---
syncthing_user: "syncthing"
syncthing_uid: 5000
syncthing_group: "syncthing"
syncthing_gid: 5000
syncthing_home: "/opt/syncthing"
syncthing_shell: "/usr/sbin/nologin"
syncthing_conf: "{{syncthing_home}}/config.xml"
# Have to define this twice due to https://github.com/ansible/ansible/issues/8603
syncthing_version: "1.3.0"
syncthing_strelaysrv_version: "1.0.1"
syncthing_stdiscosrv_version: "1.0.1"
syncthing_stdiscosrv_url: "stdiscosrv.wellesleynet.com"
syncthing_strelaysrv_url: "strelaysrv.wellesleynet.com"
syncthing_ports:
  syncthing:
    port: 22000
    proto: tcp
  syncthing_broadcast:
    port: 21027
    proto: udp
  syncthing_gui:
    port: 8384
    proto: tcp
  strelaysrv_data:
    port: 22067
    proto: tcp
  strelaysrv_status:
    port: 22070
    proto: tcp
  stdiscosrv_replication:
    port: 19200
    proto: tcp
  stdiscosrv:
    port: 8443
    proto: tcp
syncthing_data:
  syncthing:
    verison: "{{syncthing_version}}"
    dl_url: "https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-{{ ansible_system | lower }}-amd64-v{{syncthing_version}}.tar.gz"
    dir: "{{syncthing_home}}/syncthing"
    dir_perms: "0700"
    bin: "{{syncthing_home}}/syncthing/syncthing-linux-amd64-v{{syncthing_version}}/syncthing"
    cert: "{{syncthing_home}}/syncthing/cert.pem"
    key: "{{syncthing_home}}/syncthing/key.pem"
    systemd_unit_file: "/etc/systemd/system/syncthing.service"
    url: "syncthing.wellesleynet.com"
  strelaysrv:
    verison: "{{syncthing_strelaysrv_version}}"
    dl_url: "https://github.com/syncthing/relaysrv/releases/download/v{{syncthing_strelaysrv_version}}/strelaysrv-linux-amd64-v{{syncthing_strelaysrv_version}}.tar.gz"
    dir: "{{syncthing_home}}/strelaysrv"
    dir_perms: "0755"
    bin: "{{syncthing_home}}/strelaysrv/strelaysrv-linux-amd64-v{{syncthing_strelaysrv_version}}/strelaysrv"
    cert: "{{syncthing_home}}/strelaysrv/cert.pem"
    key: "{{syncthing_home}}/strelaysrv/key.pem"
    systemd_unit_file: "/etc/systemd/system/strelaysrv.service"
    url: "strelaysrv.wellesleynet.com"
  stdiscosrv:
    verison: "{{syncthing_stdiscosrv_version}}"
    dl_url: "https://github.com/syncthing/discosrv/releases/download/v{{syncthing_stdiscosrv_version}}/stdiscosrv-linux-amd64-v{{syncthing_stdiscosrv_version}}.tar.gz"
    dir: "{{syncthing_home}}/stdiscosrv"
    dir_perms: "0755"
    bin: "{{syncthing_home}}/stdiscosrv/stdiscosrv-linux-amd64-v{{syncthing_stdiscosrv_version}}/stdiscosrv"
    cert: "{{syncthing_home}}/stdiscosrv/cert.pem"
    key: "{{syncthing_home}}/stdiscosrv/key.pem"
    systemd_unit_file: "/etc/systemd/system/stdiscosrv.service"
    url: "stdiscosrv.wellesleynet.com"
