---
- name: "Include nginx-proxy vars"
  include_vars:
    file: "../../nginx-proxy/vars/main.yml"

- name: "Create homeassistant dirs"
  file:
    path: "{{ homeassistant_conf_dir }}"
    state: directory
    mode: 0755
    group: "root"
    owner: "root"

- name: "Install home-assistant configuration file"
  template:
    src: configuration.yaml.j2
    dest: "{{ homeassistant_conf_dir }}/configuration.yaml"
    mode: 0644
    owner: "root"
    group: "root"
  notify: Restart home-assistant

# Unfortunately auth setup post-install is a "manual" thing after 0.77-ish
# The switch to the builtin auth provider makes it nearly impossible to
# automate the deployment of users/passwords.
# Note to self: if provisioning a fresh install, log in and configure
# an initial account.
- name: "Installl misc home-assistant supporting conf files"
  copy:
    src: "{{ item }}"
    dest: "{{ homeassistant_conf_dir }}/{{ item }}"
    mode: 0644
    owner: "root"
    group: "root"
  notify: Restart home-assistant
  with_items:
    - automations.yaml
    - customize.yaml
    - customize_domain.yaml
    - customize_glob.yaml
    - groups.yaml
    - scripts.yaml
    - alerts.yaml
    - binary_sensors.yaml

# This is super jank.
# This whole task could be removed if ansible properly supported
# updating/editing yaml files inline (similar to the ini_file_module)
- name: "Update known_devices.yaml with existing clients"
  blockinfile:
    create: yes
    owner: root
    group: root
    mode: 0644
    path: "{{ homeassistant_conf_dir }}/known_devices.yaml"
    marker: "#####{mark} {{ item }}#####"
    block: |
      {{ lookup('file', '{{ item }}.yaml') }}
  with_items:
    - jy
    - ew
    - am
    - hk
    - em
    - km
  notify: Restart home-assistant

# Download image prior to bouncing service, minimizes downtime
# (Handy trick from some old pals at Uber...)
- name: "Pull home-assistant container"
  docker_image:
    name: "{{ homeassistant_docker_image }}:{{ homeassistant_docker_image_version }}"

# This is clunky and makes everything systemd dependent, fixme!
- name: "Create home-assistant systemd unit file"
  template:
    src: home-assistant.service.j2
    dest: "{{ homeassistant_systemd_unit_file }}"
    mode: 0644
    owner: "root"
    group: "root"
  notify: Restart home-assistant

- name: "Start/enable home-assistant"
  systemd:
    name: "{{ homeassistant_service }}"
    state: started
    enabled: yes
    daemon_reload: yes

# The home-assistant lifx integration changed behavior somewhere around 0.80.3.
# As a result, simply allowing incoming UDP port 56700 no longer works, the
# lifx bulbs will attempt to establish a connection on a random port.
# The source port is seemingly always 56700 though.
# https://github.com/home-assistant/home-assistant/issues/17949
- name: "Open firewalld for home-assistant lifx functionality"
  firewalld:
    rich_rule: rule family=ipv4 source address={{ net_mask | ipaddr('net') }} source-port port=56700 protocol=udp accept
    state: enabled
    permanent: True
    immediate: True
  vars:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
  notify: Restart home-assistant

- name: "Create nginx-proxy config"
  template:
    src: home-assistant.conf.j2
    dest: "{{ nginx_proxy_conf_dir }}/home-assistant.conf"
    mode: 0644
    owner: "root"
    group: "root"
  notify: Restart nginx-proxy
