---
rclone_version: "1.40"
rclone_download_url: "https://github.com/ncw/rclone/releases/download/v{{rclone_version}}/rclone-v{{rclone_version}}-linux-amd64.zip"
rclone_dir: "/root/rclone/"
rclone_bin: "{{rclone_dir}}/rclone-v{{rclone_version}}-linux-amd64/rclone"
rclone_conf: "{{rclone_dir}}/rclone.conf"
rclone_backup_dir: "/mnt/bananastand/backups/cloud"
rclone_conf_data: "{{vault_rclone_conf_data}}"
rclone_sync_args: "--drive-chunk-size 256M --config {{rclone_conf}}"
