---
- name: "Include nginx-proxy vars"
  include_vars:
    file: "../../nginx-proxy/vars/main.yml"

- name: "Create syncthing group"
  group:
    name: "{{syncthing_group}}"
    gid: "{{syncthing_gid}}"

- name: "Create syncthing user"
  user:
    name: "{{syncthing_user}}"
    uid: "{{syncthing_uid}}"
    group: "{{syncthing_group}}"
    home: "{{syncthing_home}}"
    shell: "{{syncthing_shell}}"

- name: "Create syncthing dirs"
  file:
    path: "{{item.value.dir}}"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    state: directory
    mode: "{{item.value.dir_perms}}"
  with_dict: "{{syncthing_data}}"

- name: "Download syncthing binaries"
  unarchive:
    src: "{{item.value.dl_url}}"
    dest: "{{syncthing_home}}/{{item.key}}"
    remote_src: yes
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
  with_dict: "{{syncthing_data}}"

- name: "Copy syncthing certs"
  copy:
    src: "{{item.key}}.cert.pem"
    dest: "{{item.value.cert}}"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    mode: 0600
  with_dict: "{{syncthing_data}}"
  notify: "Restart {{item.key}}"

- name: "Copy syncthing keys"
  copy:
    src: "{{item.key}}.key.pem"
    dest: "{{item.value.key}}"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    mode: 0400
  with_dict: "{{syncthing_data}}"
  notify: "Restart {{item.key}}"

- name: "Copy syncthing xml config"
  copy:
    src: config.xml
    dest: "{{syncthing_data.syncthing.dir}}/config.xml"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    mode: 0600
  notify: "Restart syncthing"

- name: "Create syncthing systemd unit files"
  template:
    src: "{{item}}.service.j2"
    dest: "{{syncthing_data[item].systemd_unit_file}}"
    mode: 0644
    owner: "root"
    group: "root"
  notify: "Restart {{item}}"
  with_items:
    - stdiscosrv
    - strelaysrv
    - syncthing

- name: "Start/enable syncthing services"
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - stdiscosrv
    - strelaysrv
    - syncthing

- name: "Create syncthing nginx-proxy configs"
  template:
    src: "{{item}}.conf.j2"
    dest: "{{nginx_proxy_conf_dir}}/{{item}}.conf"
    mode: 0644
    owner: root
    group: root
  notify: Restart nginx-proxy
  with_items:
    - stdiscosrv
    - syncthing

- name: "Open firewalld for syncthing services"
  firewalld:
    port: "{{syncthing_ports[item].port}}/{{syncthing_ports[item].proto}}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - strelaysrv_data
    - syncthing
