---
- name: "Include nginx-proxy vars"
  include_vars:
    file: "../../nginx-proxy/vars/main.yml"

- name: "Create syncthing group"
  group:
    name: "{{syncthing_group}}"
    gid: "{{syncthing_gid}}"

- name: "Create syncthing user"
  user:
    name: "{{syncthing_user}}"
    uid: "{{syncthing_uid}}"
    group: "{{syncthing_group}}"
    home: "{{syncthing_dir}}"
    shell: "{{syncthing_shell}}"

- name: "Download syncthing binaries"
  unarchive:
    src: "{{item.value.dl_url}}"
    dest: "{{syncthing_dir}}"
    remote_src: yes
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
  with_dict: "{{syncthing_data}}"

- name: "Copy syncthing certs"
  copy:
    src: "{{item.key}}.cert.pem"
    dest: "{{item.value.cert}}"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    mode: 0600
  with_dict: "{{syncthing_data}}"

- name: "Copy syncthing keys"
  copy:
    src: "{{item.key}}.key.pem"
    dest: "{{item.value.key}}"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    mode: 0400
  with_dict: "{{syncthing_data}}"

# This is a hack because strelaysrv doesn't support specifying
# cert and key files; only a dir with "cert.pem" and "key.pem"
- name: "Create symlinks for pems for strelaysrv"
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{syncthing_user}}"
    group: "{{syncthing_group}}"
    state: link
  with_items:
    - { src: "{{syncthing_data.strelaysrv.cert}}", dest: "{{syncthing_dir}}/cert.pem" }
    - { src: "{{syncthing_data.strelaysrv.key}}", dest: "{{syncthing_dir}}/key.pem" }

- name: "Create syncthing systemd unit files"
  template:
    src: "{{item}}.service.j2"
    dest: "{{syncthing_data[item].systemd_unit_file}}"
    mode: 0644
    owner: "root"
    group: "root"
  notify: "Restart {{item}}"
  with_items:
    - stdiscosrv
    - strelaysrv

- name: "Start/enable syncthing services"
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - stdiscosrv
    - strelaysrv

- name: "Create stdiscosrv nginx-proxy config"
  template:
    src: stdiscosrv.conf.j2
    dest: "{{nginx_proxy_conf_dir}}/stdiscosrv.conf"
    mode: 0644
    owner: root
    group: root
  notify: Restart nginx-proxy

- name: "Open firewalld for strelaysrv"
  firewalld:
    port: "{{syncthing_ports[item].port}}/{{syncthing_ports[item].proto}}"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - strelaysrv_data
