---
- import_playbook: base.yml
- import_playbook: wireguard.yml
- import_playbook: nginx.yml
- import_playbook: nuc.yml
- import_playbook: home-assistant.yml
- import_playbook: nut.yml
- import_playbook: steam.yml
- import_playbook: plex.yml
- import_playbook: filebrowser.yml
- import_playbook: zfs.yml
- import_playbook: clevis.yml
- import_playbook: k8s.yml
- import_playbook: x11vnc.yml
