---
- name: "Include OS specific vars"
  include_vars: "{{ ansible_distribution }}.yml"

- name: "Remove OS docker packages"
  package:
    name: "{{ docker_os_docker_packages }}"
    state: absent

# We have to use OS specific package modules (yum, apt) to install Docker due
# due to the different options, unfortunately vanilla package won't suffice.
- name: "Include OS specific tasks"
  include_tasks: "{{ ansible_distribution }}.yml"

- name: "Install Ansible Docker deps"
  package:
    name: "{{ docker_ansible_deps }}"
    update_cache: yes
  notify: "Restart docker"

- name: "Start/enable docker"
  service:
    name: "docker"
    state: started
    enabled: yes
