---
- name: "Add Docker apt GPG key"
  apt_key:
    state: present
    url: "{{ docker_apt_key }}"

- name: "Add Docker apt repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: "Install Docker package"
  apt:
    name: "{{ docker_packages }}"
    update_cache: yes
    install_recommends: no
    state: present
  notify: "Restart docker"

