---
docker_os_docker_packages:
  - docker
  - docker-common
  - docker-engine
docker_deps:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
docker_version: 19.03.12-3.el{{ ansible_distribution_major_version }}
docker_packages:
  - docker-ce-{{ docker_version }}
  - docker-ce-cli-{{ docker_version }}
docker_ansible_deps:
  - docker-python
docker_rpm_key: https://download.docker.com/linux/centos/gpg
