---
docker_os_docker_packages:
  - docker
  - docker-engine
  - docker.io
docker_deps:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
docker_version: 5:19.03.8~3-0~ubuntu-{{ ansible_distribution_release }}
docker_packages:
  - docker-ce={{ docker_version }}
  - docker-ce-cli={{ docker_version }}
docker_ansible_deps:
  - python3-docker
docker_apt_key: https://download.docker.com/linux/ubuntu/gpg

