---
- name: Include OS specific vars
  include_vars: "{{ ansible_distribution }}.yml"

# preflight stuff

- name: Deactivate swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

# CentOS fstype = swap
# Ubuntu fstype = none
- name: Disable swap
  mount:
    state: absent
    fstype: swap
    path: "{{ item }}"
  with_items:
    - swap
    - none

- name: Load kmod deps for k8s
  modprobe:
    name: "{{ item }}"
  with_items: "{{ k8s_kmod_deps }}"

- name: Configure kubernetes sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ k8s_sysctl_file }}"
    sysctl_set: yes
  with_dict: "{{ k8s_sysctl }}"

- name: Include OS specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Start/enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

# Sanity check to make sure we either have 1 or 3 masters
# We either want one master or 3 nodes (HA)
- name: Check for correct number of master nodes
  assert:
    that: (master_count == '1' or master_count == '3')
    fail_msg: "Invalid number of master nodes in inventory. Should be 1 or 3"
    success_msg: "Correct number of master nodes defined in ansible inventory"
  run_once: True
  vars:
    master_count: "{{ groups['master'] | length }}"

- name: Include kubernetes master tasks
  include_tasks: master.yml
  when: "'master' in group_names"

- name: Include kubernetes worker tasks
  include_tasks: worker.yml
  when: "'worker' in group_names"

# We should have a cluster at this point, time to start applying some yaml

# Set some base facts for reuse later
- name: Set kubernetes config facts
  set_fact:
    k8s_master: "{{ groups['master'] | first }}"
    k8s_config: /etc/kubernetes/admin.conf

# All commands will run from a master, wrap in a block to DRY out
# delegate_to / run_once
- block:
  # Gonna use weave
  - name: Install pod network add-on
    k8s:
      state: present
      definition: "{{ lookup('file', '00_weave_' + k8s_version + '.yml') }}"
      kubeconfig: "{{ k8s_config }}"

  - name: Install metallb load balancer
    k8s:
      state: present
      definition: "{{ lookup('file', '01_metallb.yml') }}"
      kubeconfig: "{{ k8s_config }}"

  - name: Configure metallb load balancer
    k8s:
      state: present
      definition: "{{ lookup('template', '02_metallb_config.yml.j2') }}"
      kubeconfig: "{{ k8s_config }}"

  run_once: True
  delegate_to: "{{ k8s_master }}"
