switch.leviton_dzpa11lw_plugin_appliance_module_switch:
  friendly_name: Christmas Tree
  icon: mdi:pine-tree
switch.leviton_dzpa11lw_plugin_appliance_module_switch_2:
  friendly_name: Nightstand Light
  icon: mdi:weather-night
light.linear_lb60z1_dimmable_led_light_bulb_level:
  friendly_name: Norpoc Light
