living_room:
  name: Living Room
  entities:
    - light.linear_lb60z1_dimmable_led_light_bulb_level
    - light.living_room_floor_lamp
    - binary_sensor.apartment_door_sensor
    - media_player.double_r_diner
    - switch.leviton_dzpa11lw_plugin_appliance_module_switch

bedroom:
  name: Bedroom
  entities:
    - switch.leviton_dzpa11lw_plugin_appliance_module_switch_2

office:
  name: Office 
  entities:
    - light.office_sphere
    - sensor.ups_status_data
    - sensor.ups_battery_charge 
    - sensor.ups_battery_runtime
    - sensor.ups_load
