living_room:
  name: Living Room
  entities:
    - switch.leviton_dzpa11lw_plugin_appliance_module_switch
    - binary_sensor.apartment_door_sensor
    - light.living_room_floor_lamp

bedroom:
  name: Bedroom
  entities:
    - switch.leviton_dzpa11lw_plugin_appliance_module_switch_2

office:
  name: Office 
  entities:
    - sensor.ups_status_data
    - sensor.ups_battery_charge 
    - sensor.ups_battery_runtime
    - sensor.ups_load
