---
- name: "Include OS specific vars"
  include_vars: "{{ansible_distribution}}.yml"

- name: "Include OS specific tasks"
  include_tasks: "{{ansible_distribution}}.yml"

- name: "Create filebrowser dir"
  file:
    path: "{{filebrowser_dir}}"
    state: directory
    mode: 0755
    group: "{{ filebrowser_group }}"
    owner: "{{ filebrowser_user }}"

- name: "Download filebrowser"
  unarchive:
    src: "{{ filebrowser_download_url }}"
    dest: "{{ filebrowser_dir }}"
    remote_src: yes

# Create an ini config file from template
- name: "Create filebrowser config file"
  template:
    src: filebrowser.conf.j2
    dest: "{{ filebrowser_conf }}"
    mode: 0644
    group: "{{ filebrowser_group }}"
    owner: "{{ filebrowser_user }}"
