---
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove ufw
  apt:
    name: ufw
    state: absent
    purge: yes

- name: "Set locale"
  locale_gen:
    name: "{{ locale }}"
    state: present
