---
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
  when: "'k8s' not in group_names"

- name: Remove ufw
  apt:
    name: ufw
    state: absent
    purge: yes

- name: "Set locale"
  locale_gen:
    name: "{{ locale }}"
    state: present

# Don't tell me how to live my life, Ubuntu...
- name: "Remove Ubuntu bloatware"
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
      - ubuntu-release-upgrader-core
      - ubuntu-advantage-tools
      - landscape-common
      - update-notifier-common
      - motd-news-config

- name: "Disable motd-news timer"
  systemd:
    name: motd-news.timer
    state: stopped
    enabled: no
  when: ansible_distribution_release == "bionic"
