---
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove ufw
  apt:
    name: ufw
    state: absent
    purge: yes

- name: "Set locale"
  locale_gen:
    name: "{{locale}}"
    state: present

# Don't tell me how to live my life, Ubuntu...
- name: "Remove Ubuntu bloatware"
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - ubuntu-release-upgrader-core
    - ubuntu-advantage-tools
    - landscape-common
    - update-notifier-common

- name: "Disable motd-news timer"
  systemd:
    name: motd-news.timer
    state: stopped
    enabled: no
  when: ansible_distribution_release == "bionic"

- name: "Disable motd-news in /etc/default"
  lineinfile:
    dest: /etc/default/motd-news
    line: "ENABLED=0"
    state: present
    regexp: "^ENABLED="
  when: ansible_distribution_release == "bionic"
