---
timezone: UTC
lets_encrypt_pub_key: "/etc/letsencrypt/live/{{inventory_hostname}}/fullchain.pem"
lets_encrypt_priv_key: "/etc/letsencrypt/live/{{inventory_hostname}}/privkey.pem"
ssh_keys:
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBO98zbO4QQPP+G7Gesk+yfN8hZK2v2EYkzDUL9nz4jxhKvs5uqcuj86qC4Ilmqkbj+lMCV7NApinRIbJ1+Lf6Gg=
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCoG0tPaP+xcSt1GdAnQVxETOBr9moK2D6xBBDOdNW0SuinOR7WjjuSNnQrMOD5DlYixIj4RTq6pvFWaKUwo5PI=
  - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIN1jQWOns9kjPtH+DlvAqO0e3G6yUsMkaNagTO8YtlYvAAAABHNzaDo=
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF5xv+MLeb1YN1Pa7eMARu9mu/IetYcxgIlbK0gtD6WRiK4WBv71KEJQ40AI9/2AUNG/nKND9UNNMw0V68gqHCQ=
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOmEwejZ5SPhIYgcyTQBc+giKbsxvGn6Z3IulCQtlwxgCAxQv/r+izpN6vDcxTkHo633/JqPujZwh+A0Jyrq77Y=
certbot_username: "{{vault_certbot_username}}"
ssl_cipher_suite: "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
homeassistant_unifi_password: "{{vault_homeassistant_unifi_password}}"
unifi_url: "unifi.wellesleynet.com"
zorya_root_password: "{{vault_zorya_root_password}}"
homeassistant_lifx_api_token: "{{vault_homeassistant_lifx_api_token}}"
group_dict: "{{ vault_group_dict }}"
user_dict: "{{ vault_user_dict }}"
locale: "en_US.UTF-8"
x_plex_token: "{{ vault_x_plex_token }}"
