---
timezone: UTC
lets_encrypt_pub_key: "/etc/letsencrypt/live/{{inventory_hostname}}/fullchain.pem"
lets_encrypt_priv_key: "/etc/letsencrypt/live/{{inventory_hostname}}/privkey.pem"
ssh_keys:
  - jyundt-id_rsa.pub
certbot_username: "{{vault_certbot_username}}"
ssl_cipher_suite: "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
homeassistant_unifi_password: "{{vault_homeassistant_unifi_password}}"
unifi_url: "unifi.wellesleynet.com"
zorya_root_password: "{{vault_zorya_root_password}}"
homeassistant_lifx_api_token: "{{vault_homeassistant_lifx_api_token}}"
group_dict: "{{ vault_group_dict }}"
user_dict: "{{ vault_user_dict }}"
cronwrapper: "ohmycron"
cronwrapper_url: "https://raw.githubusercontent.com/instacart/ohmycron/master/ohmycron"
cronwrapper_path: "/usr/local/bin"
cronwrapper_cmd: "{{cronwrapper_path}}/{{cronwrapper}}"
locale: "en_US.UTF-8"
