---
homeassistant_docker_image: "homeassistant/home-assistant"
homeassistant_docker_image_version: "0.59.2"
homeassistant_port: 8123
homeassistant_conf_dir: "/root/homeassistant"
homeassistant_service: "home-assistant"
homeassistant_systemd_unit_file: "/etc/systemd/system/{{homeassistant_service}}.service"
homeassistant_unifi_user: "homeassistant"
homeassistant_web_password: "{{vault_homeassistant_web_password}}"
