---
oauth2_proxy_version: "2.2"
# These download URLs are not consistent between versions, FYI
oauth2_proxy_download_url: "https://github.com/bitly/oauth2_proxy/releases/download/v{{ oauth2_proxy_version }}/oauth2_proxy-{{ oauth2_proxy_version}} .0.{{ ansible_system | lower }}-amd64.go1.8.1.tar.gz"
# The release tarballs include the version and golang version in their directory name.
# Let's be lazy and derive the name of this directory
oauth2_proxy_bin: "{{ oauth2_proxy_dir }}/{{ oauth2_proxy_download_url | urlsplit('path') | basename }}/oauth2_proxy"
