---
- name: "Install kvm packages"
  package:
    name: "{{item}}"
    update_cache: yes
  with_items: "{{kvm_packages}}"

- name: "Enable kvm services"
  service:
    name: libvirtd
    state: started
    enabled: True
