---
filebrowser_user: "root"
filebrowser_group: "wheel"
filebrowser_version: "1.8.0"
filebrowser_download_url: "https://github.com/filebrowser/filebrowser/releases/download/v{{ filebrowser_version }}/{{ ansible_system | lower }}-amd64-filebrowser.tar.gz"
filebrowser_dir: "/root/filebrowser"
filebrowser_bin: "{{ filebrowser_dir }}/filebrowser"
filebrowser_db: "{{ filebrowser_dir }}/filebrowser.db"
filebrowser_conf: "{{ filebrowser_dir }}/filebrowser.conf"
filebrowser_scope_path: "/data"
filebrowser_address: "127.0.0.1"
filebrowser_port: 8080
