---
filebrowser_version: "1.8.0"
filebrowser_download_url: "https://github.com/filebrowser/filebrowser/releases/download/v{{ filebrowser_version }}/{{ ansible_system | lower }}-amd64-filebrowser.tar.gz"
filebrowser_bin: "{{ filebrowser_dir }}/filebrowser"
filebrowser_db: "{{ filebrowser_dir }}/filebrowser.db"
filebrowser_conf: "{{ filebrowser_dir }}/filebrowser.yml"
filebrowser_scope_path: "/data"
filebrowser_address: "127.0.0.1"
filebrowser_port: 8080
#I may regret this later but I'm using the same UID/GID as my normal (non-root) user to help avoid weird file permissions issues
filebrowser_user: "filebrowser"
filebrowser_uid: 5002
filebrowser_group: "users"
filebrowser_gid: 2001
filebrowser_shell: "/usr/sbin/nologin"
