---
- name: "Include OS specific vars"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include OS specific tasks"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "Start/enable plex"
  service:
    name: "{{ pms_service }}"
    state: started
    enabled: yes
