---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-nginx-maxmind
  namespace: ingress-nginx
spec:
  encryptedData:
    MAXMIND_LICENSE_KEY: AgCEQeLU7p9FNgvakxlNYoF69j6F36nJPlFryj0NmG7XvgtXRpJRQCDuBq1cvRd5byT+EGsUReN8eD0N78wfaPQzwateWhOVUijb064J5AkvdQKcWmrOUIECmUymNk6+vizYCRQeWTqpVVOx0cyS4lsKX2TKifCl9BKn3DvDOVDF6FY6nh1Jsh17rS0bHlMM0c6M8M6RSXUsZiGv8Az/JOgI3XfyIpSc8XQBLx29fhagzWT3ai9hL9xiqJRgNkzc0rciTJ++zdzZL5n9j+E7XrbLE/lKMooABoees8J35HKbyhuSCohJICoW5LjW9JrNDY+B0HpEaxfT+s2aO2yaFudbCVKS6KQnaTo6iB2WwIlIdiJJY/0hImXNcFJ6lEPDZeyEF9dsRVCDtLNjkZfiMd9UoBBVh4OD+KKru12s/Q46y7U0nXY3UPTqTsSxinYjBNmWG2T2xTn556xyZjbocuheQihCEOx29Ed71zrW8ubb1h1se+9vQ2qVSRnE1P2I8fCa3Py/zDkGTTLFaeAYjRB1CiFwJ81qtzJVq72TqEI+ZKZwe72nNMx+yPbZDsb30tz7ONf12emAwirQ3yWFHTa1c5cuOxH679z3i2v+ZvgXvHBM/TE6Dbu8tijEN9e8l3T+orNA/IZ0W7ueGbGnTITdDV6pu/l6uHPAlpDtvwJ0m3AZxb4yp3fdoD6q8QCFfsmBC0kYVyXD7TqdpQwlz8ni
  template:
    metadata:
      creationTimestamp: null
      name: ingress-nginx-maxmind
      namespace: ingress-nginx
    type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
# custom, added for syncthing
data:
 #636: "default/glauth:636"
 #22000: "default/syncthing:22000"
 #22067: "default/syncthing:22067"
 #22070: "default/syncthing:22070"
 #19200: "default/syncthing:19200"
 #9009: "default/croc:9009"
 #9010: "default/croc:9010"
 #9011: "default/croc:9011"
 #9012: "default/croc:9012"
 #9013: "default/croc:9013"
  1883: "default/mosquitto:1883"
  8883: "default/mosquitto:8883"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lb-dhparam
  namespace: ingress-nginx
spec:
  encryptedData:
    dhparam.pem: AgCPayII1Ieiql9LfJElFJyxbB7CymyFGw5CwhsLuEEoaC9T2Sf2C8k+FUMyyaaGOGjKzdcEw8S7CBLCMD3eD5mIMqHvUdTK62Hlw8jZVnuqDxUMTomIKtN2YSrBO+dKc93ZZ0+8/GmPfla+hpIFaUqIvoExcaMFtSSSsROoPMBT4d+1vftBGg5TJe6Ks0yQxl5fm9Q92iQbAcdHerH9AkCPZv0m3YBzelp4DK8KIN4ypqMxF/fF9CROjN/zaA3WA3+LO/42VRJQfL+8d9salJ2CDgTivIDoqoYa/wnNPbPPoWEWJrkM6Fl2fni5B6VSt66z8A/JD5iEf74Bj+0GDpVnu/IgelHMiSUmJ7NVmBWSDcvXJ48lKb3yKqd/SxbCjLLBoQPRtrOYfbMlRvNzltugQfxr/VTptpU6SEvnb6+6YB1Sb5ue0fnBgkcXFNk8NCfIsYtnpaGlNTMY6T4ClvF18iQ+rRDL7mIukQjGKgYSrakKT7HXaR8cZuNxTgyIbKh8Tums+f+mZtt0as9AbNH92+A8zgbDiQO3eVYu5DOcFmc1baM6uSGpo/gDdUx7UHb3yUm8x4iv2T8glVGwTNH+wGJzxBOihPR2RdjFO8Mjpr/rKQ8EkTVov19T9UBho1iFPCdGk/HNlix+jg6HpQV4GqmjFQAKYMkJcS1CSugk5NcL9tCz8kggNh4KN7jyeICNJurJtQdmKmb+3zLEvV6O8DmR7pHKFOaWf/ykvIAGeTK+vM3frxmxttFyiB5hAGTLZXWpgkY5lDCLEZHuKJDkkosp4nMA1EOhkXhWG1LLLmIlSfUvhwL1xInrwI721iN1WtyVLaS7bSFyu4eEqfnhSY6F8Wum70JMzPEz5Ijpr2XZQt617XOCKyfHd9Rb5Rf+ktmziLQve7pRdFKn4z25V/0j8YjevNKriReleFtbIBU4Icd5H8MSNOiNQJqGuSybq5W/WzJ+aLQvZsIJK7Ij8nYB/RN+fcezS5UwYpgba0Ka3ryiyxbmx7s/oAMlSfpsOM+GkpAwOpS3FC2UiOAQk3hnIWwRGFx7hC0tzu+UXOwfAadZr1iYYMVEYGbqVW1u+Vdhq100ULEQa6yK1Uy9Mhlu0K5noD/WLcRT8AUiC7y8p2/MoYTcQWA0VHlR+P15ZbX98UVEy9NHknl7lrfYn8Km5Q/uGrx1zQJW3CFE1n4AtscHBfF/eA8KS+R++UNYmG90j4GSF+qqR6Uz2a27swEuJe/qFMFzmPFgj1oMot3P7q0CDXlf
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
      name: lb-dhparam
      namespace: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-headers
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  X-Country: "$geoip2_city_country_code"
