apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy
  namespace: default
spec:
  encryptedData:
    oauth_allowed_emails: AgA04IrYwHWQDoDBolnhF4I95u0TreBwhC0ZE3xAS7weLiK5ujXQgxAWjYiBniLJObGVuIXm1Zbi9ucLKbRykLIz0EpeqkFUmLLL4Gi4dfKD9yGpe3BiahBZOUUQ0c+p8iEkcttl8cK8yWPB0K4cWFTn61UmNp6RsqDl0sraz88b3qt3YQaaNVLAbvkh/ir1/3iOVZbgdgnlEKUF+eoVLctkHt1aw8Wx1VH0etwC+nF8cJ8AnVynhR47DMZhmRS6WcnZ3qpN9B6MuxNPBj1gAKz6xiK9Tfed3cwbdqROMdXSvyJl7fhiIsw+DH8rJ8bgkPSZqYAjCX67WPDEHePGzoJpTiMOzQpAzHHMpIgvlpeBzE4Ig8w0s/6adKQ0ccJRo5T3+H0zWxEtXqA3ipgXavpbTP6T8FAKLoZv/9v+5qcMx+soXxFBUXkITfVdYw+drU1QbY2qZkzlZtrqzrr4P1y0YfMCtLzKX0oD2lrXOCvLj77QxDK/Q6PeIN4rtRD9V7yIoFWexg0O6VbA+uuf5tssn4iydpjt2a011evMcnolabASFLWvBRrv4x0BAdSKNu/0htbyEpNlAOioKlo+wBO4MF7u2I5Qr8TaGI4sVZp2JKDrQR1+7at/RdprW+zobv/Po7JUijafRFsM/LPHL5zQb6EW1LNHDF3VGvMKuBAGy0qtfY87wSjJu61OBQf29FXx6fuEINrekLaoUUPJ7Od5gYfWMtWoOfgKQaP4YLzXKn5RcF3xDg==
    oauth2_proxy_client_id: AgAYB5dkjkV8xsp6zxlZKAVZ7o2puf41oP9AW/d4GVHkrzq2kUjpCUKrxOE9pVxE+EU1NBbtY16TcHJNwegyp33+60QnYtCvQstBzS99tO2l2WUaREQCCTB30MFfALZ/si+RngZamoQTbzJTyJ0bc867ebuurUrbNFMmLi9Bcgc/SH1Dfqx038cvJKqPKkdZr/eZV+cUDU1OWz9XZgnGa+cHpBqOS7pz2JwQCJTheNU/UFBurYtsVC3d5yLpcBHVk5sELUHrRn2EjZODzmscwKGYX6tbj3AofR8/GlBdoJZSBtJb4hkvfJUyjfMoulQrbc+lc1rBDci42ze5m/ItphiKNjhQnsteh4DpkRQyzMCOb/10g35h9OLRF5XcrkEm9eiLpd4PxCNODgplINSvcZmFeKtmDOsokD+g98uXJG5AaZombkyyv/gQD1EPZL3QBDdbM2VNNtrXA7eT1+DPjPZsIvIxhRPUuDkL3MC21K0A7VEJByzI3YSvhsl7w4hMZ8Vg+wLgwnobnVBEBe1twP4rQNpeuQoRjAE/I1H0V/hGJEKya+02DcTBkJoxvCG4rSp+1iMBfbXJRluiOmff9JtMEeAGHOZiFBSth7Ppu0TCjaBFxeGv+zMAUi6cSfgawkoqj+oBz1Sdx21J5ap45sf0r2OWMheWQj5ewDnCtBoC1rKzTIWQXJyi6Utylu4YUh7XUWGjzsB0U3Rfle5oJicIvaY6fiAtVFymF88SLG4bBAV8uTSR4Rym4I4qfzTy/ytUkA1pQ1hjTwgmHpueRwewuA7GULuUmn0=
    oauth2_proxy_client_secret: AgCFYjsgFOJO2QQmCufLxvVN++egkdfa4dIauiKiH1VhltK9+c9b0Qxn7QKcVB7ahOUubEtJWwjMzOcJnjVWh9TLAUeQ82VOevn/RMV8ZFk4rWgHNMsU67aJ8ZVCBHz9vk5e8DdemltfTNv1VZlz/FjO65nehi55d1o0ygCN26JM2w3I1U6BNqIydQDH6QBfaC7xx5yIC0OI3oUelJDuEMYnMitd+Qav2zl28AGNq/hTP+gmz/B4VwknOzlHUF9OQ7aBAqoNd2TS6UvvYGCmyu2DGBOlJFPUhiqtyM/NER3HCA7KisilIEW9Tv6p/3dMPCn9Zv5Qc5j4/1JGXWK4zuGevHaInTPuZuQ2DJkn1PaE8BC5+mJ7+z5A3eI1clKW1kGNVlxjTQdXgC0vss1oWG5oOJahemDCfgtJ3GZiEEfN+pB2j5yNkuNTMAY9PiPLJqDtjqPo4rNaYmYpjqadq5tdtUfksEtrLyV5z1FqyZIup54/V6XQEXdKNJsIZA28wphocuJy6EZ4bfZ1X5iXB5u7izUnmXdqGilF8Cg28MH8E4nsC1aRDdYTTmrUGrcif+IemtRcz2yzG5P+KRyXrvC/0/9z7mPOs0ovpqLiCrB8ueOqg6YhGJut7PSBQaojgXSRAlZ/lxXk+tvVWL+vedodM5UiBy6a4PQwQ8d3oQlK3yx4FHuGI8VnxEfzLXecfLqIXU7TWRrTFno3sS1kyu5oHGTJrihN/t0=
    oauth2_proxy_cookie_secret: AgAao+nMsRJH5CPEJGwId6ko3sm/uGN6Vi0tzww9Q0UOZOVQKO55EKYNTkP62NFsGiM2g1xM5Ml+0hjJrB0R940d5eAaQ9eNhKPp23d0fKJTi8GTZBpZIMI4IMG2IO3ovnVc/xQX+YHm0iYWXvRRdNFTHxVYZGxQb2y6OOvvyfqb0+s6YEyDc8vmFz4iav+idMIslU4iA3jo4KdvH06EJQsNlUt7om8V6P/dM7O1q+Y+CKgAmQXH8TBzdRBCzUd12poWOnm5cIK2mIYP3GzOlO0xpnG6Ec59tnVxT0m+Aw10dnpLABBoxypHGSeNro6BUX5RANDDpjTaj9i7og25UoqR3aU7q8QEVLg+BRzXJBIXqD86mlkEtJR/5f7GCHj5E+uLyEn/38h52Dgy8lbpGcWDPkjzNfnii4MsWBmP1EOoQWbAbmvwbwDZLnWaICFM2u+ok8Mg9JDSZHzBxtxaG0q1GYC91K6QejlhiLV/JH6tqSEtTZeBzsHXSstsdaI1BjUiS6FXixyY5rD0QEtNRqrVvz4nGZ1e3/xFC3gpZb80jATx3Qu6iIlMlanwTDL2ql40TEJhf70EhHOTS/Ufk9LlOG+0KzIyOUJkin5vfwdADdOnnqEFKm2/MhxOFOSs4piJx8vjm9985dSnUGCWKnBWUt1OSHuAIumSXyLfHTiNfH00sqzJ9RIS3xPEMIQYmEPrVPNxAFDbJRTaTpf7PKzUvpsm3huR+X8GKpBcHEeNoQ==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy
      namespace: default
    type: Opaque
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      volumes:
      - name: oauth2-proxy
        secret:
          secretName: oauth2-proxy
      containers:
      - args:
        - -provider=google
        - -upstream=file:///dev/null
        - -http-address=0.0.0.0:4180
        - -cookie-httponly=true
        - -cookie-secure=true
        - -set-xauthrequest
        - -authenticated-emails-file=/etc/oauth2-proxy/oauth_allowed_emails
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: oauth2_proxy_client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: oauth2_proxy_client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: oauth2_proxy_cookie_secret
        image: quay.io/pusher/oauth2_proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        volumeMounts:
        - name: oauth2-proxy
          mountPath: /etc/oauth2-proxy
        livenessProbe:
          httpGet:
            path: /ping
            port: oauth2-proxy
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  ports:
  - port: 4180
  selector:
    k8s-app: oauth2-proxy
