---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia
  namespace: default
spec:
  encryptedData:
    AUTHELIA_DUO_API_SECRET_KEY: AgCf6/B3oi361tG9kUUryOt9vF6MFT6ixiuZGMnLmT/tcxw02UlsgcFFvlmc/AALppvMaWFsXhKER38Xtrem7akdPm0PIloyz5MucWNTW694JtOwXkF+lg7xjWNZ3MZ2frllZADMKJYns3WGIhWqvqwqDWviJK4yyFt68vxyuc6sR4Ez6arOd5eyFFG0EZiKLH1l2NAX/bqhO/+9HPnChObaHUjcEl5E2sObs339pzQHQMwhueZ7qJpmkBQu7ek+WuoCyAOtk23nu3Np5vwjZgxxetoBj22d/MH5Xv9AKZdR/gHOV/yPYDaFgX/uCpqmZY0XhRC9UNPR+kKLKgpmJc7xge9ZqOuQiqY04l9RU26mlYJ2MHJ2ZrgZ0Tws48sHGyYoeiZyMurj3P3vfm4S7LhYuv8rxAo1lMu+RjwwiRphlhP0iG84Vy8fJxLi7JebUBhi1m1tu/khBGnyqtONq42dxtvZsb07oZI6/IyZgMdGoKWc6tdMkuLYAZoIkW+2/81A+sMj+3ikYVYOcFMiF4jf+w95uPewBMPBXwHUkhaIsSZMxJjzKlkT1P6QYNM2ylGx/cVJiNF+Hp0WXvhfQqpn8lZEAJ9e476oxWHGOd+hlRTflnCr/cRW0XhCuXO+EQJGYhiIk7HY3zV2PYrhrVEqbP3zCW2jeOy6vY2uUfchMU97NfBX4gsL6VL7F1AfILFuQ8VfDEUAi00TqcLisNXbel+cMhyKxuE8nhRWfPF0EEpp6Lhdvw5L
    AUTHELIA_JWT_SECRET: AgAWGJDhnB5sumvQlkWV2TY8QtReAC+IV9g5TSdu5Uf4APqWdIj5wG6JWUUKKi46ngITgQJ06zXoTjkklmhQhQNmYRMKj5nyXP344wrNH8z1dg8uxZBAeN0gZRA5jxJIP8La9xv0fDceOZxlBaJFqTWlV7Bj4rLmJFoOJpjCWy7y87sR/5rCeviYLZozsb6tMYlckQOUJ8ZixJFPFb2VM6xpTRmuRA1r4YE6fLyWesBfHrQDArLr/ZbNnb0ikxurA189CilP1mD2J1P750C7Qe+Yz0cF9KZUGI14eyqJa0jOzjBhxw30ysv9qYNzeqeur+dFeTx070xEarRBIK8ft3Wm7mV9hW0y23kr/RU/IvO3s8IF5Qoa0lo0Mwqg228N4yPwj/5ty+88dlLosP53ix1B1OFqk9texIYEFmQy21AUBgY/dZKYyae8jL3Uln1wizKpvqpGK4zfB+Q9KOj3AiGotLNu8x+hDj1JWxI/iw24gR8Vo/mxrN24r54X2NCHCK1K8IQbaY1S3i5tzw6XrU+zneAbm4Fc6bJABokpFvOHMIfe3i05eb/hhaZsJhMy3hhCKrajjcYXdwZcx2MnqCOmrRCQLGHsyMW9g4q1tqjvOIaZvzXG4BWPDhWBjAMVM4QaCxDbn39VzRl8+MFmkYiyU+q2XYZp0ohE1oAOHuMUbWUphlJXRVqwfFrrWOul3Bw7KdGIn7nUpHmD+JNzKNB2moXA1gciLXj7vrjoQt9Y
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: AgCo1WWtjynviQrY0Vlb5BrAKxJkMBQnnbSzmByAfTqbFDS8CWPGDzRixNm+bIM6vxj2C6QeQvrFC1dd0S9p6OkKGfOzwMF3jftaRM5zsh0zWuDkkPc7dswcozzF41H30O87vlHpZ+lpb/Cntmxy30m7tP6ziU+J2Ykgo/Q80h5cMxaTPf/Dwcmcph4c3OWy5bpNq/GRnfoW+haQ13ZQaDb2BIsdXXNrUDIlrd9tbyDX3VrzydNoSX8yY7T55cPNc89KjZScVotVgUAuOVrEnRSonEma3KfqXloylUUiAdXYH/RVO0IHQLvI4YPYjmwAnfYz0S3AW195j5eKImOXi0oK0hVm42fvGC9RhmpUvEg6x2dJXnBo8+Bb504ZWpbvg46ZurVDZTi1lM4vgyp1474ox53/LJzKAukuUGodg7ERBqWwiRvbQs6z9xXfq7y6+mr8vdkxhLE/WcFeg2DWTAwm9w5P/Cv2XICfjvEMK0OamW3w0RxZRXiXovh9zqDx86u5+g/d9szC/oh16cOoj0i+uF7nplgGTu54MOoV2v/0SpHLUv0zrxvG5BdDvngFYa0g6KZIutjs8TpPODfNkE1kue/xEWDvhGYeY5ouUpCH/tL/luefU8FUuIYTmH426X/ixZ53NBIiWeB2ux9IiF/sWPPPuIjNWeWDycISFTxbzVZxgV3RfYvFjzlV555/XxbTBzMLSvvA6K3NIxCusNzM
    AUTHELIA_SESSION_REDIS_PASSWORD: AgAC4jBpgNtXE0NALEtUW3ZlGk6zDO/DX81BPHx7gJj7hSfCPXpfFevpot6kOC+VgiLcT5ddeDPGbbwtSLWS2GamBAYaLa0chWhYRTJ2OQyGVpmAu1gvIHrTcYowT/BRMs4EtcXszybDDhYgBDu4FSC1cYr9HGnM5zg3Bxew15UTtmj1zFFSlkMtNcqldb2kTSLnejMnp+bGY0/59ykuIqdwq2zI8FkuleL3ZGGzgb50VfJ7qfX5zrCKOzJ6hryLeylJe7G9IRCDk9d3TwfVKd61CbTpqSMXBKptat7ZNf9qrXanK5PzqgSfyX5VdZB7NbsJAh3PqNk4g2L3eSBaTG0VjYUKJokdoy8nXRDlzNmNqKzvR8GRVW6+bd+PQxli4uaaKrPIuOB62p1hM1ajCV1tXbGzUa7Q7V5uPgjYz1IU0yqxDlwpxZrQUmlrLvyXWP/GeGJ/XISYIhzgI5OPc9Co72H/uiG2DKFc6ZNsmii6Tasy4CdLumrE33JfwJQiw6GIKOmwM7/hpAn8xz00aa5l2ce5shVB9jUu8blueJLL4RymlsbqBhqbxoKIug9OojI1D7DOnlIdra8BcUdVzs1SRgfvLeD8Q/W789ev6q9fhOAXdwoUBesDr8sRv3ZWAKlnakY5Bp5ZOUhj5uaMAEA376DJAZTJ45ZXTbvmkH1ej2jjebSsCMojJVe5n9852qO5tWydJLdHS/6Ba0sFL9H2TcbhR5Y4IBUDAzC93fw51g==
    AUTHELIA_SESSION_SECRET: AgCGTVvs/Ma77+zC0xM+8UqBwkBPisytxUOQyRcun5wZM+ylrcAep3GkHfIcutCemAUqXLZ2D/9WfYl4qNFAJh1bgDx32mx7eIr9WFK5h39WS7amwP7mUomtb/JE2FxIjsggkpXCdCAoN9/b5ySo+tAopN+bD3rq8mBhudMJoeqzybLr74EHlKRPmkU23Zyg3aI1NKc7gDBWtrSmQlrnG3LHcDjH4/bNgFPvwjzc8OTED0ZeIJ+00SaKBZd5HfuNt27cGcmPPLgXJscbN5RWF2EZqOap+26Uv1+hsLQ7E1jlIEsWOoSyNVtNeqcAxDJWVFsl61OaHEDCMdvw42gs2fHJmvJO4KJgzk7YrUp+ObQMFFBXOc72YeDN7MpxW6cwyqglKX9JwnkXAX82kwkilBYHLK6zYUMc1GTFNu/589NngHeOXzhBwB/NMmNZFjx/pn+BpfUj39+U2Sta0P4mOePKlqV4Xp1hK8GqY83+39xCDC3oyZATC6hX0DK373Nv4Tcgve+PEN3TIuQaC41rn/+AuTMUPQSsuTzktALHmCuC/CC3I8tg5ovXLTdLxV65zzqNLueDc/9UsGZJxo+dWZ/VYCkkTHBH4E60o1ZAfDg38muoXN4TfaO8ME9yOO3kyB5r9U/it98ChXPtBPjugv2zQ/CErsrsVjnITswjvku5E56JC57pnntsI7rFPriiQ57DZhc0NYLfQWjjjqWU9EAiCBacxeyVbtGSfJWwU8j2Jw==
  template:
    metadata:
      creationTimestamp: null
      name: authelia
      namespace: default
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia
  namespace: default
  labels:
    name: authelia
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/apps/kubernetes/authelia
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: default
spec:
  selector:
    matchLabels:
      name: authelia
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia
  namespace: default
data:
  configuration.yml: |
    host: 0.0.0.0
    port: 80
    logs_level: info
    totp:
      issuer: authelia.kiski.co
    authentication_backend:
      file:
        path: /data/users.yml
    session:
      domain: kiski.co
      expiriation: 604800
      inactivity: 300
      redis:
        host: 127.0.0.1
        port: 6379
        database_index: 0
    access_control:
      default_policy: two_factor
    storage:
      local:
        path: /data/db.sqlite3
    duo_api:
      hostname: api-fb01a930.duosecurity.com
      integration_key: DIDV2QZN9XI2TSRGELMF
    notifier:
      smtp:
        host: smtp.gmail.com
        port: 587
        sender: jyundt@gmail.com
        username: jyundt@gmail.com
        disable_require_tls: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  serviceName: "authelia"
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - image: authelia/authelia:4.6.0
        imagePullPolicy: Always
        name: authelia
        ports:
        - containerPort: 80
        volumeMounts:
        - name: authelia-config
          mountPath: /etc/authelia
        - name: authelia-data
          mountPath: /data
        envFrom:
        - secretRef:
            name: authelia
      - image: redis:5.0.7-alpine
        imagePullPolicy: Always
        name: authelia-redis
        command:
          - "/usr/local/bin/redis-server"
        args:
          - "--requirepass"
          - "$(AUTHELIA_SESSION_REDIS_PASSWORD)"
          - "--dir"
          - "/data"
          - "-- save"
          - "300"
          - "1"
        volumeMounts:
        - name: authelia-data
          mountPath: /data
        envFrom:
        - secretRef:
            name: authelia
      volumes:
      - name: authelia-config
        configMap:
          name: authelia
      - name: authelia-data
        persistentVolumeClaim:
          claimName: authelia
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: authelia
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: authelia
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - host: authelia.kiski.co
    http:
      paths:
      - backend:
          serviceName: authelia
          servicePort: 80
  tls:
  - hosts:
    - authelia.kiski.co
    secretName: kiskico-wildcard
