---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia
  namespace: default
spec:
  encryptedData:
    AUTHELIA_DUO_API_SECRET_KEY: AgBGWLEjvE2/eSfKUTdafXxyox1J2q8WP/ePox2Hdmbxx9YMQDowNGOBLUT2PLvNAT/Nsjs8f830VU+G876nNSjORkr8OCNVIG2Sb3nuymEAA/03GQ7iOKoLEnmCpgHHdRCuwxn0vdG+DMhOZ4apVmrtqgSrZ59x5l3pjaQ+2WKyFIAUiERzf96sLLi5UtFUTikM20NMJDYvjO+oKzvY6SJ++wQJqFJUpbhqq5qykZv7eiUrV6xPSPg7Mi45ATi1059nViGqokT/IEGqDAPQV+xrcZZY1XZEyV8MmEYKpUT20T6rbpHo+y8QsSiisEyxT5uNj1pQ9iQaSbWzZSrmAgBj7CxhOqlu+y/kmC+Ulx7eXxC0qGeu1P2v2n3lezDpwv+mbhVgLdv2L2YmVrxKh7/isI+ruTKxs33QSgEWfNyj25cAUHAN9wotDrwIMBEYKT/7Xb3eYFu3UeB9FRK8tpTR17RKoTYT5xDrjm2xA/mw6xEfFY0VKnBQnkDCenC4YgnVhay9fk0bMWf7p3wWCMOIo9XWRO0ASeHzEM78qztFHbxf6gBHtUzAjZI3iDF5VwzL2IX3wKyx13M9dDlKVqAAKR+TG80Ykqfbtzhk26uOlYkCcZ6f83OfTfdmgK8J5i5d4oY9zjtY5R0GB4CR011J/e/vNvCJkWQPIXrv0b8UMvXkOCKFm2v4Wq27X5nHLy9j3DtKxyt2jsg5CF5swUdRWvZzjy8LOpSNz64z1c/4S2QQ59dfJJ6y
    AUTHELIA_JWT_SECRET: AgAKcfGWRAF351m2zsfrUP6BMMtjTaEJVcbjS9+zVsB6XMBzid8eREJwj4FGINA1XK90EW7QQx5KDBDpH1trKftOsIraATCQowg0hHHIWJTIQua/vNpa3mzzWlH3WluGFRJtwXSetKLoJzsZPITJTYqVGZhOGCNCq/cc/h5gJ5BCAxoQ7ISUS5uJd0/gmQMv60a3hVvLw4ITs1yWY2g8phxLxyf5i96J+GWt4urt8sFXjKLN0/e4JRDlObmMxVeCEKXRiDg45wOAFmNuHNCnad9i2gWmPlIVfyEbl+F5QdySURORGzZyVLv2+NhaYrTHqF6z5ZGvpFLAt7gm2dSOoZX5NBjGtGysBsxPgf6AXXR1CiIFqrGBOFbql0/g2EKsd+4muqnjuMn2QkO4bwjO0i6KqKM8qErGvIQiEjiaaEgRHgj/80m99HJVanTbPzrOlaP/sOofH+i/vS8D2YTZnld2HNZvauiKu2fDQfwdAEf2cWeLoB95b8c0FH2PdK+wDwrcW10FMec3pQ7jJ87dUrYkUm2/d4+I37gnVlM0uEq6GxIdcNVEKrs7LapYUVIKaAsSat3MxOO2MfOxNWNYMa6WXfAfY1tShXhJg/NCcfZU27bj6jrZypdG1nd6dhfhoCYifHjOnyoghqqhDKbsFh9mXHWQejXmnbNhfiL6ipTpI5LYmGPda0BvaCzYzS2NXlFpcQrfONNTy2q3OrABsJzY+Zqqgqv+32fbnzBvBgjC
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: AgCJEgf+51gMKeHGoE39KmRpK0Xm/3LLG2PrtuAy8Hyo5AMA/bNA4y4v4NECz3lurgRw0MBqZffXSujbDXs3CEAo48Mqug2qOX3jXgtkPQMJazMcVJuGFWNKau10wDGwTRmzt9ycoH25mrY5vg/awlwkllmvs+MdLBZTNTRe8HcG/NzJ+dr7wMl1/ao7zhxTkG/M8hlpeKSd4vfdVLUWN2uz/dWcooz0YIdzcD98acMuIa8pzdO3mX/yz8gFcoHbmUDByvJhKqmcSxpNw25X3x2e5kNLnNUAMGt8DugKAdlgMss2599PCU+2S5VADGmlUtR8laHFgJTOUIjovU9wyAKN4I6nX3HR+bicHJA1m0UUqfBHcKb12TRYioWeI6/glLxHn/Edaa9eBJDl0NCD1hFNjq6X5fETG7nKMGtqk08gQoFYve/Z0JarC3sqm39hKri8qrGu2I69L8XQk0KO+Qm7lwMZgu7jiMRx/2C7GcwJixUGpRi/EO2+RkaDtxuSb0dGfWwmy9iR1V1YvpKMDIiSsXhF0ZeuYSQldMl88hmSMZMwjVg0H00NM8cbwVDQMlmgBKI2raIUYXbjQj7RHEGnxPCEskk3tTwztJ9Aodx/xcX3o2LVY2exvMc3PWIGKbPy6lC+dp/Ltf5po7nlLzrEgfh9Ve1vbqtfHPc/veFxaYGWR46AeY17Hj9W6sO+Kwo0/mjHBl7EIIpB007RmPyy
    AUTHELIA_SESSION_SECRET: AgAJ7WimCJ3wOG9u5U2/9AoI22foQ01y5yS8yylwaMIH6C6iyJ3HoyiJkp/PyWQDBXoIXoN+ALL+Y/dz/xkDAMwvC90THFAXKuXpf64YTQY8OeUOXOtWc6av14bzM41jbgHtcwuR1IqIilPRoffbWc8W92yd616SHpsKwefQSHA96YLxmWqA1DR7y9CiQ5nhgp6rslyjr1IVyjoyNSpNMW/oUOG21tySJkhkJRAQreT15AhjiVzaeBqMR/Yo4wFBzN8sDSLpL7D7SP9zv0kMDJ6NFhfKri9FPcHqLnmHMvbrNY7o27NF2EJKuUT7WbY9qAHTU4RNPYQXbosoR1nPK2LIf7AZIJLaNLqO1mBiEVljhUXmgCXeeZYeNjjWR9OT+xQ0csoXTB1J8knrUuux/rx2ZQeywP1kyJJRw9hZlKWETx24TyUfvXBc+CSknUeelqL6zG9DT/kzUwUgllcsVSOGWXmDFdcSIrpYpwnmlDfoNSNnAdA5/pq1F76z7sriBLpyrm4EmWaRWPre8B1OERQNx/I2YLml6cFxgHQLgC3ufOQmiR6pHkLk5wdLSmkn0ezcB9/MW7IJWjWZMPCHNZkk4wHQqoqTNfEzt8iSHffhp4mNocpeLXUFGoivWjy9+fONINuYN/LhfodHNK5yHrjoSlowAkaAv8lDC/Jak22V6D1gkHpUfX3MsweibTYMwImXbeB+0Zc6KeHHJy6mDaCcilIYxxuUlJ8SmUr8QUQPOQ==
  template:
    metadata:
      creationTimestamp: null
      name: authelia
      namespace: default
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia
  namespace: default
  labels:
    name: authelia
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/apps/kubernetes/authelia
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: default
spec:
  selector:
    matchLabels:
      name: authelia
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia
  namespace: default
data:
  configuration.yml: |
    port: 80
    logs_level: info
    totp:
      issuer: authelia.kiski.co
    authentication_backend:
      file:
        path: /data/users.yml
    session:
      domain: kiski.co
      expiriation: 604800
      inactivity: 300
    access_control:
      default_policy: two_factor
    storage:
      local:
        path: /data/db.sqlite3
    duo_api:
      hostname: api-fb01a930.duosecurity.com
      integration_key: DIDV2QZN9XI2TSRGELMF
    notifier:
      smtp:
        host: smtp.gmail.com
        port: 587
        sender: jyundt@gmail.com
        username: jyundt@gmail.com
        disable_require_tls: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  serviceName: "authelia"
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - image: authelia/authelia:4.4.0
        imagePullPolicy: Always
        name: authelia
        ports:
        - containerPort: 80
        volumeMounts:
        - name: authelia-config
          mountPath: /etc/authelia
        - name: authelia-data
          mountPath: /data
        env:
        - name: AUTHELIA_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia
              key: AUTHELIA_JWT_SECRET
        - name: AUTHELIA_SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia
              key: AUTHELIA_SESSION_SECRET
        - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authelia
              key: AUTHELIA_NOTIFIER_SMTP_PASSWORD
        - name: AUTHELIA_DUO_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authelia
              key: AUTHELIA_DUO_API_SECRET_KEY
      volumes:
      - name: authelia-config
        configMap:
          name: authelia
      - name: authelia-data
        persistentVolumeClaim:
          claimName: authelia
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: authelia
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: authelia
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - host: authelia.kiski.co
    http:
      paths:
      - backend:
          serviceName: authelia
          servicePort: 80
  tls:
  - hosts:
    - authelia.kiski.co
    secretName: kiskico-wildcard
