---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia
  namespace: default
spec:
  encryptedData:
    AUTHELIA_DUO_API_SECRET_KEY: AgAkXHcpK4qSDVwVqYJUBEO+2ksdVTz2ozY59+0NY8D/1kOPAsQXJsihGp2IHAIxZMEntAP5Q7/gLw/7Vq64sHf0NEDhrH4ff2zM4keaCRsCPm9CPctBBo8u90FqKrqxfptHp2WdAYP1z5XkLMy7b59QdcjO2tjmG8/c3p/FF2d7x1fBLfBS/jYqCj9aIEKBSqW8a+MYAU0u9RDZ1kehtSiaBViey/pdJJ8WURONOLeT2CVpW2fjM3p1DIKAhhH1M6btf/jDSg11X3XdA7Tj9Nf+b1E40ri0FfCRvdy4etXPZAYHyVrPgh7qvi6cHRqMYjrzHp/mVsCKYFvYnzLyByxJcqM1Ws8oUgalrle2RAr+1IG0Zo6jZUOxhb+ZPCi9RGAj5s79fGLA5WYXeXkCNmZHlb0zeuFyJ8m7BCh3PKlFpq819ejVGcv+0epeHRWGTLanXjrYw6iK81sBMu2d4dgE3mfdoL0P7yW76wVvK7fAinZE06ylMNKMu9Uc8bBvB2mtGZdXvM+rAOOmNFHmKba5W/OIb/e8avzgURDFxInj8hZ+zYePGv5I/3tATJNtWjrWAvmk3r6Xql5k4zdf9YHZVPYjcMfxIVNvmIHoiSCKwYaBLwMiLZkjUN9IcWA8mL3VqlQf5yW1X6HaE4RidPnLjqOm8SiUx4g8ihR9ECYtAh9qHFckWXqyLIqB5ktqcKSh+4XuFwMajf2fe/aTqlsO5OzJj0pa8nOLQmEhDB1PhjobkvuGFqJK
    AUTHELIA_JWT_SECRET: AgB2Iu+evBDXqaMpJiHx3b1SmvzXth/4jfNuololHzyFUQD9I3Ip3njQYQzLmLaR1u5ModMEAgR6anxblqd2zfCsmaWkdJbVZyBW449dWZET0gY7F+g1IPkoSIhKon0kdI6q8LkDgyYuLQ2QGOkarsXXTgwp8xJ+odgmsXAjSyfuPIOeLxROTTvv875UwdYEyXP63wAHv5T+isV7Buvb44xg3OJMnoGMEitUcdpTwbhcBTVKPYBOve44w6JFNGBt0ZTOsyOVp4gMMq0afAdZtPXU+qX7XaAQPePo0I8NdNU7H2kWIKDIQ6TBotWLM0PsQEXTZiZSB6BU8AOBuhpREYQg5tnVzvzJsr7rjNJUWVe2YG4gvrFnl4pJ1NF0bip0xFUIv++ATgPjFAVVhSbVEms2hlsb+xngqc0gVqZ8kJcS3Cc3d0bu77L+Adf3itGv+V9U2VOOloggoa2lN2DGEBNklXSKrn45XBv/zlB8j5XF1nGpQj55tzakJgsiy0F38/2roJuwIh9vgO/eGn6k7QMwWIx2NbO5tuxqrmk03j8pSxaE5svg81AMhOhTiNGbD3jknrufLzGtj0vFAqwS7KlnWaAamcqRUZTPCVoZVuM8dPTzq+Mmx1zVv2jezu4Li07N1DETMP/bbAikno/lCCAbrgtBKL5/sJheUIIt2m3VIjN4gSPP7BPs+WDGk2YwfBVJvbu2Am5gEyhH2YkzmYpLE5Ptg1LW6450HtXAFwk6
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: AgC6Jpxf8xKkYOdGDCAd+ngbESXu/L3+963KlLhAZF0Q6MOdSCZAZlM27gKR+pLKd+/xQSczaaTQCEd8+uF7bNp076haRO2uqEvvoEPje4NUVtJwIZUcdL42P/AwfM3jublhY35VkKvE+LuY22QsDaFKIPgqgVNncNaRiO0+wjUr7tZ4JsyB+M+zp0FtHl2i/VwjnOGp80HXDGBnDlW29dAQvYPbfghJmcs64lECa4TjLOD0hmLl5oD0r5mCf9CXjgqjRh8Fg9nIjtim3zwbc2bCrYVc46pE2i3qr4P1UPqJ/A6Y5CE0yPejzW4FYOxO60T76zw8kPcbY2bPIUxeO5EUrHmTWg0TGTpsy2fD3O2y/SCzVHKP379Q9SfEBDwY3EWGqNPIysJvNoZFwKFtoRx4os74cbzvCOu4AaY90AxzVfI6VQwxy1KpDDw1p0QXBoRJG+fs5poYfS5tns+8i8HLksXxRIQBQUZF5GitZduL9NhZCS3tqb1ilAv2TmvzvMnoIJ57tv95Ba7LdC2882aRDOBJgypq8C26TQCleuABwJLGGoc3Q4UZR4o/kJQlkWINi2Tz+DF2P+mxf7yRE5FSsL86Gbwz3b1JRAOI6oU4OEGkYmhbqBlBb0PLe00s4krE2plTV8W5IRGBnFPJ64lDMCQKWN6b8OTlGTlU+K1MVmCH6wx1KB2mdAUC0g52ymWwlegbF2jANON1SR754LTi
    AUTHELIA_SESSION_REDIS_PASSWORD: AgAMNlf2AJ8HVAAO2TLYu/xHFepHPvUC4oZl2Us+4Us9j/G5fJ1Do67XSFUV9DFRuHe2llpk7AJnZomLA9QefVIsBXQWQQEaxFb3dKGtm7cq856KTLkrQmj5ChN44HHrKURIs6zJqdeiSmFtcai/TpSe+mg0wxKhgLYGBqmjxvzWTV3reNfviMebnwPw2a/rZactvfVZgz/6g8qIZQm2di4prwU7gNBy8eN3pKUopX69RTcMGukoUgKF0YY43RNEitBR8rds8leRAeHHMVhsWTDbPQdK+XlEs+TH+yK6wBPSyWo9ZgQkMVsgJnJiQUBIIAJZgG/Dq79xsaWDWSBXWhbEOqBz9ThLR/j+9tgIqB6rD9om6iCBjc1b/J39cqTo35wn0ZluGwtdQD58Y1LvoHqnD+u+wmL9dEJkc4dsRG0ebgJIZv3YaMbdqyaYnuIjgvHofnLHCWWT3y5V9d0W3RFn/NZr0KJE6HXkumdX5OGUSaNCj8gJyFNzSgINEAR1K366KtLSlqlVhXinbvVM1SU703c5Deuc2MnIKtw9oZ2JFy91cTQZ3JyaHO5gEjqCr1MqeaIhHUttTb7/sFX/mDdjOBGXULQCReZpq/E+yl4yHtCkaU23euIVRbTkA2if7AfrVJ7ys2MacBLuqa7zO38A/6XBWBGz1AO8J6zdXMS5rO2LMIB5JKYzG87TC4Pf48rsqLovEA7AHIGphsxRixp3aA1+fgKHDXud1VcppLSjPg==
    AUTHELIA_SESSION_SECRET: AgA+QJSuqBF4yTsh43ZvcUkl85yGi7N7UKzmzhYlW1vK9oyh9/2oZDw05RBxGVdSmBj+TTCg0jewpkH16IZEO1cvTm+Hk5biCziGwVAH3hreIC/FsNUi2dxLI1cSTh6NePIWQ6dkQj8Dajtbl5n0RgPUpSvSHbvkCIjqiAZ7My/PH1CLucSd/Cu1pe4BfRpYGtB91E2ScFF4fWFIv3glp69J3/ShPiCX7GfnJt8bB1WQtWSx5i7YHrYPLOijuOFmknmUfZ2evrZC6MNmBk65tKkkxQKiKhEpnzYhPzlZDG/afYB16369yO37aMbYmdIJBW6Zo+wyMEd5uYjUxvXSy1iKWOMHrpL6J4GczdvypmUOBCnhF3FWtp6dqUOaCQbYDSNhat2ljf4Som9Tp7B5EOPi+QzoO61Wb+7MmkXiR/W+jcZ8OlCHM4RqsPFRLtfolretAB3MplDbjTN9B9sQY+gLRC0yhy6PD66A9OqbyGmiaPmY6Sy5y1FLKHX2mfoXbh9uLs+xMP8F3g7LNziAKNoBbj8lY7ov6eC3ICwo+Bb7lA+qZpgTGjVMoqN22txHgO7Dx7rfvz2T4z5dDW88QgOPHA4bx+IbhVHS2e0asMuKnQ9vpLxCl065/qeOxN7iNnhcTnkcgKnckWlttjPU5WcIm0AV2W6WZUU/ykUfdua6EWkEFrj4pUJ3Bsepi/mHj0tOlQMoplyxFFNP+5bBBKv98O1X6spGlOcJHK+QzdJqeg==
  template:
    metadata:
      creationTimestamp: null
      name: authelia
      namespace: default
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 100Mi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia-secret-file-locations
  namespace: default
data:
    AUTHELIA_DUO_API_SECRET_KEY_FILE: /secrets/AUTHELIA_DUO_API_SECRET_KEY
    AUTHELIA_JWT_SECRET_FILE: /secrets/AUTHELIA_JWT_SECRET
    AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD
    AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /secrets/AUTHELIA_SESSION_REDIS_PASSWORD
    AUTHELIA_SESSION_SECRET_FILE: /secrets/AUTHELIA_SESSION_SECRET
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia
  namespace: default
data:
  configuration.yml: |
    host: 0.0.0.0
    port: 80
    log_level: debug
    totp:
      issuer: authelia.kiski.co
    authentication_backend:
      file:
        path: /data/users.yml
    session:
      domain: kiski.co
      expiration: 7d
      inactivity: 5m
      remember_me_duration: 1M
      redis:
        host: 127.0.0.1
        port: 6379
        database_index: 0
    access_control:
      default_policy: two_factor
    storage:
      local:
        path: /data/db.sqlite3
    duo_api:
      hostname: api-fb01a930.duosecurity.com
      integration_key: DIDV2QZN9XI2TSRGELMF
    notifier:
      smtp:
        host: smtp.gmail.com
        port: 587
        sender: jyundt@gmail.com
        username: jyundt@gmail.com
        disable_require_tls: false
    server:
      read_buffer_size: 16384
      write_buffer_size: 16384
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  serviceName: "authelia"
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - image: authelia/authelia:4.23.2
        imagePullPolicy: Always
        name: authelia
        ports:
        - containerPort: 80
        volumeMounts:
        - name: authelia-config
          mountPath: /config
        - name: authelia-data
          mountPath: /data
        - name: authelia-secrets
          mountPath: /secrets
          readOnly: true
        envFrom:
        - configMapRef:
            name: authelia-secret-file-locations
        livenessProbe:
          exec:
            command:
            - ls
            - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      - image: redis:5.0.9-alpine
        imagePullPolicy: Always
        name: authelia-redis
        command:
          - "/usr/local/bin/redis-server"
        args:
          - "--requirepass"
          - "$(AUTHELIA_SESSION_REDIS_PASSWORD)"
          - "--dir"
          - "/data"
          - "-- save"
          - "300"
          - "1"
        volumeMounts:
        - name: authelia-data
          mountPath: /data
        envFrom:
        - secretRef:
            name: authelia
        livenessProbe:
          exec:
            command:
            - ls
            - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: authelia-config
        configMap:
          name: authelia
      - name: authelia-data
        persistentVolumeClaim:
          claimName: authelia
      - name: authelia-secrets
        secret:
          secretName: authelia
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: authelia
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
  - host: authelia.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: authelia
            port:
              number: 80
  tls:
  - hosts:
    - authelia.kiski.co
    secretName: authelia-kiski-co-tls
