---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lldap
  namespace: default
spec:
  encryptedData:
    LLDAP_JWT_SECRET: AgAFvON7kqf3Dsss+J5Y5vxO3ItxFfi+KEa9fHPfKoEgqwjs/ULlFjmz+mEcsA+jCnotmEemxoBcvsbiHcg+SBM8s5mfrlXTY00xwe4/yxLRT48BAVG7DHlFraIKSxR4coBm64sebkDYFXRVfV9TU9jOaD4rpV34ImqAEl2f4pWteLQs9w0KQ0Hf4FdsgK5C/jJZpPxuMHXj7wEqMuJ18hjB+VVjRiZfAm+o6m7qFaXXR2A5DpOyuAx5YgGxc3hz5sTUsSx+99NWHSEqJBtEYgkjkXhPyAV4ECfxGprhl8VeNHszQ9DkcULRyJDv3wREytsRSilS5wpGPUf9wFI8SNRPTpCdYE+MvI3IrMiSKvv43N7zNO1dvHEonqt0o2ayBYiKWAsuufYSEi2XE6X+DZgO2dV92ExcB78M7oLjxoaqHMFsr6T9qLuwGqeYCXOScacw12DMUuM+BBioJyCoFFQnNbRwEQhbOIczyLN5qFtFxhHHl+ALclTuT92GWVowoZ5sBO20bLlufdWe3WWawW/lVRl8/2y14Vt6pWI4S6lAs8EgsWCuO9EjEs5GEW9x1nuHkqb1M/jVkJX/FMPIQjBZZS4uMDX05V0ooTHcDNzjgIG+WhK0pbuFVoPrWiDczU5jaZ6HY+L9gLcu4m/CC3nyePG8JpsYFdGx41vsEQWhvGxXL+lXqMUmKYP7v/5bcxq0GJNMs7cmp1/MUkWC8j1p0M7M8afnEDnDthvIGnSziA==
    LLDAP_LDAP_USER_PASS: AgA0PTqCzoqfG/g5woxMruMabWkOJ5oCCuWaYDVlf5yQwSD7XwvicGHMuxsyc6+waRfL30zBMruvk/kl52a1FIvx0qABlJp40/o7iVa6dUXReSlMamPxMzEDo07/MT2k25csuadj4ykmv8RoogntubCn6LfSO/Fy+kCvwArDEQkmsMIk1LUuHCFapDtb/kC7hyo48zUg/CjzlAmjZjxpnow3Mr6xJ22ZBvHOijw8UuhrWg3KEyR7xCBwDPdh6+ujzJPMYnIoGhONl0jSYnUlPOpELZyVxm9GVV2QU8D2DuwRaEQUSqXMazmsF4uEdXLFkzdxNVInvZaxsAy+5D9NrepwC0lUvQGN4S7yOX7g6VKMjuae3KhWeC2tAwt7CEC3djDhRc80c40lZMgAPRoleTGVQ6RL/ZJ+M4sxztUgRL/bY5FhlCju4fWNYStd98i8/VZCCsycVrywjAfScLqHlGlUPcnTnUGsCunL+8dlW8hjRLaR2uhDxlVlgC43bCcs1PZb2bV36uToTBN4TblmODhsaADXI5N5FM7TD/op+O7GcWirhsGf2rLHdREt86gMFsBr5a94n+ldrSC5jBhuHnkKKznjkkukvtvb2tTZwZ5tLDEJPLFw0+wSFi8QbNWg725m8OagMHsiKG+3rFJ16idDCLBwD2bV8wZyJPuv3sLAPN7fRONXEImCaOQjOMhkY7JXAF2APvZ0zhAEk1Rd0w==
    LLDAP_SMTP_OPTIONS__PASSWORD: AgAssAF02gdEBUsumhUnqJHooPsbr2Kyj0QB/SRRKWShCG+pHB4mQrHcWZicZYZfewOS6D9NoBqK90YxlnY6MYJU5Ffs6u6KfzlnGBAgQPAVoGNGehHdXSRyWotBb0fnYLBMYvQNKDD2mUrlRlLaa4ZYWlS3S47aI1BXABMnkwlEDVJfwayU9dlyKkHeFOJbWyPBT3RvMf1TbSWhoBNcyBZFtm6B5LAdchYVHtDkZtK0RmQMUoHgVBa/O1Rl8rwsNFAWkSRwfDY9B6Y14HHpCoBSlIL6pqE3sKwiAkLubo34F/G9PuKYnwjwip9ZJA3+3sJETheGhCBKQgD+6XH7/PSGa0gaWVQvxDqrgZN+s11n5qRQFxnCg7AXGFX4Gt8FkrUX9T6Gl41GWu4uXdBwwxVkEWXH1ry0PlFetnETLSQ4nMDqz4YIJrTfH03aa7FhwBgopfoiWAQcOz5Boa6DXXKCjmhjTgwccjBAMRDABsPa91/VsIt1qlL1+bKoiExTMnUDhxG4zRx4/7rgKdmNs0XUmir+UBwOmFsh6Na7tWsHdUmtf78hgv4QEMzFOqdh4mk2rKwN61c2xpHz3mY5qJE7YfMIEo/o1dUk/RvWqeOViLosaKRlOhNNJKzRWhhJGEU/eIYL+5OZqQFsJWbqZ7VwuJ4UOOj63aZ5IhnhRQVNEJ7OuhzSjQbLxvvLqi/ni8ZIU/EDAK+z0wxe4OeAutxT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: lldap
      namespace: default
    type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 100Mi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: lldap
  namespace: default
data:
  LLDAP_VERBOSE: 'false'
  LLDAP_LDAP_PORT: '3890'
  LLDAP_HTTP_PORT: '17170'
  LLDAP_HTTP_URL: https://ldap.kiski.co
  LLDAP_LDAP_BASE_DN: "dc=kiski,dc=co"
  LLDAP_LDAP_USER_DN: admin
  LLDAP_LDAP_USER_PASS_FILE: /secrets/LLDAP_LDAP_USER_PASS
  LLDAP_JWT_SECRET_FILE: /secrets/LLDAP_JWT_SECRET
  LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "false"
  LLDAP_SMTP_OPTIONS__SERVER: smtp.gmail.com
  LLDAP_SMTP_OPTIONS__PORT: '587'
  LLDAP_SMTP_OPTIONS__TLS_REQUIRED: 'true'
  LLDAP_SMTP_OPTIONS__USER: jyundt@gmail.com
  LLDAP_SMTP_OPTIONS__PASSWORD_FILE: /secrets/LLDAP_SMTP_OPTIONS_PASSWORD
  LLDAP_SMTP_OPTIONS__FROM: '<jyundt@gmail.com>'
  LLDAP_SMTP_OPTIONS__REPLY_TO: '<jyundt@gmail.com>'
  LLDAP_LDAPS_OPTIONS__ENABLED: 'false'
  LLDAP_LDAPS_OPTIONS__PORT: '6360'
  LLDAP_LDAPS_OPTIONS__CERT_FILE: /data/cert.pem
  LLDAP_LDAPS_OPTIONS__KEY_FILE: /data/key.pem
  UID: '1000'
  GID: '1000'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lldap
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  serviceName: "lldap"
  template:
    metadata:
      labels:
        app: lldap
    spec:
      enableServiceLinks: false
      containers:
      - image: nitnelave/lldap@sha256:d7c30805ceb7b5b1a773d55f14620a83b3996b51d29d620866f55266192bc671
        imagePullPolicy: Always
        name: lldap
        ports:
        - containerPort: 3890
        - containerPort: 17170
        - containerPort: 6360
        volumeMounts:
        - name: lldap-data
          mountPath: /data
        - name: lldap-secrets
          mountPath: /secrets
          readOnly: true
        envFrom:
        - configMapRef:
            name: lldap
        livenessProbe:
          exec:
            command:
            - ls
            - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: lldap-data
        persistentVolumeClaim:
          claimName: lldap
      - name: lldap-secrets
        secret:
          secretName: lldap
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: lldap
spec:
  selector:
    app: lldap
  ports:
  - name: authelia-ldap
    port: 389
    protocol: TCP
    targetPort: 3890
  - name: authelia-webui
    port: 17170
    protocol: TCP
    targetPort: 17170
  - name: authelia-ldaps
    port: 636
    protocol: TCP
    targetPort: 6360
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ldap
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ldap.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lldap
            port:
              number: 17170
  tls:
  - hosts:
    - ldap.kiski.co
    secretName: lldap-kiski-co-tls
