# slightly confusing, this (custom) storageclass will be our default longhorn
# storageclass. By default longhorn creates a storage class 'longhorn' with
# triple replication and no storage retention. This will only have double
# replication and will retain deleted PVs/PVCs.
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-default
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://authelia.kiski.co/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://authelia.kiski.co"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - host: longhorn.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
  tls:
  - hosts:
    - longhorn.kiski.co
    secretName: longhorn-kiski-co-tls

