apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-registry-creds
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgACKmD+HV+1CCBaK9DkkQn2UV5VoGud5Jf2I6uEF7hmRi82269JbCCI86+OQC1R6QJ1CxjtpszclwBqyYLVnIuvloLngGFLuLYiM97AsDwA+Uac5zxNnl3JCQf4qIqQJqAS9i331EulbAv5QgFLVNkoUJf69M9PMrlMbGF5rvIeC/6aiEsNBkRjpd0389K93uOUvmDH4ZuNSBqQtjfvbBRNzw37yiteqGpH6W5yOXaNilVjzdWbOoRdiWyJfmJsqBN3bBSqA4TX4e7ofTzjtKxBMPErthykV3Xc2NvCqyPgWpQVd0VIJlUuwkJRxJUsOPvAFiTShnzJOyH8roQ2Je20eyM1Y+CWOwDzHZldhC7cpwtRXLQW5QQmBo7Gx4sH7A/gxfNA22K7H1dQ3wmUMx6O1MFrprHFGdUSYRVskNNSHB80PblZENQQTJN9OOc+MRsQAncGpFacIK9XOwXA5R9lfxXL93hH3W4V1RRItgdWHV8OESyPZMikt9goTybB0CrqwZoozZYuWYNAVw2OGPOhyl5HGgd2NXkRtqt/PpLMtESsEPdO1OPPV734/zS4DZySJFARplRgPzQqaapoPIBTJyp5iwrQ1qCY+wITMaAxgjytdkAYJqydMHYrriXsuH3YufRaBlmX1HCG67QWIi9aKU5q1SJwfLRHjenbDsSlZzg2yR58RGSFpIBHrvHzc27YLUB5cm4g3o3ASD1MNCaP9mvUV5V1ejiuyAsUGHuCR49C8P4vfPk3B421n5mtoa5+aSh7b3RQHk/xXqLIAEBiVpBYpgLGIOHOmvS1MFsWiEgg6HRvtddRyqdNFO2Vu+nrqXwECvWPvbOcs8dz4l2KA8DVdirq/CSC53zpYTsV3XMqEGs8tHbjUfahMqnoM4NLkSiE9bFTaHhR1xq5W00tNtoX/kpugLN52r9ryp+GDrF4pT9kTdcvSivgRY8uRPeJ/Bp1e0oZ9XkbmFbjlbWf3ATXCmR3I4b4OGkqK42xIc2ImaXDTFQdYZZT0KRbYXlbJYOqBc9y53qnaSKhAFimirBY5gYwMnA6fraeC21lhWA9bPADjwszuLL2XLYbLvNHqMkfbdZdIzBzt6070v/9Bp9kApmUbS5PS7CNcZbl6f6rcrYJR2tinqh8f/vpv2HyUylu6MADUKG6mcy343F7jeGr
  template:
    metadata:
      creationTimestamp: null
      name: docker-registry-creds
      namespace: default
    type: kubernetes.io/dockerconfigjson

