---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia
  namespace: default
spec:
  encryptedData:
    AUTHELIA_DUO_API_SECRET_KEY: AgA6unvK2Nas00ttlTWbjLBvu1l1Puy2mtByuOD6q67S1zINrjqsCEgagihyxu8PfuY8Qh3xm1qsNzTnpTfjQJ/E83HdDJlz6N2vpY3ozHwA9TWz1jaIWiM/5xhzbX1kiEOF37le7G3ViaTu2VUB0XvYi0l0yuehVs0JY8XoEwJZpzg3zsdCrbyKdHqpl2Y7XONW+Rb6SV83RylaYnK7V4liaAeFZAfUi5ZkTHzXTWVEfFzdsOdfT9d5Fx9LaeOIv4J5XWupmtVuueiSuSFwag8aq3lxTCZLfJIucojj3LddzrgDwmwBtQq9MB3hoCNmir6+plpnCRpGLweCRI0GFRq+AI05LiaYtLJ8SuEwcuX95gSKLdABnF0FLm81tullG/jo9v+ecD6snC4bVNXj19DO8/jsRMsAKJ6PQ6bPTyl+fsUjX18mLqCCm8S/8aHwCVri9iqMiK3ZXHgceVN8+JwIjBT6ozZdsTuAVrb2jwTASs2kjQaewGkidD5MTlQwYckML2xfqqw8teOp1wxFVEH6T9U9ZdpKBuswFjmx+GTlwabe91J1p2z5LVnsCMi5o+jmYv0nii0due6BggwErMHNdkRmaCkwkSMx8Ck9ASAa6q598T0NqE3LEFPSuqLAW9hFJh/coh1kCb523zMlX8a6+zJbBpkMKDHsPE5Mep3fxdRDzNWxaSosNcOde3lwy5VLve2AnRRrxz4uAdDn/4Bhb4bVnlfJdCSQDmW59JIsTzCI8jIjHQ/m
    AUTHELIA_JWT_SECRET: AgBi1MET/OKYyatlqZpMvC6acLBBTXaVBmgGAlsiX7Zct3GsUnT4GWbaS275hjl15L5TfbtOAL7mIkW2mfO9dZg4MNpqpuDM84/Os6gI5q/wEnD3y3O9vp89Yn9KgtdEcw+IPKkH6MOc51WJdn2CtcP713AvWwtMHn+/4oq52jfD97lCWeXTvMIBnNUrCRB6MEE4ItXmT+ZgKyvqQ38aqyFDRmYJNwk5XIpGf8fwehx45wQ/kvDBUX7IJMBjWevL8G0o8hoCMUrcx/wA6b++tqxGw1pyMP8LUJc+8hOaX5mvMmO6c5m7GfJ7jKPIC03TCRnLAd3UkHiWJRqdK5SKQHebZ6K3BpBMfC/lgkqsllvHoyLeHAG8x7ZOo3I9IXb9w3iXh+aBzgqY89zkCZ5A3o9BIlsxY5QQr3yPOe6rwcvauwY457zKVRm2i+aLWxwA3VLzvnjyR6dIImV1CW53N5Jcjziuvn5TXF+fyRZimX3nJTkZVObjD+pTE2Hw25CU3/jz+RTuwVuRXDi7inXUyQ/hCACu6DwV8hJ/IrfrSAbtYBOQXeQTLOzG1i+Oad4O0eHpKtRwWgzro2RSa2cXv1aHUImZZF2z7hdvk9enQuAPSYmFj/dTTvFHV4OpOw4KrxLIxGpx9lT9R/lrQKop6rS1BDM8LRnCM/3tVKnYPk0hDF4un5Qcmuq/niQGm3VYG64EALz+e+bsX9QzdwOP9NP0JrAbTMRKsbifvCaHjHJL
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: AgAbvO0JfelSL/Kt+QK2fFPhJNakEQ5A7Y1vXRdMraaV0vXZ9pFC/ol9fIMyjLNk+RK/frfs3GJaAWrzAU5P0qIDE73FSR5HxCbAQr34Ezswah3Qf9w8AIGokrJK/UZH95rguSQataU6Np7rHbwudYUEkTIqNEG+cru+MozDq0CJmS4PFUDNdG+rCYcaWxBi8yBpIUNu99ufHuaSDsHZH4GNi7Nrn/H3iUqfIiTQjIPn9SowxIz70h6HFPlXgT+L47+X+fqt+ol0ev/buMx1vWYYojz5KX5JrhR02SH/EeiQGBK1c3nqMTPxHAOj00PjdnOeyp6D9KFLtS6znGDx9X+xBuiANQSAiJjXlfCBNorSnChWv/QT+IfXvF/5E3ufGDS5RQeX+1JCQH3XHf17qM3/1LrqDJsY5cm3P3nIybLqnBgeuAkspNVvEKtFWvfrdImB6t8s80i/lT/JES57MJCWZvEYbcALrtumEdp694HOu/tr6/yOsvbZIM5gU45vb+ejkOzGfrthNpyKql2LZdO0rZ6+mHVPlWInxQClBFT24a3MPblhMjwu0j6spCZRoYDTEiXjOGY7zWP9YpbaOcyaisD3NykhECe2PKzfQXlJNM3oNWFyvuN8Is9yxWgjQAHPp9O4Gy+oO8tyy4QhHm359MianMWtNgfNtXReF2gz5fv0q91g9dua4pLCMaeKHO9y+Lb4BSQUVpFtqmAVMTry
    AUTHELIA_SESSION_REDIS_PASSWORD: AgCpk6hN8zAx8w9XuR2L/pNdl/I6AEMFKx3p28Sy1m8UdTYop5y4iidsCClHIqrUIedsyNFI8jWFJhkmftcCIHoTs5o+99zzvH1Ik69djE9PRKwXk4xtWgQt2Chxs1rXLmD/kPSV4UnaOD0eCp/ueihX6O8OWT96ti9tw+3mjO9ARLMdmgHExbR0PzWhy0sjvOAzhcTypiL8jlC1OPn5aMG8Tv5+edAJpzpr/rv8lsgGOeVhgCK5UFqLZwG2cvxn4nTWYe0UnboyUIjiUih5NFLKFvzia6cg4/ApmeuUk3fndY2pdB3r8Go/uk9Mcd7BMsDwRpi2hahMlj9fno/W7osNAudCeFg9S9UzIbfYg5rY/cD6MYsHKBtz3DeLoH4getX2vt0VQkArD19kz4bTp7RBo5j3PQFWXKMjTXCPFCAoKVTQh+1uLjeVANFUqSxuh/iIqEkPIyiHwN+lK0+WXgYOsLfzCYKJtD9lD+4Az3+O33aEifhlwf7RoT0S0/Smtr8fElg8mknlFSsYjcmLkaGRMbElNG4brA3QRA22RPAnX7ExPAyggIaBV9bD0iT0iW8Ivur8wxfen8AQtHgSxXs2MzQLIY5ZencWGo0UN5R87qmRooPlyFoDbKHOYpFdiRnsZRw1g72wAuj+JozBfvPTVcqwuatTC9d7i7rbRuK/Uqk3JLr/oOg/ty8pwJn+WEsKnl37aSlPv2e38PrUNwWPX1Aa71n7jCWbdJzEMR0NHQ==
    AUTHELIA_SESSION_SECRET: AgCfZRakbpJMMTBKrA0Gs0LZ5rbG70cDo2ggmCWQssU7F0le2oTfR+jRriAwctqwpSkhJMZWie1OL8iOmJVzM8hRSGRJF+qCN1FMiBTu97OKT/w1Wg1WitUyJt9zFcdelQz75NucdRUlp0nPKVND/HFZGbMy7nia0i9eHOihZBo+iRWDY0/SpR02qZIygf+nabcMoI2YzN22AvfulO692KNkck4/dJ6sjEfHulNOzEFs+sqZqScD9zJvgsbFUW+cfzRppVWovAwRoJtvC+WWOi9mE1hqnu23KH3WlqAh8JvbgccAKuJgepMpqDfCdeAPFHrGuVY3jsMG0+JQbv7jmcCFVfX0qR7y/PkNl3kb/Q8vK+118AzQyBhDWXEI3jFnehb9e7n71uS07siCSkccz96zCjETIjAaQLB1MYdPcAFl8supTJyHF6jMWMnEDzQynMc4JixYH2hdp2GlKIPOd3TkouBi1TGyvjgqsGHjtVJEJjE+XWmNZTQNZ9IqRTVNG4N9pQZTA/V+3CWBTEKtOVn1Dg9okweAzq/DRdN/WmqX5LmmUpzeOuiqqOTcK9Au+M96Kz3DMOC0rAALzptf24spUXc//4LQAoOyQ4yFCQsXkVoKjp+dLPUvVQmL0EMD8f08x4+z1DdASyaAyC6BmrbAPujbNuI8FdLSr5LBgqsaL6EGIhnSztQFqdKk20gUKv6SZ3c2evRSQ7ZFV2lnzMZD5QjIxbIjwI4mQC7ZQ46NjQ==
    AUTHELIA_STORAGE_ENCRYPTION_KEY: AgAKw8h19g1hZs8kuV7eccZyMU3r217+tqv6ywRJNNkCPrIE3crPe+I5egp+wljkAMwrcsBXMwGpE0V/4Dd2Lx1ytapC7RljlTnRmr4WAxuzLrjZEgLgovTy69g2GK11Z4FAjxtDWpNKPsxHpz5H5Z57ki7YaP6v1P5Ks/ADn4jlGb3eBzeyMdDo2zZDF8UcQIui6U4tBEVXCnQ7SQt7jqa2pzwR8k+mzJXujsYS7mxIbYeFOSIsAH84ZHImLOu1CJoEmgCq9RffVWSm+GbnlXyqbZpUlkdx1iPCvnRZRNwwxLsjMioiJPxe6ZMzAnqa1yNBJ0ViF9pbf/eHQUJTTF+dvUIha42oJE2P3ZPRDJRSDcXpLwqjytIJHd9H0X0Aa/T0zhaFtKUWTFwit43rn+5czkpiIMyrlLDp5BszdxP6Euu6tZYmMOU+HPO9uPR/Aupi/VQW29SfHwnYOQbxJa7LncJYro4aUtvqdBr9yz8t0oOypRvsopKGXOphgz8BwWIMzda89JcuG+VBVMFHnmF+hmtuOWiDcgnhbDh5J3VJTY1Gpsln+NGPAAji3E/FksUlGeo5Dqqh1Tp3n7doAShm7iPupRJzYwTVDpI/GYD3svg0Ktt/qI9fJY9CUgcULXbGWCq2SR2IbkrKXbwTObUzbqGohxzeMBZvv5AyHlcAxWtWIVawA1qvDHZbimCswE4on8uwvuFKIYabwzAm1Lcqb64Hip3Whrwwl1EFHC6xpA==
  template:
    metadata:
      creationTimestamp: null
      name: authelia
      namespace: default
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 100Mi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia-secret-file-locations
  namespace: default
data:
    AUTHELIA_DUO_API_SECRET_KEY_FILE: /secrets/AUTHELIA_DUO_API_SECRET_KEY
    AUTHELIA_JWT_SECRET_FILE: /secrets/AUTHELIA_JWT_SECRET
    AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD
    AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /secrets/AUTHELIA_SESSION_REDIS_PASSWORD
    AUTHELIA_SESSION_SECRET_FILE: /secrets/AUTHELIA_SESSION_SECRET
    AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/LLDAP_LDAP_USER_PASS
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia
  namespace: default
data:
  configuration.yml: |
    log:
      level: debug
    totp:
      issuer: authelia.kiski.co
    authentication_backend:
      password_reset:
        disable: false
      refresh_interval: 1m
      ldap:
        implementation: custom
        url: ldap://lldap:389
        timeout: 5s
        start_tls: false
        base_dn: dc=kiski,dc=co
        username_attribute: uid
        additional_users_dn: ou=people
        users_filter: (&({username_attribute}={input})(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (member={dn})
        group_name_attribute: cn
        mail_attribute: mail
        display_name_attribute: displayName
        user: uid=admin,ou=people,dc=kiski,dc=co
    session:
      domain: kiski.co
      expiration: 7d
      inactivity: 5m
      remember_me_duration: 1M
      redis:
        host: 127.0.0.1
        port: 6379
        database_index: 0
    access_control:
      default_policy: deny
      rules:
      - domain: bitwarden.kiski.co
        resources:
        - '^/admin([/?].*)?$'
        subject:
          - 'group:admin'
        policy: two_factor
      - domain: longhorn.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
      - domain: frigate.kiski.co
        policy: two_factor
      - domain: zwave.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
      - domain: io.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
      - domain: io-bmc.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
      - domain: callisto.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
      - domain: callisto-bmc.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
      - domain: n.kiski.co
        policy: two_factor
      - domain: nitter.kiski.co
        policy: two_factor
      - domain: twitter.kiski.co
        policy: two_factor
      - domain: r.kiski.co
        policy: two_factor
      - domain: libreddit.kiski.co
        policy: two_factor
      - domain: reddit.kiski.co
        policy: two_factor
      - domain: tautulli.kiski.co
        policy: two_factor
        subject:
          - 'group:admin'
    storage:
      local:
        path: /data/db.sqlite3
    duo_api:
      hostname: api-fb01a930.duosecurity.com
      integration_key: DIDV2QZN9XI2TSRGELMF
    notifier:
      smtp:
        host: smtp.gmail.com
        port: 587
        sender: jyundt@gmail.com
        username: jyundt@gmail.com
        disable_require_tls: false
    server:
      read_buffer_size: 16384
      write_buffer_size: 16384
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  serviceName: "authelia"
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      containers:
      - image: authelia/authelia:4.37.4
        imagePullPolicy: Always
        name: authelia
        ports:
        - containerPort: 80
        volumeMounts:
        - name: authelia-config
          mountPath: /config
        - name: authelia-data
          mountPath: /data
        - name: authelia-secrets
          mountPath: /secrets
          readOnly: true
        envFrom:
        - configMapRef:
            name: authelia-secret-file-locations
        livenessProbe:
          exec:
            command:
            - ls
            - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      - image: redis:6.2.8-alpine
        imagePullPolicy: Always
        name: authelia-redis
        command:
          - "/usr/local/bin/redis-server"
        args:
          - "--requirepass"
          - "$(AUTHELIA_SESSION_REDIS_PASSWORD)"
          - "--dir"
          - "/data"
          - "-- save"
          - "300"
          - "1"
        volumeMounts:
        - name: authelia-data
          mountPath: /data
        envFrom:
        - secretRef:
            name: authelia
        livenessProbe:
          exec:
            command:
            - ls
            - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: authelia-config
        configMap:
          name: authelia
      - name: authelia-data
        persistentVolumeClaim:
          claimName: authelia
      - name: authelia-secrets
        projected:
          sources:
            - secret:
                name: authelia
            - secret:
                name: lldap

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: authelia
spec:
  selector:
    app: authelia
  ports:
  - name: authelia
    port: 9091
    protocol: TCP
    targetPort: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: authelia.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: authelia
            port:
              number: 9091
  tls:
  - hosts:
    - authelia.kiski.co
    secretName: authelia-kiski-co-tls
