apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  namespace: default
data:
  WEBSOCKET_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
  # /admin protected by separate auth
  DISABLE_ADMIN_TOKEN: "true"
  SHOW_PASSWORD_HINT: "false"
  DOMAIN: "https://bitwarden.kiski.co"
  SMTP_SSL: "true"
  TIME_ZONE: "UTC"
  TZ: "UTC"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitwarden
  namespace: default
  labels:
    app: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  serviceName: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: vaultwarden/server:1.30.5-alpine
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: mailgun-smtp-creds
              key: mailgun_host
              optional: false
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: mailgun-smtp-creds
              key: mailgun_tls_port
              optional: false
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: mailgun-smtp-creds
              key: mailgun_username
              optional: false
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: mailgun-smtp-creds
              key: mailgun_from_address
              optional: false
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mailgun-smtp-creds
              key: mailgun_password
              optional: false
        envFrom:
        - configMapRef:
            name: bitwarden
        volumeMounts:
        - mountPath: /data
          name: bitwarden
        livenessProbe:
          exec:
            command:
            - ls
            - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: bitwarden
        persistentVolumeClaim:
          claimName: bitwarden
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  namespace: default
  labels:
    app: bitwarden
spec:
  ports:
  - port: 80
    name: bitwarden
  selector:
    app: bitwarden
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/auth-url: "https://authelia.kiski.co/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://authelia.kiski.co"
    kubernetes.io/ingress.class: "nginx"
  name: bitwarden-admin
  namespace: default
spec:
  rules:
  - host: bitwarden.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/admin"
        backend:
          service:
            name: bitwarden
            port:
              number: 80
  tls:
  - hosts:
    - bitwarden.kiski.co
    secretName: bitwarden-kiski-co-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 512m
    kubernetes.io/ingress.class: "nginx"
  name: bitwarden
  namespace: default
spec:
  rules:
  - host: bitwarden.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bitwarden
            port:
              number: 80
  tls:
  - hosts:
    - bitwarden.kiski.co
    secretName: bitwarden-kiski-co-tls
