apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: croc
  name: croc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: croc
  template:
    metadata:
      labels:
        app: croc
    spec:
      containers:
      # No version numbers for the croc container, this is 8.6.8
      - image: schollz/croc:sha-cdabf62
        imagePullPolicy: Always
        name: croc
        ports:
        - containerPort: 9009
        - containerPort: 9010
        - containerPort: 9011
        - containerPort: 9012
        - containerPort: 9013
---
apiVersion: v1
kind: Service
metadata:
  name: croc
  namespace: default
  labels:
    app: croc
spec:
  selector:
    app: croc
  ports:
  - name: croc
    protocol: TCP
    targetPort: 9009
    port: 9009
  - name: croc-relay1
    protocol: TCP
    targetPort: 9010
    port: 9010
  - name: croc-relay2
    protocol: TCP
    targetPort: 9011
    port: 9011
  - name: croc-relay3
    protocol: TCP
    targetPort: 9012
    port: 9012
  - name: croc-relay4
    protocol: TCP
    targetPort: 9013
    port: 9013
