apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio
  namespace: default
  labels:
    name: factorio
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/apps/kubernetes/factorio/factorio
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio
  namespace: default
spec:
  selector:
    matchLabels:
      name: factorio
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  serviceName: "factorio"
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - image: factoriotools/factorio:1.0.0
        imagePullPolicy: Always
        name: factorio
        ports:
        - containerPort: 34197
          name: factorio
       # Can't do rcon because LBs don't support mixing protos
       #- containerPort: 27015
       #  name: factorio-rcon
        volumeMounts:
        - name: factorio
          mountPath: /factorio
      volumes:
      - name: factorio
        persistentVolumeClaim:
          claimName: factorio
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: factorio
spec:
  selector:
    app: factorio
  type: LoadBalancer
  loadBalancerIP: 192.168.67.203
  externalTrafficPolicy: Local
  ports:
  - name: factorio
    port: 34197
    protocol: UDP
    targetPort: 34197
 # Can't do rcon because LBs don't support mixing protos
 #- name: factorio-rcon
 #  port: 27015
 #  protocol: TCP
 #  targetPort: 27015
