---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-config
  namespace: default
  labels:
    name: filebrowser-config
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/apps/kubernetes/filebrowser
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: default
spec:
  selector:
    matchLabels:
      name: filebrowser-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-docs
  namespace: default
  labels:
    name: filebrowser-docs
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/docs
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-docs
  namespace: default
spec:
  selector:
    matchLabels:
      name: filebrowser-docs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filebrowser
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  serviceName: "filebrowser"
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - image: filebrowser/filebrowser:v2.7.0
        imagePullPolicy: Always
        name: filebrowser
        ports:
        - containerPort: 80
        volumeMounts:
        - name: filebrowser-config
          mountPath: /database.db
          subPath: database.db
        - name: filebrowser-config
          mountPath: /.filebrowser.json
          subPath: .filebrowser.json
        - name: filebrowser-docs
          mountPath: /srv/docs
        env:
        - name: TZ
          value: 'America/New_York'
      volumes:
      - name: filebrowser-config
        persistentVolumeClaim:
          claimName: filebrowser-config
      - name: filebrowser-docs
        persistentVolumeClaim:
          claimName: filebrowser-docs
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
  - name: filebrowser
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://authelia.kiski.co/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://authelia.kiski.co"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - host: files.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: filebrowser
            port:
              number: 80
  tls:
  - hosts:
    - files.kiski.co
    secretName: kiskico-wildcard
