---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: firefly
  namespace: default
spec:
  encryptedData:
    APP_KEY: AgBSZjpWXPwQtRCRpUOeNodSaDZSXNUmIwHHS4P0fyOJQzbL11yjbPvIRZnIkrUzvD3hoZRkCLGLPOOUkiP8czo2QOiP/8YIZDyNinr3NSJdJY72dKPFlb1zAed9xBFWicd9ZPKm71e2FDV2O4VR7zslA34085ByV8f0eakAxr2Q1gOnUr/9eNQbZ8a+TTR3K18MxbLOZeJhJSSDOxz2WuV005JPbfb9rsjgZuXvaYhinx7F2RIB8qUgAqu9jr7xtyEtF5Uj8sGgyiySvnkeaRUyolAded1UfB3vr01/U5lGmU6AMLBDK9t47hB9vS/9w1um4H85VyeHXiX0rpDNjWao7kSyqxnJCohWQpull18lDGUthMpN3PeEiALGcILaDipoi6R47X4ZSYHx9uc0JS59Q98rJVOsI2/vf+lyxc7TBUJqchAiF880x3Z3I/mOzzL+UDiIaiHhWGCJdn42U6JLk3+RvkfZMbC3oakaNnk9PUkPiHQFu+IDWTcqb/g2Jn+x2f4ysjHEeONQ/HkLtJ9D3WIDaFmwuS3zn5B1A9yyCfn9B06EmGXAfP8ki/g5IPfo7QqbRq8sKhrKdT6Ilu/1AgDe9QVRuY1YSPhxAsAqDQK3lDutFMVQ/hhArPLJ7eG0gXRsJcxcx1f1U5UaZ+VjYDMMD/C1z0X4gMM5/5RXg9HTzxwArxKb8ZQ9wJrUwBdRNNc6l74A0npVG9NcCP2EAQVGYskI0D/Bcv0VF8/+sQ==
    DB_PASSWORD: AgCcC/HiMBuMXaGIwRb1tGZGuLiXlLTQ25q1iypa1BIKKFPpL5rbV6fl/vA6X4eEUQZEvywgTVEy7u1LwbN1Mob/7NRzsRcF2jNHu8or9YBsr/xJT0KMCOPxzOZjgh7V+nIiIdRdWgw/RlU2CH7WdsBY+0jVtuQSm/NoLE0+fDoxyu/CkNrFUzRfUcSyJ7RBGWn1+4mKA7nhH6G+n0AiLkZEydkfxQhBG4K1LQNdXH6mDnid6NaLntebIPnYyPC5iRNMCie4aHLPgnv1xvU59f3zO6VjtNE5J1RE1aqYl+lCf/EHmbvnWNUGMdgmqHuN1uD6mslB7Mp4yYOMQfVamtObeLYyGal/N/frbaZASETYdxSXYexsqS+GwP7rMiIvhayh2pjcoxPi7zrIdtwGAewqigxhg2pnbG79/ii1pPzeaiKNuye4W8amoEhkjLbv8KfRxYjRpCNfmTLjlxVajzGqGW8iSsu6huI0E6vb7px9iDi0ENnpUIXYVGosIT49B7YdlzEN5I1JZ+OfwO/MlJwthWtWTPeaVOsAZObX1e2hx8Ys1bTOnheV0YzUXVr9fnNP2/R7tZgO1J0FlOJoKaw/d4l03zGRpsxZKGJmtYJK1jAze77klLH8W+frVRc41rZI94Khg+Wc28QA/xvjtZGg+dEb7tDrH9T9tpFVMU8boat1zHzdlN/ESKYnhyQBFgfCzZ5c4xpI
    MAIL_PASSWORD: AgBfPD6KCMPaFj5pmVbT//ZxAuxKBerCpAI0KfqEuzEgBsD5rUkRC30cmwXv3qosSSyKSjS8A5tCx/EkRtLJZgm8N8aJ/YkxrJQB3r4+0Xc2jRrM13BxTn49Kf7JVpRFsIRlo8n4C2rusJ+nt8jV7WJQGpg5HP+R0axSglrKswox403atuji2bF9d0sgcV4lho5R8VARnX+eaYYJ4L8cXGyUWeOLzRG3eVoSD1365VHnsc6RotFgfComiN//lEpUsqIPWlSF1CCpXbtI3D2dhQk2qiRZukYI9MkEdHz7zBR5+RphWNEEQe3xQ7Xq+MBO1x7vhQTeelJvOgCQIke/or60ytyne1RhMvKMP5DRCGilwMv43N66iUIa6lEIc1pESE15XUVMpPM2RaXG2qDiExN5bhyYIkGP6Hh5OlNUARjE+o0XatEOakqwkAW7S2YsWTZE71f6xbCsC3fSqfSiYX9dlfzl44/kDL3NkWxk4L3F/Bitd30U9eO9HiQLgGG4srJtALVu2znM82ErCHKktvge5PAX29jJhC/Z6zHgzwIeRzPoYwF/f7eBVjD7h9Hw4ONLPsVZWhxtP1LMiBJ4yjM5XLdd5G1cER/7AYdQA2bjjb+spH10COfy6wP0wDrPD71M4fP7qg+tn8S2ttgnck/WqRyOMOvnqJYvCSQoQFJFvOxnY24VBLVosi4a8TOKETojqFUyXNQ4+VyN8Sg6ffMZ
    MAPBOX_API_KEY: AgCz6D+fm5eWp8FYAwDv8FVTrs6TOXMJZH86FNcD/iNWfAQZGbT46/reP7EZDursrrp/ksRpI03EhUnNefXGODlfUblF6Gz+dSo+yd+A2xGozvLhrWUzOAxE0W+qQYbe7c9/k3meuc96QUAzIt3Aw25QrYhYqsJDMnVPXiai+NMvYFY/lrt6QfXgNvg6Vbokv9ZRxEjF2R3kjFEXh9wmsz/um2xB2PdF8ewtv3GX/fIjTOwWO13QVq1Y/aaWRMJQpGiAqmvlXHOQ5yDOf+msjgsbYdDOGgDYgX9vW+BsZa3TFp4v4371mo2uHBw+8t52R6z4Tp9Tf/m8gbYSLH3Ix4mM5jp6EmkeLg16jc6OH6WV2MNdh31Wai9A2YeXmL23DFb8CfGKs+I2jIwB5v5PLVy0D7kDujUTWTaP6fdSV9rNDYHVtn7THDg5wehVsjckX9tE0LVeYSE/RVmZk9WuNU5dhFkLXYCUdTJ7Qs3ORwX3/VElJk0+wpHAFsYekqz12ppa1LuPNf6wYCoIVYoFhVHsG18GF2HDRdOsQzNMVVKxMT9qIwK3VipMZkyqnA5rr+YDbViZbtQuW2x90elMhhoXOCNFiatQSkpt4Y/HCVavfCvjfLzctXuRa4TTh6fCP/O87a4lTKRg4ZxbHe2CeWcyFCzHL6LCKj3qarwM/oo9PSpisq3ziNl9hI3UMrND1r7g3XAozQMu4NlJhI5NiM4Ll7JNjMah+pVc+tUG3r9t/o1d78+S8EP0mD8xPDIislSeV+fLIEtBMAXN6OmkFBY300SLMcTmdIo/pumKgKfLvtNhGOlm9110
    POSTGRES_PASSWORD: AgBkewKUPT+hMlQT7ISsyiRSUp+mpIUhtMN3AwRn7nOo1NVfirkTvM702ZNGULsjdk3sECtxefjvCPtqsEBCy1mqOBtP+H7WJhgXdjp4k4r0vc0AvXe4+iAdPPV0xc70WiFstt1XSn1gL+jYVXnVr5pXKPiyX8H+1ec1azOeuSwwycZtS7LWGf6qZVI3Y6Yr8JI/ppRVOeEB5q4ScklQ8JT9//nbxP5hvsrHCMr85gxufsPCxKfYkeeLKitOF2p0X0Ovytj8uzRCZY5EwfLYoP+QgacfZ2Dtj90ja6EAEYghF9lkxJ3Tir5HWu5obCflujHNfFBcK7RRmJFCkdJ3ZEkLVPEvwkD4xdZHBYCkx9VvTzMBN8+UZc1BzwHfbhpbZ8GsIjF6PaSqWdF6iFlpHV2k1+8bZOfMAPK5GkNqzs2hETD9rGJFSs6NsThBXULfGw9PYboE4O1v8EaCqH+HZLGEu9+NbyAsrV1SuZXp+hcCf4HY1prPA46WqkgeMkY4EsVsLpvat3qrBNbmsddFR+nahD8A7SvP1J6AssLKg/a9+7IVY/p5qvIq7uGJy8LccSzkvDrHGqKMMlEXgVOAEmIcglxUG9sfIuvdSXOQHt8ByEEph4Wdy4BqLEbuHoSefqXOBA1vtHdKcws6SjVKC4+Cuu6f+tMszTw9oY+rc3L+THqOXJRxHQbTRyDSfBHVF7WUx7Y7m/lP
  template:
    metadata:
      creationTimestamp: null
      name: firefly
      namespace: default
    type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: firefly
  namespace: default
data:
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_FROM: jyundt@gmail.com
  MAIL_USERNAME: jyundt@gmail.com
  MAIL_ENCRYPTION: tls
  DB_HOST: localhost
  DB_PORT: "5432"
  DB_CONNECTION: pgsql
  DB_DATABASE: firefly
  DB_USERNAME: firefly
  POSTGRES_PORT: "5432"
  POSTGRES_USER: firefly
  POSTGRES_DB: firefly
  POSTGRES_DATABASE: firefly
  PGDATA: /var/lib/postgresql/data/pgdata
  TRUSTED_PROXIES: "**"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: firefly
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  serviceName: "firefly"
  template:
    metadata:
      labels:
        app: firefly
    spec:
      containers:
      - image: jc5x/firefly-iii:version-5.5.1
        imagePullPolicy: Always
        name: firefly
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: firefly
        - secretRef:
            name: firefly
        volumeMounts:
        - name: firefly
          mountPath: /var/www/html/storage/upload
          subPath: upload
      - image: postgres:12.5-alpine
        imagePullPolicy: Always
        name: firefly-postgres
        volumeMounts:
        - name: firefly
          mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: firefly
        - secretRef:
            name: firefly
        livenessProbe:
          exec:
            command:
            - ls
            - /var/lib/postgresql/data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: firefly
        persistentVolumeClaim:
          claimName: firefly
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: firefly
spec:
  selector:
    app: firefly
  ports:
  - name: firefly
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/auth-url: "https://authelia.kiski.co/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://authelia.kiski.co"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
  - host: firefly.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: firefly
            port:
              number: 8080
  tls:
  - hosts:
    - firefly.kiski.co
    secretName: firefly-kiski-co-tls
