# I gave up on trying to prevent email name leakage, mountPath doesn't support
# variable expansion. #dealwithit
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gmvault
  namespace: default
spec:
  encryptedData:
    emily-packet-passwd: AgA3fUdhsRbBca+Dg5Fdx/xgxxkVKpwnbqxAQ4XdSPiVHGImQpcfscfIdPGltNQrTSs/j6+JBAc6rVs2ynFjbg281xp4dqcwCAhJFK5vPjUDAZRQS013bcpMK/iQwFxsA+QCs9cUL7ZjY7nNpdGshJyhO3wQ0PrBcDlZTN+GbcPGcBS3JdbuM+uR4jEp6fFCp8zG/cZ01XvXfCWwU/mQ7w7AQuEZFuws3XAUQQ2426GsBRlMSNqY3te5JgXdWGcpjsf2qZasrOvWD0a8dOtyDZnej7qhRD7l0QTt1sJ+IrRROO7rBZ8oGD+69J//opyLBIhqp9wCV8H7URT6kADizj2Wg/frGA8uRCEPKP/kJnVaOOai559pS+Q008z1sxjB97TURVwnOvvl6axU83GKRGv2pAr31nmQV0UO+ECmWqYpRVaa8AdpCQNUKqkSha51UAewwnljt+6ehouJ0IEBjo67eD6cESmo6bHRLXLNErWkcPjt9aBXC1VS7cBPrm48MLai3dYwTP2MJV4h3ftqMSWe7i/5m5riVwcmNVEw/S281CEn3vfCkHReZ4xfOmdqjd5i+DVkiwYHtMxCh31wR0rH1V8dEhu19mK7q66pkz9UioTPmsRep4lIJx762idXRApP6iF68IjHyZJG9yUEyqvkzVOem43ZJAa1iWxD/J3XmvNV9RQ1unwDQTgzSVYVu5JTXkQTAyjtT+0kZhKqMr6Z
    emily-wolfe-gmail-passwd: AgA8Z+Ftcsy2Dqi1qT+xnuWXzdl2GI0hJo9RhUoOdnCKRccY/jutWIa7g2ZVMdm39RB+hFSM1W+OV0mViGvhtIsDmDQGL6n3TYBG7JAdl46fvAzfJcO5QWvTPYuNhxxfK7ZA+0t3hoWJxDRA/L1FjZuEsRPdwueArZU6hC/VoVZdlY4gMlOCOOfGlRt4FhOFL6JJWmaa+1g+ouNE1Vc61VIrwrb2BxcsQ4EB0ZEvEWGXwoCNJakbMV28rzgEO2zx9HSW41UotUrO96nldDeImvFqgoHTErfZrIDRGH0H1yi5v6qkR4fUI08hZPCZUaTY2fi3qxNCoy4oAcMX4MKMLsutpPxZ7SsrTF0e1o4gkVyx1VwPemhEimxj7BqCEkFWrv1kwOR8/TWGKrhzdd04eQQ2HGQSxcbc3GdsI1wqya/KaaMavwMVlMVfO2PYE9i7Lmr9U25l8pfIkEQl38EHm451xUaCQe2cHfMsfzHYiLekLnzjeFdC6As+ouuewbLrq99VzDYaYT1vK1ygXKvvTe0EaoRvVwe7uRJ0lOU8QYavXcNA9HTTbyx4VxURu0UtVM7m54Xnv/JFx155TSstKUKoN0kk08mVdUur/pJ/FM7n6so7YHrBNx4kw7HfUksQWF48JdEUV6B8jxt4YIB68uhFmJd16tM7EcDByiMHqBdbDhLt3Y7VNuluv5zUNGYj5Z0MFO3cKJo6u9hM762At9WP
    jyundt-digitalocean-passwd: AgAK2kxzZfWe/2GvYu4xYasUOz81phbAXB90RqmIf9OjIu2X6o0l69n2+sRtdMqYRvsx0u6vn/BqvPhPaz0WqjkjX6wIjJLLDrYur0PPlWM9YCwqMFf270r29iDzvTjK785eTVK6zdveACiGgV24lIuaL3dsPWBPP4ehxF53w7xLEPPZnmC+QV9+czqLqQi2AOCzXGggzbdvHjX3JpysrVBmOIamBXFJejmxnX4vEGDmwnYTK91niP985HU5fDz53f6yjSHNmfGSYloZWssVEH3W8kIAT/0k8aMZYkIp9Uc/TOEgoCClMrLsJAlS/YLg3/mAr8ebX2yMknQM/k93cyZASsA+M2z4vrDSDHZItw3Lf6t5iAPONWa6sSgl9DQx1NkgYCvJdJwOcNPrjXMkzlBUmTpntF3F6BOYfWAP6hyxBNwzuzl/4pvg6/89vX3JOeT9aQZm0g8ZLG4lattCYYN5DyCP45pb8R2N28WVcvooXKP3LQ6KfpZzNAMlzPpxk7jR8m1aK6yPc2jMxh/IpAOfJl5dmJVTj+gdtxexVToyh/+joE06ZMBT05z36BRLEYPI5ZS0wXkDll/uKn3dAqHgH+Tx34u/Vmcn02zQxkQgAZ73dxU8Un7JZ2hzcd6r+EdYpSzuqh3GFsQ3QljaAc4ncsrdKrLO0yDbNoFn1s13imx3sbT2aAYs/Z3pNqzI8O9xHxqvIWHevOJ7aXWUH0/N
    jyundt-gmail-passwd: AgCuOgWxDy957EdWcwHs0rt4a/ZBPEbUfzqhgw5WMfM5XYtvqnNXnVeHDZxxCJEdI9tqfYhpbDJ7dTkThbFy0UX77v4q7FDH8eQJI3Gy9whf77v6jKOvXcL1P3LP7I2TA9PLqdsFgYXQdeG7lM3bMaeMyc4PGJbI1CPvBAUDLKeYkRjlrd6vAA3o1UmA9RaX+9L7A8TnD8F8oQZcXX8cfHkqOMBK6mWOy7T5cADL/28cqVyBnxB7YfJ5QQpIExlHTCUmzsIgYvLernNuBr7lopWhg0XRw648gJLEMF8qhm4Gy7sFqAiIet8bJx5mBOdCTeGmMKjSzBZ58zKVP7qRleTYi4zicWKQONqO9ox/Fqx/5bLhcr6j8GUheA3vVRDsq5vLKa6EOXJYN8DRQoHXkJgxK5bTfmBD5+/79EM9TSp6lX/7NwaNSMieHUApyo3+KsihvsAp7WK0wUipFWGuMYiTxUFCvX4oC+2HtFDY3Cm5QCJNezdmd8coMym8S8uS9pR3MSgfwUb/h5Pn4iqJTscUCP9AFS0TzvHK/PMXaCbSvAsZrK1bjlQyebogRv2Nl814/i5j0B3KfgWtYm18wusD4b8guAY1fbqUZz0NO1tnniHdhtrKhwT6gwc0jxeb8Oq/D3XlP3eiYVJPyHrUwb6ekoICQpp4jUmRQIvH6s110KWljRmbGCP5cPDltSJbDwEkhjzGcHzCJ0yHJppvKzpe
    token.sec: AgAz5vSwE7ThYUvCnFCPWwySJltWLKp8PEc87Jz5PMHVfFDwWNKMmRB+p228lAydy8vstmvMlEbumI+SVrv2h66BfyAhVYd8EokiGepbRab0Xtm2LluJTshhGNhnEale0Rv76kLjuGM58e90Oy29vFDYpApXbssvJ6TLX0ItV2zNjob+VMzA7ftTsd0LHnJcD9hnUE0nYwetRJmVMKQY5cR8UkMhNjaFIavdOnOiH3YXCJ6CUmny3E4uHVwN91eJ60D9lggMCEIkMh+4zaT0p3g/RqmlqJ7/MawgENWqcY8ApV7FUNSGb/8ecx9zJpJ0x8mgZHRqaya4mXN4BY58VUrUSXEyzXxSQ82FIvnDRhowUY4cvj7p0CJxXCKiVaJJKDECLmtEcMyBo79DnbtE2zxoSBhZjLBAsKc/uodAQ4Dn0fwFIJQ7aIvmCiTa+aLv2khn/715a/W1etSiDkcvn0yqYwfcYGzu+Sb/AGZAEJ8Bfu+KktYeZGQgRf9H+6HtieHBvEVCY9oPUpRYAkEW1+IN17olO+kyz2AjT3KRD5KjaPsLTmASUeSDYzkKa4MRlhwfkVryAdZGWyUkTd1WZEsa9H5TW8r7iIiYZIrU5UP4/zGwBfLai4Yg7LfIC6yw87OVrLVXQYH94GwfLQEMbibCRT8zNhB25I1TgDoUqLEyCVd/dBcOuVenOeMBzzNijijKsEahvmLQ8O3IU30=
  template:
    metadata:
      name: gmvault
      namespace: default
    type: Opaque
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gmvault
  namespace: default
  labels:
    name: gmvault
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/backups/mail/gmail
    server: callisto.kiski.co
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmvault
  namespace: default
spec:
  selector:
    matchLabels:
      name: gmvault
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gmvault
  namespace: default
spec:
  schedule: "00 4 * * * "
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gmvault-jyundt-gmail
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/data/jyundt@gmail.com"
            - "jyundt@gmail.com"
            volumeMounts:
            - name: gmvault-home
              mountPath: /opt/gmvault
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/token.sec"
              subPath: token.sec
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/jyundt@gmail.com.passwd"
              subPath: jyundt-gmail-passwd
            - name: gmvault-data
              mountPath: /opt/gmvault/data
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
          - name: gmvault-jyundt-digitalocean
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/data/jyundt@digitalocean.com"
            - "jyundt@digitalocean.com"
            volumeMounts:
            - name: gmvault-home
              mountPath: /opt/gmvault
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/token.sec"
              subPath: token.sec
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/jyundt@digitalocean.com.passwd"
              subPath: jyundt-digitalocean-passwd
            - name: gmvault-data
              mountPath: /opt/gmvault/data
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
          - name: gmvault-emily-wolfe-gmail
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/data/emily.wolfe@gmail.com"
            - "emily.wolfe@gmail.com"
            volumeMounts:
            - name: gmvault-home
              mountPath: /opt/gmvault
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/token.sec"
              subPath: token.sec
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/emily.wolfe@gmail.com.passwd"
              subPath: emily-wolfe-gmail-passwd
            - name: gmvault-data
              mountPath: /opt/gmvault/data
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
          - name: gmvault-emily-packet
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/data/emily@packet.com"
            - "emily@packet.com"
            volumeMounts:
            - name: gmvault-home
              mountPath: /opt/gmvault
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/token.sec"
              subPath: token.sec
            - name: gmvault-secrets
              mountPath: "/opt/gmvault/emily@packet.com.passwd"
              subPath: emily-packet-passwd
            - name: gmvault-data
              mountPath: /opt/gmvault/data
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
          volumes:
          - name: gmvault-home
            emptyDir:
              medium: Memory
          - name: gmvault-secrets
            secret:
              secretName: gmvault
          - name: gmvault-data
            persistentVolumeClaim:
              claimName: gmvault
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 2004
            runAsGroup: 2000
