# I'm not happy with this level of indirection, but in order to avoid leaking
# sensitive information (like email addresses and names), I've wrapped gmvault
# information (like email addresses) into (sealed) secrets.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gmvault
  namespace: default
spec:
  encryptedData:
    user1: AgAoxjOEgsnBPEqsg3X0fQnTjkxjYembScSq9bGPC7hUZ5OTtXW4goZ5YqSrcmd6DHzIIiAtRI0u7841uRO+coNFtklQH7PPKJ7wJOUDW8t1CERB60M3MajBmugybfNvDHkjWcV6/F8Syx7AFUsSXcrNHtWQSejvtrMbl4ff3wodNT2EdS1Z1sOfTysuMzEjkraRhxs3a7D8zV9B0oySclQ6P6SN7VdvFZsOzzUOMpoU2w17MnejtQ5C0lQuC0R6f1dW5TNW4BWTUnlJMIrdRicMh9hGXzVxvgFyW9mC3SxYniBSsF9kf0NFd5/gBqPnV9Z778ccIdl47UgvMLwzy829pWLa7svdtu2ZWELExiPagyATJ5tSs8bJJ/MSakifaldMRdhLYBZxg4h6yxVljXw5t4/vm4WrUgEji5sVTrDVs223UdforXGWfMxuK6PARjAJJL2hwj0mfVKB1HZOteMg/b5e7rmHqiX80GSfv0zAQzfFS8xm9xxB5Dilr8PdmOhPUk8ggt8kwr70nv4Gm1Bg1GF36IgsLTEfWMZgDAMRhm5Db92jadbmqJbYa3N5YKy8Qg1JVoy1nP0TQ0vZjh2XWOzdr6mWnzAa7henGAEy68k/AQqiNHHHWrDggMnFmwlzYtGS0vJNBagsEQlzO87jn/Rcy6ajHyL9Tq2NQ3jInth2nGbGdBmlfDQl41+TOy2C/mlIus87jYHDEQMbbAVc
    user2: AgCEASySyRc61Sie8lr/y+nXZYbHmgqRCOuXMk2/rj3iKFF70llVjaM7lbcBS6/zBLeUWCFWiNFRhVCRkNl0xhnPonYMgj43V97n42bzvcWqyNQWPzWRAK2ekMer2PBujSRhzr8weX6vx+b6W6ka3zXFvtNF2tUM+q479JWllSviiANNFtsgL6YFkevb5qM69J5ae8lpEYk9smB68RLhUslWEHOkkAxsbgZQK7+Z/Y4wcYHRBwCthB272fzE90CgcxfRXgK8pqYoaBKCPtqZ4/A2R5w8zXaYZm9gv1Y5rxm8dO+sWXpuQdut7IksPdtdFWUVSApfCcQ70VSIlanAwoHGIRIWqSfNq6j20LrGjqiuikCJUGQ/VIIMEkTYxiy9M1au+vYp80GrCjsxFgWV8EICxqRR1DDp/QIJiscx+NoTMdTqJLysqvwwNVaUl+zXdbL4iq3EdjqBdVbwFRgCPdxfGvkRZU/VNOQjx2kBLvbQjuJEf1Bjy+km2sgUNphj1fF1RIghw/Va91hqiAIavZUbSnd57FrUPwy798fzMvE1v0ht5GS/AhmiOq3I1oZGv3lX2doPOGytDlXzLRBdr6WHhO1bE2SnHjNtZVz0+eQg2ZQtNPNjSMgCF2MzSjGCbWECIX7GZR5L8EhS8ATR9LncQrgJ9Ch+cpJ9kRugf+/SOLTn6vxRguyx5fvnD30MAgmVx0rspdfJvipKQ/wcEbXdWLAmEpobuw==
    user3: AgA1HYcr//UzdTOgdWzalt9i88vBQ7MIGZ8FD75C5ojLa5vJhX1LdP8EtMpPtosI+I03ZlRbYllfLiFtdmCFIXuK2tMa+vQ46fqyik1gAhZjgc2YEo1uN9K4md85AVy26Hvaf8RPIcpepJC7k4HjYf8qkB7ZT4+ibszXhlk7X98ZZTAd721E9xYrDcKytOq1zXB3upekAyc17sjJUdJo2HxVimVYs+IYnTjm9nEwPgEa5WjdXbC75o729iRYpnDqvbtuNBxpKQkClGEXeJ5wBqDCQlp5kw4uzwzNbMc9N4L/5czUET2VVCJLNAd7icLvCdWD6aJeo4N10NCcmroOX1OJhFRrEm9m1nkEX2xV4qDaxWTOf1NUoSigbtMV1N/ZLD1znG0pgPYs2zg8CIkAIaqqQPc8Sbhdy0PCxelG7RolHwD99p+PSnckrTUAY8qztxU65OThDxDGz5BSxTE94A1DK61OxVObt9mDj0jGFJedzy782sGdgmMI2zG66kD5cCGM9ZM/eOvSDV1OQhBCcN+oANxDzZCv6/6S7YmJAgnQ2p4jup3dqYHK9pWXMv8+C8QEtAkPIt2pgu+OLUITOyGkirn5haWdZ7wL5KDILVmwIwu/R0nqJGbwkmHU3JJpkpvot1d5fYaGLE53xQUgTtqoRIQcJ+XYH7fKliQ0Lih4YIarH7N63+hLI1ADXunOOasoCcgjDupSUfY93BJzB6srE8w1e4I=
  template:
    metadata:
      creationTimestamp: null
      name: gmvault
      namespace: default
    type: Opaque
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gmvault
  namespace: default
  labels:
    name: gmvault
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/backups/mail/gmail
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gmvault
  namespace: default
spec:
  selector:
    matchLabels:
      name: gmvault
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gmvault
  namespace: default
spec:
  schedule: "00 22 * * * "
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gmvault-user1
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/$(GMVAULT_EMAIL_ADDRESS)"
            - "$(GMVAULT_EMAIL_ADDRESS)"
            volumeMounts:
            - name: gmvault
              mountPath: /opt/gmvault/
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
            - name: GMVAULT_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: gmvault
                  key: user1
          - name: gmvault-user2
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/$(GMVAULT_EMAIL_ADDRESS)"
            - "$(GMVAULT_EMAIL_ADDRESS)"
            volumeMounts:
            - name: gmvault
              mountPath: /opt/gmvault/
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
            - name: GMVAULT_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: gmvault
                  key: user2
          - name: gmvault-user3
            image: jyundt/gmvault
            args:
            - sync
            - -p
            - -d
            - "/opt/gmvault/$(GMVAULT_EMAIL_ADDRESS)"
            - "$(GMVAULT_EMAIL_ADDRESS)"
            volumeMounts:
            - name: gmvault
              mountPath: /opt/gmvault/
            env:
            - name: GMVAULT_DIR
              value: /opt/gmvault
            - name: HOME
              value: /opt/gmvault
            - name: GMVAULT_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: gmvault
                  key: user2
          volumes:
            - name: gmvault
              persistentVolumeClaim:
                claimName: gmvault
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 2004
            runAsGroup: 2000
