---
kind: Service
apiVersion: v1
metadata:
  name: headscale-external
  namespace: default
spec:
  type: ExternalName
  externalName: nyx.wellesleynet.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: headscale.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: headscale-external
            port:
              number: 8080
  tls:
  - hosts:
    - headscale.kiski.co
    secretName: headscale-kiski-co-tls
