apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      # I didn't fork this, and I don't want to risk running :latest
      - image: kennethreitz/httpbin:latest
        imagePullPolicy: Always
        name: hello
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello
  namespace: default
spec:
  rules:
  - host: hello.kiski.co
    http:
      paths:
      - backend:
          serviceName: hello
          servicePort: 80
