apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  encryptedData:
    auth_provider.homeassistant: AgAr+8njsIDUNghcknFSuCmi+wXLyRJEWtsQU0ozrERaZGYqVOtZQtLlRG/x5smpnjtg937TaZCVWjO9YfWB8tIUVD9PbLBA4xIJY9zF+AjK2tDzmjizvzRt1ZxQXEe2cZ3fPCtfaoKwjEaQavZ/jGrML20kZkHmML/Qy9gMyW4wluQrPYQ/vzPxqa44ZcHLEzLSKeBMAbPMAhFZaigFHVsGicRZ0hP52H+xqaCd5taZJi5RH60+GYuj4+wNy4uNhElQsIKphaHwFboMUpQnt6oVLR+OFV24G70UDo3mYGFDxC5p6rU0yncokNM5UJOYJPnWpOlASOO+lt5Pwi0YJeeH5kb63mlwFxVks2X32GcZOqwHyDSB3hrCd/cB2Ux2VgLLTm532jBMyDTsLMf/qDclEG7M7DHSikZIxEgQiLH8FJ5BqvpVcEiSLDgRkSvfwgAbWblYY9RYmMgoVgVnWknJGjmQBnINnPteqkyjR8v1IP1skc6Gl/hVeP8K2tESfqRp6Pyt9s8scXpW+0Th/19l1ca3kfiD5CXxJ6SlDp7/I9gHtsM1itfZTQfoDW/2rY8/X7KXNDgGBG3zzfEGOX8rj3krCcJgWEkgA8nZqVJ1m6Zu/eHj/U1USDpAchXKpeCW2Gl1HzlWPt3EiEtgiaJjPvreyUZSfu8J2NVujARUv0saMcwNF5frPq6Y5NHehNSRH2qFb6dtuREn2fM+WErtZAv+osrK3jeSobfu/QVSZY8hFc+MgVJRT8tTm2R4wb+P45vIAmqvhcUxaM80MPIjpW+weLAKnS6aTXA4Mam3svAqqF5eiBANcZYpNZxc2YoybOeKM0dcmwNJfLqVWVPP4Ru9xQ5S3LhaNlXInwpEYXq0Smxuzx0Os6FmORngaKPj+NRox7ok/s0U9JUCzn/sY4hHzTWcY1U3zB+UVeONZl5X0DTznNC+BCvyrvzl2/aPZgLuKKGkil7dbVLSEa8vJAxxKE+Jrf9YI82R0u4Lm21nfzuGToRgoAQHy2Vu2yKjXMPyLj19dFSxBURiVijgiEs/hdgTu1+zDa9IoJAvwgvfjq4RAXdBlK6uFGySt4wPixJpdZK09/TIYqRlWkPqesgZGNwF6EcmZ6fAshbvbUd7Dk3Z7EcYUPnUYK4BfcfpdXhImVVPZi1otf3lVukSxAF0SPCyvH28/DSYDC4roheUv7X3Dbe6nXLjyrwDNESMlE5TrU1+WR0wgH3XLNCMgPK0FY7AuxXEV4QEiP61Y+i9ngXIDcZu4TR4VhNGLEXjabzmeVFuuxsuYnLBxcfyEiYC3PP+uUnW2J8diNYTQeOrVL+SA1+x6m2bBqk3eVZj69OJVemNSoZcC/8sblX4YOA/fd116+QVpvtfL5L3eXHJV6Wq9Yz+n93u7OhAgzLB6fcphzfg1IneK+q45MaQZlRxR44HzA==
    secrets.yaml: AgAXnDxNqHQuy2vwhtVkpu/2SmkJlA9Paz68QWEqnjAUKWm67yY5MuTob0AEKML+SVYNS3CEpvZvNkHpBtPHscq10kCiMdq7Z5maP91JiElzY+lI8UsWwjpnPdKkn8WZD3Hb0qIogLKgVkqoWCTD93zqKBMnYSQHRlkFqqS3nFlhzxHxbllVI9X0I0gBKQFGmvWIIeTeqv9fZAPINObFtVVdzzd5wPMz1VUB5mGIdAk73NHHumrvh5LTBEH6vRb62jkRoshZibIFU/+Cjd1YGHMmMrXiR4YK+XRMDfVp2Y6Zl9usOzVzK8CN++9otQErmmEaPG9eOOf1PBV9GLYCZHMn9AiVsy0bK43YINyT4d3Ax2BJ1JLfc8ItOZOIJqyc0v2FwLgRxjzUlaYGYR7eJmq3zYZhhPMzDgML7xa35HHRcCuOeZwxAMcfCCHjKEkuqEOC4gWhDEYbQ5pJ8KzpREhzBJjwcJJcdTbG+YoQZ01XiCet5Gehc7QKd5JlrXT0CddV6LwNha29ROurlVhavRxvqlJruMNKqsGiB5dFMVu1NFOTs/xOAhy2MYFOotLt8MxNcgTfWZvw/VXgfR6RlI3hSQXfJSeEdMTvLCX4wn6NXsLQnTcdFjesdU3Gr1XAJSAKco3TAKfYTshv3xl9XVfsFzJa5HqnW3wkZCMk11tZWA0RurVbSc5SlbRD+32CE2nDPf84Nf0+k5vySREi9+HG2o1aKHpyVIMNqNAsSlktZoU8nW0DRanfUg7RmD+cuycYSk8Dv7OtdVJ9O1nAlwa+CdvQ89XOkTIM0J9CUJyERDJ17HIH5s/X0U6gs0wXUYfhVOzWoKe1KMEZeXQboIo5qv5wOHoRJ7QD8t/aE34CQM+lB6cu4DQRllYAy1lVvYN3BUMBAFh+X3V1QwnuX1wZNR/XgqQTgOr99q3OgyvS8p12WnQY8VRFfQ60ACvY30SfW16Gj+hNbWSJoqAH1tF5OdqIlqiIy3geS9H/h314iolR1oJBO6msz+t7+IR+ymVKaisLt2EO199BN9ogJnt936N9NoVnNBnJcyfE0wU0gYoBOABzFMOA8hjcQrLpkm84ZXW6SG6STCKTZlpoLFb3QA3YJ+CyPPHF07LtWqbLmkJ8opzI98VDCTHfe6++xAuPPXZLKhuIqSywQL5sBNL3W3di680OB3AJUCq/0DRqrowK+eEAZsoC3fRDtOQEUPpiuSPU1bkzyJZeFRbC4X7SiIGhQDeHmNuXz3brKcARxpY93n3MVTfT9TJpBQadli6iNT1LYS/Nb1xs+9VBU9s148ns5RGBv2lvp1kkO8Ptn9uImIA5fuqczKJA/m/WDDHz0oGyBdLJCpd3k5r2bb8Cn4Ced+Owp+ZdeWvsvxhxYmpAseAut2ZWmbrcbgW7RSCS2Cclf0Wrta4hlOzHiOgh81lFhdlTn6iI97cyW0+OO1ycxNGAUo3T0/tjsvQBtgA9bWzCJj9CLDl9xTLDVEg9iio3MA1Obbxcw4y7Ag==
  template:
    metadata:
      name: home-assistant
      namespace: default
    type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
  namespace: default
  labels:
    name: home-assistant
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/apps/kubernetes/home-assistant
    server: callisto.kiski.co
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: default
spec:
  selector:
    matchLabels:
      name: home-assistant
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant
  namespace: default
# home-assistant is dumb and doesn't make "external" config management easy.
# the container assumes that the application directory ("/config"), is RW
# and will use this directory for storing all types of stuff outside of the DB.
# Due to the RW requirement, all configmaps or secrets must be mounted using
# subpath. Unfortunately we can't simply drop a Projected Volume into /config.
# (another annoying tidbit, there isn't an easy way to skip onboard or
# precreate users.)
data:
  known_devices.yaml: |
    mia2:
      hide_if_away: false
      icon:
      mac: !secret mia2_mac
      name: Jacob
      picture:
      track: true
      vendor: unknown
      gravatar: !secret mia2_gravatar
    lila:
      hide_if_away: false
      icon:
      mac: !secret lila_mac
      name: Emily
      picture:
      track: true
      vendor: Apple, Inc.
      gravatar: !secret lila_gravatar
  # this onboarding file is generated after the manual onboarding has been
  # completed. I had to manually generate this and then copy it out of the
  # container.
  # Note that it's also very specific to 0.93.2
  onboarding: |
    {
        "data": {
            "done": [
                "user",
                "integration"
            ]
        },
        "key": "onboarding",
        "version": 2
    }
  configuration.yaml: |
    homeassistant:
      name: Home
      latitude: !secret latitude
      longitude: !secret longitude
      elevation: 30
      unit_system: imperial
      time_zone: America/New_York
      customize:
        switch.leviton_dzpa1_1lw_plug_in_appliance_module_switch:
          friendly_name: Christmas Tree
          icon: mdi:pine-tree
        switch.leviton_dzpa1_1lw_plug_in_appliance_module_switch_2:
          friendly_name: Nightstand Light
          icon: mdi:weather-night
        light.linear_nortek_security_control_llc_lb60z_1_dimmable_led_light_bulb_level:
          friendly_name: Norpoc Light
      customize_domain:
        zwave:
          hidden: true
      customize_glob:
        "sensor.hank*":
          hidden: true
        "binary_sensor.hank_unknown*":
          hidden: true
      auth_providers:
        - type: homeassistant
    frontend:
    config:
    discovery:
      ignore:
        - plex_mediaserver
        - google_cast
    history:
    logbook:
    map:
    sensor:
      - platform: nut
        name: UPS
        host: callisto.kiski.co
        alias: ups
        username: monuser
        password: !secret ups_password
        resources:
          - ups.status
          - battery.charge
          - battery.runtime
          - ups.load
      - platform: plex
        host: zorya.kiski.co
        port: 32400
        name: Plex
        token: !secret plex_token
    group:
      living_room:
        name: Living Room
        entities:
          - light.linear_nortek_security_control_llc_lb60z_1_dimmable_led_light_bulb_level
          - light.living_room_floor_lamp
          - binary_sensor.apartment_door_sensor
          - media_player.double_r_diner
          - switch.leviton_dzpa1_1lw_plug_in_appliance_module_switch
      bedroom:
        name: Bedroom
        entities:
          - switch.leviton_dzpa1_1lw_plug_in_appliance_module_switch_2
      office:
        name: Office
        entities:
          - light.office_sphere
          - sensor.ups_status_data
          - sensor.ups_battery_charge
          - sensor.ups_battery_runtime
          - sensor.ups_load
          - sensor.plex
    automation:
      - alias: 'Turn off all lights when nobody is home'
        hide_entity: true
        trigger:
          platform: state
          entity_id: group.all_devices
          to: 'not_home'
        action:
          - service: switch.turn_off
            entity_id: group.all_switches
          - service: light.turn_off
            entity_id: group.all_lights
      - alias: 'Turn on all lights when Emily arrives home'
        hide_entity: true
        trigger:
          platform: state
          from: not_home
          to: home
          entity_id: device_tracker.lila
        action:
          - service: switch.turn_on
            entity_id: group.living_room
          - service: light.turn_on
            entity_id: group.living_room
      - alias: 'Turn on all lights when Jacob arrives home'
        hide_entity: true
        trigger:
          platform: state
          from: not_home
          to: home
          entity_id: device_tracker.mia2
        action:
          - service: switch.turn_on
            entity_id: group.living_room
          - service: light.turn_on
            entity_id: group.living_room
      - alias: 'Notify about presence detection'
        hide_entity: true
        trigger:
          platform: state
          entity_id: device_tracker.mia2, device_tracker.lila
        action:
          service: notify.all
          data_template:
            message: "{{trigger.to_state.attributes.friendly_name}} changed state from {{trigger.from_state.state}} to {{trigger.to_state.state}}"
        condition:
          - condition: template
            value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
      - alias: 'Notify about UPS state change'
        hide_entity: true
        trigger:
          platform: state
          entity_id: sensor.ups_status_data
        action:
          service: notify.all
          data_template:
            message: "UPS changed state from {{trigger.from_state.attributes.state}} to {{trigger.to_state.attributes.state}}"
      - alias: 'Apartment door opened when nobody home'
        hide_entity: true
        trigger:
          platform: state
          entity_id: binary_sensor.apartment_door_sensor
          to: 'on'
        condition:
          - condition: state
            entity_id: group.all_devices
            state: 'not_home'
        action:
          - service: notify.all
            data_template:
              message: "Apartment door opened when nobody is home."
          - service: switch.turn_on
            entity_id: group.living_room
          - service: light.turn_on
            entity_id: group.living_room
    zwave:
      usb_path: /dev/ttyUSB0
      network_key: !secret zwave_network_key
    device_tracker:
      - platform: unifi
        username: homeassistant
        password: !secret unifi_password
        host: unifi.wellesleynet.com
        new_device_defaults:
          track_new_devices: False
    lifx:
      light:
        - broadcast: 192.168.67.148
        - broadcast: 192.168.67.153
    scene:
      platform: lifx_cloud
      token: !secret lifx_cloud_token
    notify:
      - name: gmail
        platform: smtp
        sender: jyundt@gmail.com
        recipient: jyundt@gmail.com
        server: smtp.gmail.com
        sender_name: "home-assistant"
        username: jyundt@gmail.com
        password: !secret gmail_smtp_password
      - name: pushover
        platform: pushover
        api_key: !secret pushover_api_key
        user_key: !secret pushover_user_key
      - name: all
        platform: group
        services:
          - service: pushover
    alert:
      ups_on_battery:
        name: UPS running on battery power
        entity_id: sensor.ups_status_data
        state: "OB"
        repeat: 5
        can_acknowledge: true
        skip_first: true
        notifiers:
          - all
      ups_low_battery:
        name: UPS battery critically low
        entity_id: sensor.ups_status_data
        state: "LB"
        repeat: 5
        can_acknowledge: true
        skip_first: true
        notifiers:
          - all
      apartment_door_open:
        name: Apartment door open for >5 minutes
        done_message: Apartment door has been closed
        entity_id: binary_sensor.apartment_door_sensor
        repeat: 5
        can_acknowledge: true
        skip_first: true
        notifiers:
          - all
    binary_sensor:
      - platform: template
        sensors:
          apartment_door_sensor:
            device_class: door
            friendly_name: 'Apartment Door'
            value_template: "{{ is_state('sensor.hank_unknown_type0201_id0008_access_control', '22') }}"
    recorder:
      purge_interval: 0
      db_url: sqlite:////db/home-assistant.db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  serviceName: "home-assistant"
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      # More recent versions of home-assistant are awful. They require the
      # WebUI to configure integrations (Uniif) and are extremely hostile to
      # using yaml + SCM for configuration. e.g. everything in json under
      # "/config/.storage".
      - image: homeassistant/home-assistant:0.93.2
        imagePullPolicy: Always
        name: home-assistant
        ports:
        - containerPort: 8123
        livenessProbe:
          tcpSocket:
            port: 8123
        volumeMounts:
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        - name: home-assistant-secrets
          mountPath: /config/secrets.yaml
          subPath: secrets.yaml
        - name: home-assistant-config
          mountPath: /config/known_devices.yaml
          subPath: known_devices.yaml
        - name: home-assistant-config
          mountPath: /config/.storage/onboarding
          subPath: onboarding
        - name: home-assistant-secrets
          mountPath: /config/.storage/auth_provider.homeassistant
          subPath: auth_provider.homeassistant
        - name: home-assistant-data
          mountPath: /db
        - name: home-assistant-usb0
          mountPath: /dev/ttyUSB0
        - name: home-assistant-usb1
          mountPath: /dev/ttyUSB1
        securityContext:
          privileged: true
      nodeSelector:
        has_zwave_dongle: "true"
      volumes:
      - name: home-assistant-config
        configMap:
          name: home-assistant
      - name: home-assistant-secrets
        secret:
          secretName: home-assistant
      - name: home-assistant-data
        persistentVolumeClaim:
          claimName: home-assistant
      - name: home-assistant-usb0
        hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
      - name: home-assistant-usb1
        hostPath:
          path: /dev/ttyUSB1
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - name: home-assistant
    port: 8123
    protocol: TCP
    targetPort: 8123
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-assistant
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - host: avcad.kiski.co
    http:
      paths:
      - backend:
          serviceName: home-assistant
          servicePort: 8123
  tls:
  - hosts:
    - avcad.kiski.co
    secretName: kiskico-wildcard
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: home-assistant-oauth2
  namespace: default
spec:
  tls:
  - hosts:
    - avcad.kiski.co
    secretName: kiskico-wildcard
  rules:
  - host: avcad.kiski.co
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: 4180
