apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: joplin
  namespace: default
spec:
  encryptedData:
    MAILER_AUTH_PASSWORD: AgA4gcC8yRE+If5elyCoRtsoG3J+1OTGk9/2UBcG8PdOsG0/G5wJmYog+zBTkJWohFxwFTRCUC6nAq3E3HhK9zwON/+nzRpwhXqIeA5LkhmlccnByzgRigzVcYx57TMS2sFIL2G9Zx7I33Hqpon5FWqEjYKrJnk8b8ys86b/10rPJo4W6F4L1OEjdQEUFQWGYU9e4ehgZ+RxxRxJ87SY1iYddGnAv/X3ZO1fMa+C2pHJcz1oAhSH29XU6orKciNeLSG7UhCuTYKz6RR0up8mAWrk1mrH6vy0lMjO+R+EIwRB/Ad42VFyFxrUQ7vnJjG3C+KY+A3a80S52AxinrcjAhUnxOQPaTaUEx+YGs9omRmL6B3dd/q1yeHCPqHKkRz7nIwXVrKkxtfMfDRhlNVGA3N/mfM4OGuEjODCsqpgCQbvGEfet+ulMi3tGCoJXRB6fJd237ME/cQ/JcfAjtpqymFhQwO+pzquklz+JPBy/aKjmRiPISglBFJWGDiYRplM7MzPxQpMpBdNRms48RY5zhMlP8UkkLbXmGMnI9mSrBi+PJW/13QgOoj2fEmM+Ye8YXWFNrotef00209TU3T6TsqpNrmSy5tF5Q/Gmf6WGF4U0aNvsMEMsm8dCsJ6lpLa2vwwjFOHLxYfyHsRq9WAxQiTrw3Wo7nxs6mOhkt1Ol4s98DUAOG363yao0sK8koSHmDt5ugi6eexAGmUglPoK/i8
    POSTGRES_PASSWORD: AgBuQwGCUkWQYKQYsU7j1+pKU1umkyqh3uqbTQyIy85ONBwSu+fFVO+sHXpKBu2KZKT9kzVA+I7dX7ORXWwnNqQWnLIZYzYhhae3mokQNgxrbH1q46nki18tu4OyL95trxdgZAqweahEt4hed8eYaUD7U3CbjVJBUwsHe2Y7bJLYWhKrmSjmq+YUQg0Xppl/ZR5LupmilVIFuo/doKYyc6OC/D0VEQ7OFe0C46g9q1tYRNgMEwoeItoFoPsaVDALBOjV74occnfOGHwDjgjThwMeo6k3NVxUnnBKIAASXHizP+/3RC3AdjMqvp6EQwB2Zx9TzISMC9c797pJQ+vi4L0PryWuBggmVaFgwevjQ02VvST1+L0hrjWFHNFTUudWT7o1SLx9WA9bXIll3k/tKjSmiESihIfJANBLOfokkNUXZWxlFB/I6qKhXahLLjH2IPGQv15hyZ+ISmAwa6/BlIEdsJ4Nv3409FYWVEV0a+OU4Qu8dhFsjkRbBvf2fyqG/FzsyK9NDKt8OMPFNBKR4E6SUKzXVQK6PY5CYoIr1k8QlYtIrHzbdb3S7+zOeKRDTB+34BoVw0GwH0rQLOPsOrZhDG1mXsi/LcP6YP8AlfuX+2xWFn7gVGGRmM8GWgkJMjlhNcRMJtKi3CWHdxdZeIuunaq0REUW0TfuR9kSvJabC5eUiON174XDqt4qE+1hFo++/zpPG84kQ8BYFFSGaz6ZkQC8Em8SYa1E20h6YdnnaA==
  template:
    metadata:
      creationTimestamp: null
      name: joplin
      namespace: default
    type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: joplin
  namespace: default
data:
  APP_BASE_URL: 'https://joplin.kiski.co'
  DB_CLIENT: pg
  POSTGRES_DATABASE: joplin
  POSTGRES_DB: joplin
  POSTGRES_USER: joplin
  POSTGRES_PORT: '5432'
  POSTGRES_HOST: joplin-0
  PGDATA: /var/lib/postgresql/data/pgdata
  MAILER_ENABLED: 'true'
  MAILER_HOST: smtp.gmail.com
  MAILER_SECURITY: tls
  MAILER_PORT: '465'
  MAILER_AUTH_USER: jyundt@gmail.com
  MAILER_NOREPLY_NAME: 'Joplin Server'
  MAILER_NOREPLY_EMAIL: 'jyundt@gmail.com'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: joplin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin
  serviceName: "joplin"
  template:
    metadata:
      labels:
        app: joplin
    spec:
      containers:
      - image: joplin/server:2.13.2-beta
        imagePullPolicy: Always
        name: joplin
        ports:
        - containerPort: 22300
        envFrom:
        - configMapRef:
            name: joplin
        - secretRef:
            name: joplin
      - image: postgres:14.5-alpine
        imagePullPolicy: Always
        name: joplin-postgres
        volumeMounts:
        - name: joplin
          mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: joplin
        - secretRef:
            name: joplin
        livenessProbe:
          exec:
            command:
            - ls
            - /var/lib/postgresql/data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: joplin
        persistentVolumeClaim:
          claimName: joplin
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: joplin
spec:
  selector:
    app: joplin
  ports:
  - name: joplin
    port: 80
    protocol: TCP
    targetPort: 22300
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 16m
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: joplin.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: joplin
            port:
              number: 80
  tls:
  - hosts:
    - joplin.kiski.co
    secretName: joplin-kiski-co-tls
