---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: joplin-webdav
  namespace: default
spec:
  encryptedData:
    auth.conf: AgCDshcElJ2BptZt7gBzthQU57o5SZsQ7Gr4rog6Osto4anQNMUftjk9p4ZrjpTw9YXC/1vbWMUyw7rDZT9CtEmJDWNFfLKogDb90R3604kd7Zv+RZk4TlUd22yWojMNDGnLjUm2+70YfjC22B0QwCP5+QcD5zj+lqvk+izzL8b7dD/r6hlngB/ryk29O/x6E7UtFp+KhHqPo6hz3ffTHtYa9OyANgEpWlbqETkOPe9D8lWb8P+P6yTZIb8OZyhV8VUDPg2D/B9+CdnCGezTLCc0Byu2oC3b0HJHvevgQjlLQvo1j2/NZp4N+W6ECbDYlUubi3NRP1HqDXTglVhpPD6YWLeXPHg0rXiFJ/WqVAHLVScdiCMw1gpVcmThX2Vsd9qEzwtZOTic+3p2Z0K1/cHX+1k5V6+s/FVgvWbSo7ipp6PymlAnFy7hddU+Wfcp08j2Eyt1sJUeG/oSTYIrTVB4S7bok0KpNdGBjyJ9NI9yzTrNUpVM21NcrUgVREQBEK+aQvAccXy2TUzg8+TLh7qZQiaj46p4MteW3nfmZn0qCgpbHNx+QK+256tgRBxyGaLQIaHJOWxgYMTPo8Cljl2fzw0bmBQj8eYSBDs1ULFjh6XfvnRQ0xZFw5xdMciOYzc/AfYxdW+WLznO6+AUmtHP4q1FTBgD/E7gqKGPBoNEzByzv3pBW4BBHYrMXxbogkwQEvKm/YI3anr1F69gtGaIoeKc0S8pLqaaE6ccjNRMQm+pWGo22+NmpbgqCUc=
  template:
    metadata:
      creationTimestamp: null
      name: joplin-webdav
      namespace: default
    type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: joplin-webdav
  namespace: default
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"
    Listen 80
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule filter_module modules/mod_filter.so
    #LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule dav_module modules/mod_dav.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule dav_fs_module modules/mod_dav_fs.so
    LoadModule dav_lock_module modules/mod_dav_lock.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so
    <IfModule unixd_module>
    User daemon
    Group daemon
    </IfModule>
    <Directory />
        AllowOverride none
        Require all denied
    </Directory>
    DavLockDB /tmp/DavLock
    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        DAV On
        DirectoryIndex disabled
        #AllowMethods HEAD GET POST CONNECT PUT DELETE OPTIONS PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK TRACE
        Options Indexes FollowSymLinks
        AllowOverride None
        AuthName "joplin"
        AuthType Basic
        AuthuserFile /usr/local/apache2/conf/auth.conf
        Require valid-user
    </Directory>
    <Files ".ht*">
        Require all denied
    </Files>
    ErrorLog /proc/self/fd/2
    LogLevel warn
    <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common
        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>
        CustomLog /proc/self/fd/1 common
    </IfModule>
    <IfModule headers_module>
        RequestHeader unset Proxy early
    </IfModule>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-webdav
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: joplin-webdav
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-webdav
  serviceName: "joplin-webdav"
  template:
    metadata:
      labels:
        app: joplin-webdav
    spec:
      containers:
      - image: httpd:2.4.43-alpine
        imagePullPolicy: Always
        name: joplin
        ports:
        - containerPort: 80
        volumeMounts:
        - name: joplin-data
          mountPath: /usr/local/apache2/htdocs
        - name: joplin-conf
          mountPath: /usr/local/apache2/conf
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/local/apache2/htdocs/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: joplin-data
        persistentVolumeClaim:
          claimName: joplin-webdav
      - name: joplin-conf
        projected:
          sources:
          - secret:
              name: joplin-webdav
          - configMap:
              name: joplin-webdav

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: joplin-webdav
spec:
  selector:
    app: joplin-webdav
  ports:
  - name: joplin
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin-webdav
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    nginx.ingress.kubernetes.io/client-body-buffer-size: 16m
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: joplin-webdav.kiski.co
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: joplin-webdav
            port:
              number: 80
  tls:
  - hosts:
    - joplin-webdav.kiski.co
    secretName: joplin-webdav-kiski-co-tls
