---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-kiski-co-tls
  namespace: default
spec:
  secretName: mqtt-kiski-co-tls
  dnsNames:
  - mqtt.kiski.co
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto
  namespace: default
spec:
  encryptedData:
    dhparam.pem: AgBN9bOlh7FxTZrqBFuDfr9nZLShLDWYO3QODZXdf+WrcD4H4QLvdew/zlhXCDR+P+pR+le80xKSRb6u6wOYalHetz7rz1IJO2izlV5m8/EEcu9pwBqvqzPBseqk9OAC/PAoTbbyZDwnC6hfX+uTufKzWrx+r7AJQClAvlMIIRoAjV59Y3sceng2BOnFRRfR46ec2L0B4YZ6pZGIcPYUeH7pyOfhbF/836Lf5xpPr4D8VXwiB5frQJ1mj0UJ2N0C/9ZDCyJ8L5wLMKDg9PVMjyp+Hc6UXNoGHQk8HVwDBkf2P2zvBHaiOMfVy64VNWPod/cq55Tow7hOC52d+ZQAdlbRwAiqNI4qtxADOSYPrdPvuftc4LKZKRgx+G+teG++NxdN8xnuPKjVH4nxO69752dUTMoguK3/xM1e9wcfWPYH7Mzp+iCd2ancHilkOZvE6H3Joohc8ymzzq1ppijwi1pPOxeMVM7oPkgNmierTq1p/uErchFa0yD2hylFe3S46iL0OdbBaAexhtk7Q9UcZ/hNb0+Y8PvnR10DEighJ08Mez3OJ22kd1yVBMLQDpyXYSkiFeXFQ4qJUzqe4Hv22GYtkDmrK8xu4nncfPihrugJqY0+0LRdXEqJOiMg+M28fzOZziRa1As0LQuYW+cCypUrWeCqrG49gmHmeQJ2FX8lAEfkzWKMcTln6iyHyNU3QCqmIXt0f8GHYfdTRiM9UvlLGS08bibH7VWcBsWOJyulG7HwLZdlatqEAYN/pUTxHBIwNsXEJV6betYMGdOGJOWqoiz9IjrYtxW5Jt8AbpwVUfOia8z8Dmi/2oJNZMTWS5NPOsX75Wo9BatqTzR0YCMYcwQP1F1JjfkrHGg0o8iNkvZd0mDUOdKr4wlIIAkHgcBEq1bH6BjP/3ZaRN6LEa3hjwaeQNQxq11Wn+QMfsYDwrBtWgIZupOFHOm6h0JCMmWG3jJCHpUUGb6tlxRLvf2rUGhNBKAlmAUXB8CBpj7kwf4RaqH8ih41gba8gELQpFeNxMaaszhuGytPiztYpkejo1YPtCpV+yXPNiUDgFv+MvIVPkfAjhix6wwxewOd/pjOjnjEbhK2N2RdWVzH7J9J3H2x52E3YNst9tQGAbatcM7U22V6Lna6+sAFn3RRN1EYbrF+e/oo98DjDS+jxhAvccDGoOiomsnX/29KYTqJ1xHz6s8VMD1RdMgYATNzO/MANGxMPjYTANLRdU16IesKOET7E7mUhSEjZk7GEtIcUKK99/SWyMlc
    passwd: AgAyeUCv5539vYGoM/1BvTBjgR8SK3uvyOVpXxu+kiS+AfWPeOElBVDoEun0K24BS70rUsKaFWLvcDDyWV/mVAEA3e9npsf1rroVvGiPiXq+WfUlNCJK2zDOz3C0/vkwoueRZqdA7iS0XWR68jGLQjYPRZGIlcEI3b0P1Ilm4suuLvby8vtmUDR712ItnzkxHGgB5QXoBIG0RXz47AjL6kuOV1N4BEOZXLXLAa4b3e07GMaS/0zswOBjxs8vB/Ge1tEQopMmr1sKSM0X8GbgB868ElBnyRbCrcY0XmJ66gQH9ursjvjoAHpLkQh8IhL9kna8Pr7XUmN6c70u0XQkIk5eZ5f+Wo6rjK72hk0h0JoNE6pU2AhckZP33yMVb6HA8FHOvooHHmFJEM7MT5Cu0HyTh31VnC6A0lrSgMm8jtbjpvNK53QPUP4Hz77HZbyXrao+gAPQryQ3F+UshD4HJ/JqLhkicXs2oZ7JsE+d7xClyHb3CkYypxEFnlpYBYX63pOFEQAiS3Rkl09Y0afzmzQ3qv66ICmMZ5phV/5S0Reo4Pf5dHe3It0chJ5DZtJZ5+XAWBDQteegd+Yw5zlFiWD7OGHTO7e/bVFZ1GFpBdZWA9PnqutsuJcaWgg5+9kXTUbMSOCJidpoGVqfMSZAyIh/ymOUUZva9/NQ9gafY/WemzAimItIEqccwPU/p4Gn8rGkyh3Lww+kCArC1QyVOutLiPheI2x6NJQomZuKl2W+UynfCptptqqavu1Y3wjvsOLNW72ceovteG6CQ+3PqbW+PXtC4NL7EuDJ+AlduZQqG7LGxRJm/URcmPySf8fo9SfnIaUFCcf9HQqQCtjTZPjrLL6fNiBl+g70iYVSy0aXfOFBB0e6ZN2fw1oNYsfGHELlkRv16oUBMEr4pXwSMKwNsXVITkrURX6+EpeU9uiUP8MSfx0B4L5/6tdrkG15yMhN1t8RNdHXWxx+4MSOqicAzX59arH5GwvtXFVc4RjU4mcE+fIXikrVE0CUowPnNeZ+dOo8UyIxTfoCy3tWUPHWN0BU/JvfLyOqqF2LPAHpqxMxZc8gskhIyjR+YiVm+pP0TFWld2C7YbtLrMVqvFIFkLUwXWI5EoLoq0ZqubJQ3Ojyg3yH65KUBqvKmP+TGPn/Dc8FYrGqeFHDh8Zx77WhlHGyRiuOdjicdd50vMHuzuG7X9r0SF4f5AYtYcSXBIloBmJXooyZY06EdGTS2ZYyj/5j5ijL5zt2KNAiuHTf+b16JzKSGD3BURqjpv6dF3ZQmp3U3QdfefG4BdKln4BcTx5ZEuLWvOvhbNyyHEnlTyjAp5pH1/v5IPX2W8lBFzVvLQA/0ASKZ3wsNA==
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto
      namespace: default
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mosquitto-conf
  namespace: default
data:
  mosquitto.conf: |
    user mosquitto
    listener 1883
    protocol mqtt

    listener 8883
    protocol mqtt
    capath /etc/ssl/certs
    certfile /mosquitto/secret/tls.crt
    keyfile /mosquitto/secret/tls.key
    ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    dhparamfile /mosquitto/secret/dhparam.pem
    tls_version tlsv1.2

    autosave_interval 300
    persistence true
    persistence_file mosquitto.db
    persistence_location /mosquitto/data

    log_type all
    log_timestamp true
    connection_messages true
    log_timestamp_format %Y-%m-%dT%H:%M:%S
    allow_anonymous false

    password_file /mosquitto/secret/passwd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  serviceName: "mosquitto"
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:1.6.12
        imagePullPolicy: Always
        name: mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 8883
        volumeMounts:
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-conf
          mountPath: /mosquitto/config
        - name: mosquitto-secret
          mountPath: /mosquitto/secret
        livenessProbe:
          exec:
            command:
            - ls
            - /mosquitto/data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data
      - name: mosquitto-conf
        configMap:
          name: mosquitto-conf
      - name: mosquitto-secret
        projected:
          sources:
          - secret:
              name: mosquitto
          - secret:
              name: mqtt-kiski-co-tls
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
  labels:
    app: mosquitto
spec:
  ports:
  - port: 1883
    name: mosquitto
  - port: 8883
    name: mosquitto-tls
  selector:
    app: mosquitto
