---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone
  namespace: default
spec:
  encryptedData:
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_CLIENT_ID: AgAKHW5lToFZ14DwdlqtnxwhmNQlw0mDRFwOf6nc/9kXVk6e77JUyPpEvVQjCSIDrNnoomg6cl8uVy9opsl9xr92aszl/mFuOzrCppjJsnxZKo51PXj4zazY64JlCpnZTY9Wlvw/XI7+9UP5YA7WG1vl27bZzw7Mk0QNR3tmaFGFxtBGWrgF7I2950hKa3SFpB2qz62Hv2vuOjS1FkTKLZ9yNn9k1bK99lqG3M9e/kQZ6thsrau6wvVAsquR7b3txEoOBrAQVZ51I/KW7mz5KLM286+NiG9REKAHnPOOejzjdvqssWKVlsaUxHMMydzE6OXBsx7gQ1Lsc34XXzG0Mtp8ehM9mVNuClOJXhF4trw1FL2xag0ExWNfTXtp7RSdookVU9bIH/agidMlakQNvCuj55RIkHqvGy79JwGVTQPRLbhN8mAUgEeSYwYM13adYG6X5R2LjHSg+WZXiBDc7Vstk50GDsTvOZrArtbO2d1URGd3sl67LUofy1Ekuya/MFp6OgJW9apc92xGviJ6csSN9OAyCsdL3l0wLSZ6NODCurEaeDVzfDqHwm+VrpVl75mF8fqnivRRAfF19ZfhbvZ6YPs7aQQAvklSH3cUSC3h4dDA1RHF8y5eQwIP3D6lWulHEn9Zzn/SZSQwQhO0LDi3Wj56q0+8g9gimSOJafqhwyMIjxm/fl5afrQfO9f8xIqcR5BLfQeCp0btFR0gRf+Wo5GZOvFHR+DqDsvRQr+r7ZdsP1kTTfZ3aCH4s2a4DLfWn9cpg3+gJVVePolNysjfS9STbkaA8WI=
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_CLIENT_SECRET: AgDEFB2K+7VvoNv652AxwwDGB2TW2ua7YIXUr7KXgOYuv+VdK375G2oyKdtG+QYElaQ66lYrlU4nofRFxK2a3Ot9yWKvjXQKpmO0V0Cmo1iGevFTRUybGJGTc5jqiOxZeBAjaY6YEP2YjmBThGtyAyEqL63cgfE32gErZ/BxQlQPQzDZ4T2e/6yMyAh36M7QCV6fIhzi7EwdaWurcNOUXsPaFCmkWaLQ+n7Sz9Mu6O1X0pfsT3vJKNU8+fjCCSQnNTznbdKqVdDRMSs9pNR2dVwYy5q5XdwFW6PvwEyU3Bv/JOm/oMT9qomE+ETjHiq+OU7GJQgz7mzclLvyKl9NT8K3iaIJ3OegkZYcstg3fvWIKvGUTGbg7b8HkMgVpwcdh2q/5MMWUX8ha19tAAgQ2QM1xsSU5Kwn4PxCf4n/d2+p59Ujx7CvhsMRBysCLNGDPtOnDza2KXcikkj3DAi1DLUdZrUl7Q6aTeuc2LkdU9aTfUzjr2YlfCkHC3lBsskYGhs50UoQAffpwGFUkTMTG+LujyvTb87oYDZsep9z66p8jj+vaLhrCz7LIyZixQdKUoIQ/zGMJs4Zbye/AJz+3pKWJirxsZ1xjzHoZLufHQWgANBgvm2eEcZ9Es6eP8BAYgLFsPfRhh/4wOc1FbicctnQFr5OCXaNSe63YIHeEYFI3/pM5rcfld9Bim/x8CaOu1CEHMXMNefFK2sZw7+Ebc/unOxOXpv2zjk=
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_TOKEN: AgAZCo3wZOWIaObkNgeb4fW8U7eWuB9PdxF9SXHuzoNgXhlpEyUm33P8H+VtxpfbQytl9S+lvzJCDXNAugVz9PO/B92lbRoUZaXTo7rmbkZWJK4r8be0qE5sT5WluNILvvJt24WEJZ55uNHYYjeNDVA05PeQXqiIHQ5qwAWemqiYw8nSvp9J4LAO0rvuLFg30xRu2zSogC3UdRthSlevjcHPkZW8zyuZUVJMtsklu8lFQbUt6/9vf2gvQ63wEZVTsqlmOg1OL6sJZxxNXXf2hVt6qOSlI+xihoqSNv3s2iWI+kJfK/eXV6ap4Sb27EyJ87k/LStIF3B7zKAyeKWeNjKc6qYyCOidfeDwAFOOUM73bvLgGlV+szDddBvkGCPmnv3xx/cLdpbsAFMeDZfk/VxAGwSNkyzO3Ws7YSVvo22e7VGDI3q/EbF8uhZMeZe3s8+NQ+J1ESbrOYsJV++ekEUj/0KHLmBUkCrBSOf+evW3fNMCtBn7KubXsY1f7KATtIxliMeqRFgGUlFtQVnnFJpbgkyDyc37Y4SfUw1dP6Z7D9HMfnZ/exjckJRTtPFg4zu7ZXQjCjxyMiBE/gApiCiOJ2YfP47TAFSLhq03lRkimhiaDswPBKBKVhWeKjtYiuBiHpyl6v8i7X/uMiGMDMV6CW+Pci5LKtydTm3SBKuNW5K3ftb8ldsmusAv/GZDtv42ZqMpnRHKG0qiti6Xc7KoaX2LpyuQyJg2Q6N9LCzwenBvcDSGES/EPoxon5H32D8zcW770CmQ9Qa9wmJB+wWkmc6KWMu92JYsEEUU+rvXTYkbIaNbZsEFsW/1RXnUOWGApBlIWmlTMmQ7w665R7NpRj30S0YLvs8NxE6ETmLGAtKTTv46vnTUW4e95i/Daojgfa8uDDges7qyklmPBtsSvOZ69a8QMBZab464nP5aCHmKBxk+qBJ+pxE/2Y7h2/okG3YoaAazBsI6TCoZS5P1SNAPEZ7NVZQGOZbRbJ1xia19qY/XwBx9QJ5sEi0SDHSL+XbRNTOF4dOQPy059vAhLlQlUh6r/DjzArmEnckrcRDnzXKUEfpmJqKrkcZgbTCFqs4yJMOYy+OuEHfTbjJfS4MAGtd0tXezRDudIZJpTqlMggm9BLO1erzW7juJB/dgktP/6mCCIj4=
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_TYPE: AgA1nj6y84Q35b/Ax+i6nYs8sMmhxSR3UEoSbApbGkv+Z/OqKLZDAv5xGvjdDbwSQNgZW21pjRoe+AxLsCYHd8NSl97deFeXlmAb2jt0Is97ZCbdFZ+2OtQM+s3dE2gSFu0DVj59AKvKNAfYO4O1DRgJGmpDmQNGn+F2TZdK69EzO6NC48tkVuzHjbDvQaZnFB4qPI95itpgjuuxW4bb4mZzNFBpe8ezr2oEOSSYCieYU9TVf+Rv5xBQ7Ywj170jAdzqWl0Xp/g8qimhcdCCyzQTuouoF4gPhEIaGo5/uNlCrVXyP/aWsn0n5tgVoTSGZdos7pBM4jtUafwVwqhulnddQn2KGsPfH5miJry95FYZ9fx60wCHxSzw27WrU1IlIRwGKR0eXbTk/wO0IQB1JjH0E1iEvwXwyBKBYAz/CZcDFlDR+XHujw9NJX0iGJQvdxL+WBgGNTbWXmvibzScwgJ5528gpTl5Mp1x3W9yb0CmDjcH0c/xmehukrG/0wMg617uE6ro4uFxO39rnK3GNm5ZM6/ZzENx7Y4+TuL0kpH5+BJkpS4mjz0NuIrHyqB9taVaccqTXxHN6Mh/2ngWPm9VBLB5dH3brWbeLqSCseg4z50jsy+jl03rr+YUcGrSgsd6JiFIuB7qgRVH4tcGCZL2Ep8c9vVRWYkeLIzedUjpoXFtxxwTNXeHvrj92+LqSJkuJoIIMw==
    RCLONE_CONFIG_JYUNDT_COREWEAVE_GDRIVE_CLIENT_ID: AgAxhIiojzOFJh0IFFwlM6hnJ3rla6a/f/ELFkelsuHz+Wml74tg+w7KOOlgev98RUSVNjJJsTdm8J7RPPul4PkahhnJlFU6XWtpczfP1wMc9McbezS9uZlwQ2mdePwCf/3sgNRlQz55s38ZkS61enreS91/NZW7lspI002/1xt6OAViZG+fM3UKYpntlf8D9Doe8+u3CXuvrlznK0ZPvEIKUdNs2hvX4KNGna32TSSgbk++l3tXO8J+Wu9605Iguf2vB3y+P9NBbsWsrvSF9jraIrDRUfa1KbaHjq3KbkwKMA8jdXOcR828vvtoNEIGVM3ufMsjmjAEEEa4s50WKpFhoJDa8lDQYJTWOng+hv+xJOSkh0gzEwfHDJ386p6NLUESs19UwYXrpft42mKe0UwLkMVccRKuG8M9K3FE+K6Rkkt+z7IhAMnWxlcrlgkNEjwox8wdDVyM9Ktzw5uhSqkP+Y3dtlQVLNLcKdtfB5ifUrAVu6EwfMHPX7NVS2+FG34uB1XgOQNXALsx3hkVfnIfXM7q7rA2KS5fjti/KvaRuELxtzTQT3kLCNj5gZN9xGTznBLJn4qQfWiroe4VLrjJ44eMPkwjuAC/sCtdAEYmql0oVcpOfbIIh+KG6sLdx+40eUy8vuB2jaQcv6XQONWxuXJJJQGDvCThtjw0FwyPU4OawfeZdKO/2kVuFggIpB4w5+Pnr8k/bdYCGxaawmYR2aRDnR7RW0l5qiAGyD17ot0bTcOs9IQS8uTHHClKMEGyCrKKLmAK8Th9gQWzT62wjdIOPUeAS6k=
    RCLONE_CONFIG_JYUNDT_COREWEAVE_GDRIVE_CLIENT_SECRET: AgBI9Q8Ti7K/scgedy4FO05IKWAwrEAiGGzzF8vbdoTVm7JzAgM4BmpxJ4X7P0o+SGLw9CpiOEtXue4PTD33+B9QeH8fMpqf3R8x7lWSbXl27IS0rafcK8eRxT7FMKgM9Cib3hc6YpRp4thf+FS6Qabkd6RJm1z/VNaaOGyzjxnGenkPvz4t2h8OGt1EAtk2Fnr/m2A5on9mMVEBlwIndq3ZYRPEZdsveewsH1JUYgV61bNTc91SUQC1Y11Ja4g1yY1RKZEIZlMHA3PWbgJIaGVZv5IHcthxNkz/vS22U67TzpsykWLCkZk0CveIc6KTIH1VBFT9EsSExtME4LuGHMcfG06rFv8mVaogLqPhQiP5TancFo3VxU484mqdlVN+xy2B12/9ekN4qvOPMrPsbnqXY8fsV4+FVbXUmUXKDHnaE0JixDzp5hnjbfJFz+BIG8P56zY9CI6nuGcQf/5d2SQAV6wgXy/G7K72blpEad/I4Nyl2sFMaexT7hQ1K11y/zVWuDJ+5hluhegFWNZp1w+nlYhJRTvkm2Ckyn7tpiOv9oIXY5S3ZyKcz0zuOOrTz5N8Ju80jIpz11NgRpxVegQ7vsojqMaUYJvRbQ0gW+Wp5qfIkPjh0A64uPxqaRqaZo/B08/FAxjpQpSwocVv7etKpFKYPHBH5khFETlWefEeXStgMQkkdrsn6f5GWrB1nJzs9Usz7XwEM6QMc0F6YeC57TGelmbtsiU=
    RCLONE_CONFIG_JYUNDT_COREWEAVE_GDRIVE_TOKEN: AgCQid1N+napxgLlRsPS0fpcBUtdTM4U/qTQ5hUgi8WLHGzqejp1WPh6j6UXNjWalW4OANs3Q+YtHAO2x34CIWfJXntBdhiGYRlDT+gWoMYDBICdxt8GIRMu7ZrAlGs+dY3XJqufwyndCa6U6YPCI54DmQmLZm4kZI/2wnK98iBD1bdZBOBpb2Jz7RqDKNGjFEWCsPS7DHtRs59Y5y9wo12OtmEJ9ni9q3ZsttwIEzyQsvBliAsxYClF2cynxP2AcDikX/dfHNKPQw56k8/zzmjz5B8nOrFa9VfzLHnJxx4XXTHa2FZ4BjBQtdx5Uh39YL7tDrMcZaJ9dV1lRDhX+8GIoeR4P2Zx+BxXq01f6I8QvnbrxrzPklQd7xzqM7AVJEqBwOBi4jfdc2z8grhoiPlm2MosysZFShLAvn4VTqax3vK0/0vWDtH8iXxr91SArB8TUeKu1Yy3FvY3SOV7XlL8tnDDz/2X41nNQ3NdkK97JfJ55f1g9lNE3DBPTyEu3PABU52q135Labm/tTR8qiS2uGUKU1QkM9USy0s4Fo8NvB2giVIMcCv+UWm+ti3mIOm3hVBfYkSV0WQqHKp5nGQfaqQlmy2rfC5Wys4yzLR1dI0rbRCKtHt7OIqRxaJmMfwIsp9O/z7mPutWuxXu+PT/QG1NKfX8YijgNscDcc2ibe4EQ8ZCOgQrMmedRPjGWwaDvpgdwGdC7xbYzbs8eNj9kufku3kMY3K6NwIR/TGtHx6SamNz3hfhfrDRwVly1H3b8WU7b8Vkqrd6X9itI7d0rHKm8ZanlQFKlG95sjLh/yDxEF/eZGZhu9b+hZYWhUAwGoSyiBmDhsb/uW6lv+DNsqz32dflkK7ZmwD32hcPl7niw0Kc5IXySOAXq05u3uHy6U/IJjvhqZKnarggH+m9WkkJCHaTGSp74jQsBRxTP0v46xsw1GlwTS7QtFdBaxNjpRNFTIuvO0s8Vmv+Sk/06cQXRItuOop12CwXWYkdqRcPjzO+KcTfZh/pXe57YYC0cLFJqmNdOF92yOBKzcy1a+/dS7HOGyyC8GITAkuhvcEvb3PuqE3KJa0TEEmYTRZ0aQHy4wzJ+LmEYliMTOepuUz56VMfA73DIlUM7+aAH3T014K0wxUWLGXUanz90UbYikSWfrmsYt7tA/2lbdctnFHaKCTJ1ibwEq96LjWWGRlKEIxVjhOcbk95AAj1B8CHnpvR5QdFi2VKY3rrGVtIsudaZRDPskSqWrluLZ9ATi4SwNY=
    RCLONE_CONFIG_JYUNDT_COREWEAVE_GDRIVE_TYPE: AgBQiIL4YgGuBUAbiImPyV+AjhWXKBwj/AWlGNOtcc6vc4bZbkOigSWK8qdX63KyoZ8oIayBYChp0Y/mdovZmapW8dOZ8T7IvtdUItnefAJF/eXIINr3cfyPakNiY5kVcYDHhJclA2bC+FaHZ0I+CmydHRnwgYMuJSILLegH9R7d30N5p7ujfeWLuh3La5ddbnASuDsV95Pf+iRHleYMhs4phHq0gZo97N9piDGgnfUCua3Qv/yCPU6hxz2RBcBD8zyJL3Ji3+gICkRyQjEqd4eXC8X0Astjdt8/L+fi8n+oduJfIWIX5medDXfCDSjLlCi9bZYTEjlxHwiYLzFYoK3eGycd/FLkCsN36T3InmLjHjquW6lehIWcTlBYPtnX4HoUVTIsj9zAoKsdmReyiOlO2pQ2yP3D7uNTxsHrmWBHjSBe7MuDxhfNjy5qf/ro8Vwq4pIW2uJLTQnVHCDixqFxwwbrIgao8A2/9ha/fewzGmh0Y5wvAyausOSxo/bJhKGqkn+bx7ZBpqimSCD3T1dfVXD5gg3nFoN654b1Gs2A/EaVbHlVRTOIRcaeyItLQs6malL2cQWhTZDMjrKK8d5pszYZAyK9ds040RWGzmkNF3jhNTjvoUaUpFkAtetHt7a82rsjjR7dUFiZybuz1Kk1jRUmpkk1zsb0Lv88HX3pOVoO90y6bScYxF+WcA8Qdo+vmG4+JA==
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_CLIENT_ID: AgBxCfFmeTgCi/pr9HLZNGwhmECr4EOeUi5NIxqKQ+M+rVipcj2/MyIAc/MnWxADZXczWg3So+lAaMoS3DTa5LSrSO3XvuVhV9oQ+44Pqv8uQr38XGh1HoIj8UtMX3kFrNNLH4ewH8Pg/sHabU+GrgctkaAGFaR57X6A6ALmWaCqZZ10hjh/AZSpcb0OYROOcRwDnHfkoTmU/NtB+RFyXjYk/eDAdhYmTwQMyFlbJoROQVHSlJxQScpkKn7Ld/hbsSqJnPqg0Tev98rwIZ/+vLD/mFuIxFI6uh5wke2Z7RKrl9SeTqpTnKO4Rp1O+PIdubGdpWPfZ3BdIyiPWv/G9miZvTq+RIeWDE8VloktrRIHVAFgbntg7ftWaDURKQQvx7Dx6nKKm4993cv2EF2YWXiuLY52QUCDuAw+jsmIfeB0XuFentelCoasv9Pg8+Qya1N2k2UwbNbNJSgEBflzf/VeHtpgKHR8sJYLsmwC1g6qrAvuj6doZEaBdybjQJ5cnD+nVMev66oMRyXyvzCRteRPHhvGTxOf0hS3LHPihWNcgdCGIbLc48SdiWDcqDyAG7C3vWxFyhEbhxQDYKiH8VCRMULBzZqibb5gFwInk3Mp0gp/i59Q70vxsdym4wowYBykeMuWM2nDx54cC4Mcv2vYqSDOF+2RXyD44Zx5iw7V01xvjLJN8eeOQv0oWy4yrSC2C1oXeAVS+0Gv7di5ZgnNk/7RvxUPodOpNNQpC5MhFasIxAWRu3icpOmOvPymo8rgFnDaeTdkmhkh3z7pqjFLV51q86z6TxA=
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_CLIENT_SECRET: AgAtxFg/1KfEVlX7Ah9TPZXGqxgt6qOHk+s9W63p6RSGjOg0jfz1VN20Qow13diX9IVakPad+rIarQxSXUVjHa0P+Ho7UXGe5h4R8Mtci3cvSlcYbg9IDAZrlbzCRzqtVY5Z1Q8uMGgdll57tUsl0ZxPgUSu22+pxKiVbQkbsZOX3dEcGZX/ONDayv9i4vtRLL8f7oQhsIhmeXAsV1jG4u3pB2IcmRlW5chndX9mKE3e2Mg8/MThZpFI4317rF4L29Oeo7UyTS6ckxdn854PHJsA+ad3jts6zDeVzjrPAKBtPZlf9UiLiyjISrh8rKBcmpb0zd2kyVCcVw4c0cK3Fy4tzfXElNj4fGctSr0bHJjwF6YM0499Wsx4i6yI6QFLJYHD6PKZwtA4BoxWIELFeV/xdwvmLZYRDY4Hk4FfFeBvXWYf7OXoRr10FpV5lcRLMBShudh57b8Uh83aYVHL8yEfEKjdGBnDMN3c1T5faoQ5oTYbLtHXbIk6hWNSNa34JjkGH8CoWmQhoKtOQbFFBc0mworLxCi0CRZzO51UR8Ji9xzwtzTS38l15yZjoVtx4ibiWA9GqXk5XZqvh5+TEY0vjvEmQIzY5XfUVgAZ6NTfEIn6csLkZd41Kr74PtESel5v9+fAccnUDeHNkEI5m4hvLKubNoqlvji7PgREiI8z7UrGuCfRjSOIZ+JaE1xNRyK+rG9houiagwP/OmYiVtRFkWiSGSdBmSQ=
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_TOKEN: AgB/Q0z7b4V233aaXT13pRDmDag0gI43zveKRZUtPYA91bmUqUv4JCmTLl4reOXQOf8HlrNql3NzuHqTkqAXRcSgqLqqKjbDwqKzTC7C50uaDIU41oyl1HjEDaKwacXp94LT5SyQHDr4gbNQa34zVtqdHL4Nqm1wUk649oPlVRHFXqMhihtoKFsKm/z6mDpfJqm3D0OzYSmaq6qlgaG5RVCT3A/x6GGFEM6BzcwGz+7+7NX7hAiEc6Ngv+QItEbAKKoIU4BRvLGLZdfbdv5FTWwGE1OqXKI3/uVIxZQ7qp2+lLnXNBh5pmCs2EZ9EqoyGaYioBG3YMEXrWctY4OjABzSkyz06r6qr04Bj/N9NGczvAdhcqL9TYg3Xr4UMeG59HFuDPJ+5yXljKzKk3H7t5jnB0salmb4+DYmoUcQvK4XQR9hll6Z0ufLMkG6YzaXQNBCVtbmOFR43O5Qj4lUeXEnAqNwl4LMlf5gMj40V1qHM6eqBEmoI7loYWqUgfXZ8RomOXkpSUGneeVruSbrTPpvsuk2dto9PCk10cXa21svkizpL/fGY7bsPqJs9Dk59edTn8l0xrT0xWeOiBySVoH0p70fFWRnrikpzmtXXAruFj/3m1+UIUhu30GNjKFySoiMruAR6LxYtZW8nDfPwhx2DQBpjnbgLVSssLnEWh0nswM5w+x2sfFKdg6g8hVR3ha/UxRV0+dBzH5Xk3IoHITx3fMPh+UapGTvm3zJEhae4gqlUxN7Jc5AmXB90T73zJYOZlJWyL+JjuHe3oRLn7thHewxHFtmb66k/v0NwFu8nEilORzMwa3tNyxA/Qa4oE7sVkqAQgKIrTlQij4D5J318JcePDdyNK5nGZmHc5d3TA1lGUA0XUzwQZ1o4OAH7vCMTgh+uNIBrdunxvghbTpKPTLmz9DFln0whkDm2G1QEuZsJlcv+YYDznwfiw6t04oZg/k8HmwP5615weZr3mygvViz8FQ7sJVdF8wBZzDRbP/iYeU0/Y3RzYZkwVpDlU6qbBZJpLeMP23Hs8/EI1Vs4uxVZtmX4YC/6kJ2SYyXbh0zDTNI795X1zq8n7xJXA/olBXmfL5o6JRtrl4hUnETXZZFvdi+d/rZqbzgMybej5atFWLeq/XOOwdsXSaK1wZ3Hl85DJlXqtuxTtfTazFMxd2hXYikzrIMuTrGKlGRog3dMwVh+tj9X9J3JV66W+qGca1zkqhpsV82bbUPlg8Eg+P5RPoZeCWaxy4ZyhVoonv9Qco=
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_TYPE: AgA4pbCeDsrKIY2FTUbFHWUURTrBH3EsUFVjMxbSa2Djw69s1oV56JsTNbieZTXuY+iIPx6bS6KPh3RIyDBW1KJGNQ5mIUlfUk3t+T+pYmXarJqNzpPEPH2VmKZjxLOROY590dGOig/vvcmXlWO8p2+lqRorl22VIWsIzR/alTLdjHkEmKjW3YGZMXTtjqf2UXE0PyQLcH1VQ6pIdGzMWcKkYsCbFQ55YXFsg8Xps/oVxn4gCoC0HcDzG31SBwMrWfxOSgsviC6ZKiANNkCyL3YGxrPPj54eArySa3PCB1NF6xot0w5Y0dphDJ+CXD7lFelwROz6LnRU6PU85YpVA98pb/X0QHdmDPxfdoyZA32Bz9zjzAEFIQ1RWlka5U6oodHwlb5lu8xas3XmsrGv2lQrtcHrFQ19C4eCf6/Ky+3QARqpanZSWCjee1oGAwSj1LHa0GhUurVHtKMv0nx34i6pG990a/2LYBsupCvSK3yPUf6E8qvTXwwJ8vLoH7Wi5DzvkY/hpsm2fimpDWFq0Aupz/bHvfmUDEvCHRcG7IJuJj9UxWST5So49qg/jymXlixAjfLy405FyvuX3ax6FiskeLVsPA6829fLd0gdqGuIRa+Or9ETGiG0P96/s15rCU4heSR1FztfdBrc7PgvXmXAaltUJ3w07tPvZYzaI3xvNrvD4vnEum3yB5ALU/rdcTHQO+IfFw==
  template:
    metadata:
      creationTimestamp: null
      name: rclone
      namespace: default
    type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone
  namespace: default
  labels:
    name: rclone
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 1Pi
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - nobrl
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: cloud
    volumeAttributes:
      source: "//callisto.wellesleynet.com/cloud"
    nodeStageSecretRef:
      name: callisto-smb-creds
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone
  namespace: default
spec:
  selector:
    matchLabels:
      name: rclone
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
  storageClassName: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone
  namespace: default
data:
  RCLONE_DRIVE_SKIP_DANGLING_SHORTCUTS: "true"
  RCLONE_DRIVE_CHUNK_SIZE: "256M"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone
  namespace: default
spec:
  schedule: "00 5 * * * "
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone-jyundt-gmail
            image: rclone/rclone:1.64.2
            args:
            - sync
            - "jyundt_gmail_gdrive:/"
            - "/mnt/rclone/jyundt_gmail_gdrive"
            volumeMounts:
            - name: rclone
              mountPath: /mnt/rclone
            envFrom:
              - configMapRef:
                  name: rclone
              - secretRef:
                  name: rclone
          - name: rclone-jyundt-coreweave
            image: rclone/rclone:1.64.2
            args:
            - sync
            - "jyundt_coreweave_gdrive:/"
            - "/mnt/rclone/jyundt_coreweave_gdrive"
            volumeMounts:
            - name: rclone
              mountPath: /mnt/rclone
            envFrom:
              - configMapRef:
                  name: rclone
              - secretRef:
                  name: rclone
          - name: rclone-emily-gmail
            image: rclone/rclone:1.64.2
            args:
            - sync
            - "emily_gmail_gdrive:/"
            - "/mnt/rclone/emily_gmail_gdrive"
            volumeMounts:
            - name: rclone
              mountPath: /mnt/rclone
            envFrom:
              - configMapRef:
                  name: rclone
              - secretRef:
                  name: rclone
          volumes:
            - name: rclone
              persistentVolumeClaim:
                claimName: rclone
          restartPolicy: OnFailure
