apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone
  namespace: default
spec:
  encryptedData:
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_CLIENT_ID: AgCbAFztetCdN79Sk+/D8HzmmDGzMU4Ndl9/nWTYM55UdWtPX/UIj0lnfZvjm0YVVHjTphKK9rOYG/5VHvJ9e/PItEVy5BwufH113k4eXjNvUmI7nJIZGetqdb0CYBgcHo968t+674bxg6uqnogPk/zjku0VAe420Kj4DPbivjEKOF5/fKF8zecbfk+wbmXhQ892ff8p9Y7ClfyiGVXIcx+mmER3+cDn4OMiC9aK5+IWVB4VXOCB2ZA0f6sOfp/UPBmpz2+fPwjJsnz5lOlEAd2aMuUhep/PnyFMsMYoPWxpxksCu9pvbAsDGpBm/DW+lJjSYbD84amA+Fzc52hj9Y+C4V26+vBHyUljJb8E767B33i+vYwDyhPugyJcDRM33F6ZWhjaiIPOyQDckZibdCOJYnx765I9vxJmaKFmqdIAaRE9QVozxp/DBzkcwW4VcIu0dWfR3N1UVsOhd1OgCw4WmFlm6QdO5I9tyXqh5Errv+OAywEc4xvMxHMJvpJ+ueSM7htq6i/qgf5OrzQTtHnFjJNF44OdG8D/GoH0V1n47rE/XkI80wMlBq5UCYAsXwNjBJz9VscvWnzarF6njysADpGBmBczBDikR+Wg2XcmuefrPyPsmJR5RAfaE7EcOfQtB3B2tW56dcvpduZiBlB+p4LOqlsPrgZ9TvH9aaw7OXjbro0mSbRP2V7xx/J2Q1eQqsSA8QHdwHTdmuSSbkN5WsG3TEIuGk0s+YwmdBsT9MqI4LRbhctTX0N7V/tlavoVsADNuEwMeKvWgJJd4MHbooY5GG9cF00=
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_CLIENT_SECRET: AgCkkGeg77UZp0vMbtdSh7y24kfPUicPKu3BwrSPwTQprKEWHNk4IwACXUv8yVQfPUn7iljFY+l7ivOa3iXOQ9rWLvh3EB/19XlJLT5VgUWJmND+JNZJMSRx9/ScRWZ7VubKeQZSE7gJPhqkWeHSvyUviNdLY/7/CZRbZPW5v7HtyNRAapAIfhTIsDHHSeV1ON6gp7ZNm4PSpZenkic5NOetwJJiOV0Mn5/N4VlfTIgxkUTqs8iEJrdmwiU6aFs/7mvxqoGtacQ9kOe0RGIlEgMxjpz5BbzqDF2JuXEd6UMG6SOKUEk9GKelqR1vUbAGtDUTz5JrQnHxU8CO85qZ1wB0BhFkoP9cNSR2pmXc7DfSq4931DipTkOALJj1TiASBmMUxKNz+mgRBAhe+k0pZz2bMv5rBpQQzGsZqnHD0z7lSuOTk64+tTId9WmPCVEqsIaurxsfS/Og8tubWb9Lqzi+jIOVgo/mUUXdssUk7la0XM1bRnqZ3Vg+35S28lxweJwzm/nZx3O8g7QbR54lfCGhIGMrAZRz9GGJCvGgspWB4hNXysgQ4yp2j/wy0E6FpEbyrndM/Y/3QOHaHU3Wwr51pQpIThCTOrU8qgD2OmsgbLBbDvcRvqx2ONAlr6NkOvUuIDJp9XGdtDZWkz0VQu5abz2f8LpG7D/oq70VhZPKtnyiNNq1W2CetveM8o/EQD84hOhkUXeDIebvHEqVTbIXhcnQ80H77SQ=
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_TOKEN: AgAx5S/Xa7/PqGTzttct4x3lHIeKY7opRF8oA7Q502zLQA22a59fEp1S/M8MXXaeeHr0FMfdKFwTcVgE1br+ZQGnHlO+9daAqW+CJmFXxrLuHLa6QNX/Cd1cip3UBOKq64rjmBK/gykW+JbSUBrnhf8N0/bGThLqJWQAP2p/bu+ibMOEKA/g8ma2t90d+tbzEbmPJsw9n8IGnowjS5ZPnxGbgG3IsDRtwsbWvNwL7+LAUs3df0kWPYMyQqUVmVrDgGVfdYAAwJ6EfOPDGSyiSFV5poGjJ9s9MUuwKlYa1JvdnTif6tL6G9n4SC2Wc6qEu8uzyV4HQIKctN3zZWBkY9WDfKOLn6NO1WJNsUIoieZwQ6wPvKOTSUNia8Q//QODThp7FTWieVuHVZkbT0kE00qOy/PT0HZEAdxEzylbD/Vx76WDIh92yqyLGakyIom/Ivwj9rYDvjfzvC05EFwQvo2vjn7hlvPMyppiCZ5jC/RGeLRri9pshcuFqrEXeQ8+j+o5iZoevsMZNYqLQrX8fylkJtF1d6ICIbGghN7nY+nsDUs5IGQBy9lOqF1Ax0rMZXK0y/izcLGoRsQq6+F9hSWE5y4H/i4cUsI2pMdBY7PFJHWfxwVW+mFDc7MbiH7Qwrb5jPg6RD7BOnxPRQiUzmqj/Odn73/JhTIZ328p6T/2WAcf74DRXB7zuwzw73HP4uF6k9mlBUq1J9j5E48f/o+vgt7vQDqkmcVZrIqzb+2asxFkhfZ+pJOqn1AUkvHuTAAMRByiL0ttfXp5TcPlZkdmvSx4dIzhrCR8e2W59ICbHXcvbxLEc7z2mhotOGxndJJMV0M0L8oIusvd+sfWT6cQkIMxwERC6J6COlvdUseClnvTboakQ1tG6M4ml3fZ1y/M1qqSR8WgqZUhRCoUEGn6BcccJ+DtcYFpP9Pgx4yjoWyeAy7ZWy+YyXz/i4lUB7YT3QhsxcnxGPW0lXxhJmJ5NQf3cw7oPuwUci65H9PQ+2Fkxfiffx7ITgWCChEfcZBV0wYuopzvF+L8rjSd7BvuXBKhsBNCVu3BBUtZA18qdQz2ctxjYf1341AH0m3BlqynlXbA40SRWnL7j1TvQCW58V/0vfs6eFyPefhWjk/rdumpj/r2FAsZmuCByYFkXilY6vbOjBomIlo=
    RCLONE_CONFIG_EMILY_GMAIL_GDRIVE_TYPE: AgB2+NRHDivvXzfyv8O40hvd2g4RG9K7A8xEWCQmzR2giMOjoa6cuB12YArQ6KED6NSue0KyuGKQ6i5APWwPeT7NzYkUp50XE9KU7VO6bDPRdSE9pzAD6A2MBYiEgU/iQIeCHINjIBOlBDTwAvNpCkMvhsdIDCsxOoiPH84RZRRfI0P1cvngEHIyEKQneb7C/ai2icvaUxhYtEmwGQ29gp8j/5zxan4qvSXhGcewY/NOQC6WZ/hS2AvnsPC15LFSZZP4QmCf2pp0TwwUpshegMBDqdvkAnRr02uOzEoRbd4tizdLumiDoUtjA0oIotTgjDbIZDu15PKZODcIy0vKoOsla2cvrsdxbfbp7C80Jiyn81eT3vMNdr3ThYHNOXSodcWze6CDayfpQgCxkbn28QSDNm2ECI3qSSukZhlaJTKK5tcJ4Uqskr1JijjHM39hQUMoLsBOdK0+QOqttWF7GKu+DHlcPVet7NY/fcIHJxDuEchLVITMJ5IEuaeJCdeHu4g2S0EH6tcquUmWfr7VBgrRaWFddHZypCH+nT7ClBcVcSZxFLXzvljluCR9ZrBcQL3WMNF0KGbFXdhzzYqgcY+hFvAaFhMqg0jCrw0DJVgZiwxVkRPOUrDmDeBMcPwOCI27yYVqIWJ0+o8ZM9OFHmjBrTs2MqvtxyS+Qp5suAH7tA2hJqcY7ZqkDifFDIumKOO4JYEKaQ==
    RCLONE_CONFIG_JYUNDT_DIGITALOCEAN_GDRIVE_CLIENT_ID: AgBVtwIb7EoWs8POYt2Eh7xLZ+t0hxhspOGT/SjyqNUpbFk850KnJ44fpehg8NLqbd1fznYSiM5vy9s/vHy6pVf3oXc6d4GESb5fLcASZAQ9lSau8s8UKuNsfyv79KBkLmFq4H+6jT4UF20ZzxwUc1ytGrhfswJsH80BbrrdDh9Eoosj1vFfPCwLoG2bqdiiiNYjb5m7MBo263WL8ep+j0m3rF3LYzFrasUHdYQhwwiNbZipTeIdtMKkrsQRjyAHkM2oXVtjZHQvv16M4PBw89BxI95CPGIwc7cvojxU2GhFSSpcsAnH+8hpEhE1vYHjKwxVSUdHyeIzIR3TN8oSswOfREBrXvMcC7n8f8hK9CN9JXISRrcnQHRLn5TwXtAwGSJbWa6Ee9Veg8Fi10v88GkETSIrcnzUPC63K8muC72PtwghF75lBazoZgKQsN82j47EQV9VBOSoZObM94bK+HmzPWdBB/OKBX+pfHwd33zCdfKKFbPbmwe30fVc+6TosbrRWCqIOMqR0+5/gqoIzfk7/bnudZ70zvQlap4xEOtcwKNKrzU923Ej8ZzD8PgHTW5Qqw8TYNcbaremZYmXMftNso4SYfVGfkmh+/OmQwvU2GdzWePSh1RoCQuW2s4CuzdJueBdnZFUW60sWZ3Vz/YnwQ/ynTdD3SGCmSi8CUSBsiznV5Fuf/qKO+W65lwUnyd4lDmKl8pUO+aITfDo7aCswCIdyk+nz2ZBpV0z01aUnBGCC3oODDhq0zxdsb+Tn/RFhpSM8sZWm8IgZZQmhyA/35IOgER/X00=
    RCLONE_CONFIG_JYUNDT_DIGITALOCEAN_GDRIVE_CLIENT_SECRET: AgANtcCB9QS/WjeRppY3ketPqoQ5ryxSSNgnG9K6y9AU90YXWVLX2ISKroKlNO5RJCBeDIRHG2LAQfaC1UPDUCeDrU154ggRh7aAW2LxZfuqke/eZhK1hBjKRwwCOe+crsVLZS9Phbm9iSPJGOYZ0SrLf4zk8LZ7TxtNbnzN0MBj0BvEbIIAzuOsbTkVZAtciYJRHE3Iy0DINCzdCLOWlaqBvSGmt3KBLgLVVEJx1OcVNia8lWFKYZex0W/eLVEvuGQotaPm/ENFQZdQpprs4DMt37BOOyuV+LZrJ5HpBvtUPGJBo6RycyABZjuKUjzyNemD+RJ8/C8LTU32G3C1L1otIuXOMKOYqkqlq+9jSlPttUewtD+3dPfyEebzuihNoN9kxLx4w16LHwUfaa5cAxa4sj0DUSKOEEFYEqzzjm1cMlm2YEeYRWpF9qtmFmwPwqCohaNpfNf/qcZswDgkABO/DGTKcR9FJk2GFUCKelxDAVKQcrhyL3ScjBlTRhFYLeQiw2SQ95aiXePBZgVdDfE+yALhlyArVLF+9qo4LyQCFQcc7M71LBLQvKyprY1T106+kh6dXDJSNXwLRlPzx9TRF1DMphviaer9/GBnnUUPmTRPyFDVafaCAGpVlxW0Nt8XZcw6sZOFKbOfqGVLItYRtr0eNbLmEL1gfDraUl/XIR/IjRCVFaJ3MDeQrlgkql9z9d9iDHtNpdl/W5YhpB5+Ok/0GKqMZ+4=
    RCLONE_CONFIG_JYUNDT_DIGITALOCEAN_GDRIVE_TOKEN: AgAvs8RZYO5zY96XFcoXqkPNUbH2xmAhizhAXdb8xeuoUXV9COjAB+KDGfgly02kwvps3EGCtqcFBkLc0U29v8giahQPQC1ETrAK5in1WtADOLJfmjOnaifQwl1LrVrMhf5YGGwzX+Xfpop8esrv/yfBedor402FI3uiL8nEKb7W83TnkL8O9H1fONYOLbh9VAB1/JLwmM8cG3C1tx6FjpVWfnNHGSZ3EJK1Dz5tydzyZZ0mZgTaMFMlzMOlDckM+weFQpOVo3xxmPa43WEnjfWAIdc7+nqLhRCMj2ljV3A4b5wv1lGmsH/FC+uaL03rzu/Iv6IkXEVWgjrU5/ExZIk7GM+JiKgrEBY/4gfbILMDe5wB0r/0VBL24Dv5e17DDmykZWIw1k/iDqd+yEiB+TZCH7uFOqsMizaPS4YwG7+rBP3OBB21K8QGH9wzfrNq7iqXAlN5CYembvgWHNYaDn13c1blmIhQ9xIoZuwmZE6yudq5JLtV830hVEGk5dlXs7njG2J5JTVXBLeIkxI5YC/tzi0T5bgK2z2bQ8zpxDBh4CKgJ5q26ELU3+sFDbHUUB1YzV7n2gkFEL72ho0L0BhX4uLfM/PF2I/vKzn2U4lb0FqDtk5bWbcwvo17sZxZ/SQj0eAbmnFdkx7x3vxAFyyDuAu1dhlQP2C/xGQNI0OAKfATeWOC8eeqr/luxrXNkUR+3q4/z6O0vEGiLCMxjbOf8PxemObAYc+yDHiMfoCqq5jFcEpe0JBLAqm9+wosGAVXAxJBRnilxqVacOJl9qJ7hKNZ8PEwmGvjLyvMWCNiu7IpNq/lZ97cPOPWQQpBAizLf2B4xPXhxv+MgeEqUT8SBx7KC9TODvU02/4ybs8cusDIFWzw/GTeK4LS/1Dq7RS4+D3gY45g71w3Ng6Obni59tQ6iwZP+Z24NWUQ/4YCaWfQ0U1+ofAGTZnWWqI0tuY3zKcCaMZQifOvMqI95ODmsYU/yOOvX5P4m55S66PVYiDa+30CXwx9GtgK6TmBQpR/pLRsb1YQHQnA6kZo17sihGasU1DSnITxsQX91TM+DA+XOMLQIUdM9QmOiRFpYQ==
    RCLONE_CONFIG_JYUNDT_DIGITALOCEAN_GDRIVE_TYPE: AgBkUVbwZstvEPjYj/4uBHj7jIpLD5Y2ooTQ+7eSweZfg5E2pWX3uHv7Jh4xufr99R1s40In77GfI4slU9rqvxOR01MhC+s/pm8Hn+/2w15/yeLz3kA4K/OKP3vzd6rTbABREXx41lkurx1LHY3rG5Mgu+Ex8LFL3aRigxqKL67OSPr+uqny0gbwia0Xu3D4xa1NPdfZyITlADqHwHvhLW4UBx9R3TTprLjxARzoMv8Jfb7FudRGxGhmm6qj3jEUedAegPekgjNvj2G79akVHC+vq9n2HYD34WGtwaO1vIF1RHnPIU6KQb4QKoRMaqCfEu2ThiN5q4R07iG7ESKgYm4omGj5QcdLkNoIXfcuyVJVJ9TZP5lWXVW2QjwQd1LKFAAcd+0MxVd9mWZTJZa62/Ic6dr1NEDowZ+VsggYGa7hvgab8R5vjR6X+Fe4Gq7xsLIbYAU3lrznOUAtMfT4KKjsj3hCx+AuRvWnpEuweqnHZfm5U23NHl6YZ3vzmdZbLOcjSUD5ogF7K7hPDmkPYoCwc2JxJk01sjSS6ChhuH+iUqfbIpuUTFFqMu/YjemwMRw8BlInES9Gukud731hp301wgteCjm7iFjvzN7FBT0gi1h9O/BMMR0EXn2mNjmXilz2I6VwTIzoHsob+2fkHoWRFuwGR31dIsQtDam3P0/KYaYa7W/F5c+S4T6KcdxV1FmtHvNmvQ==
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_CLIENT_ID: AgA/tSs4oM+LrF3MFsMJcxRlynmCCpVlWQzsfbq7kpJuMJ9Hi1XSww9zVL8sjuAjbY+p9lew6ejR2RZucBHhvXXe1fe48FPPVXT301y7ZMouCpy3iqx2WjKCxsiYLwVwmseHQKT1H7zBarUfaKzIFr/pYpRAKpGyJjutbSuwV3naTiITx+wVgedk5VIuqf5xbnFbuEUpihMFY+QTk+Nq2aL5mf6FF3kkQ9rICRNt4cqUzQYVxANqMD4rEvkQHNY8rVNtCmwvNrW8epbT0VMFiSUY0FHy+OuGZdZNO+fEQU/8nsYwMkvcjoujyibj3HK+q0otf4ScGMhZkybR2xK4OUFLPFWVUijDb7DAAf1so0DJLkJthbogcO/JqdqXxAHQi3vEt3fK9cbJx7MLcuaZw+QJLjM4R3sxDnegNVTig7AReqWtHDd/aXD8vtzfnwBA++TkkfiDChSgPMpejwnj3SlP9Wrc6h83SHZjeQI/cWI7pqjm1tgP/O6tjH0+ttVMK54T5MiJR0VZT9yp086gr3arqW/fJAR0vWMFxLeYGEp2KLk+Q2SW5eOAxR0E4qJPKj4bxN1+KlJU6Jq6BxFIkZE2vVdoNbbyHDNBu8xoBBJ/XbMEE1trQJVzxz0zi6hacerFjhl4sT+VE1pJ5wMA0hsM+0ThNSbtnz3MQ3Eaimoy4qqyjxoaY6S1Deil0j+st4Y7q0KeeBgFdNTBsSUxRcMgdlwmZ4fafyorR5wClvUTQJ30c59m17KgrBaIJLIU2rfD99QHEfm44/QDcnXeauUKLx5eMwht/XY=
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_CLIENT_SECRET: AgAXIMB7HNHuT1CRDLq8JNZwct14w3qgvN066h7TDyooo32ltPgVWEoQkbs5yGb+2ZqI/POt4Byv/J665gsXS5mJgrgoJ8tiEcGg5VLhc+0FGMnQ1RJh9/zHelfybSe1TgAGHeECWwFPWCMJtaoaQYThf/T6T/F00W/OmdH1Fp4uBAb/NBaOKqyLGdsTVZpu9rai60RSrQebtftEv+kQGarV6ChcaV8Kz2UdZb7Bbfd4c5Cv9lX5i7uTp0VrBiMsInNzp2xFy1K8HQzxu0Auxt2TiFEO25S2yXDNzLwXyT18mcTippEz5A1d0jJkrr/6Qbua+bzpNUJIDuLrixwcDyEFMV3CNaMmjdz39yKPD4nNVYV9p8SP8wA+e/8Z9XjYG/eSA1Bh6Op9H2qRGqrcjP5K/FmPFtDdYbbSbKLrrfj5yGWllprzyOdNglffnC8OQ9nJwSvAhQP0Ih16QG94arh73z1La7EF4dy4zXuqomYgnyg2t342Qc9WoG+nmAWZdanHTTjTg9VNrrII4R6h93f5Rw/8bKImc8BpmS0qViKoqGKOGtfQEwkMODGCMuAKkUsu4Fyqc3ZHfk6VgTA7Av+rfaVWbn+stWP+spwMzHGwBGX/+bKXMnVWeK2Hw4/DDCm1OIisv05xmb5aAvpMGrtoUHwulbqVn4EbL1+mDgO01pX82Yu1AD/uX/broRdRKwZQ3c8YiO2mmfi7ryyx8gHd5FDafei8SOw=
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_TOKEN: AgCiXVtA6GoTPlWgRzOfzL1HLhe5/7wcSySQnhSni2CHkA5n18a42SBw/g83ktu6D9kvnvzZepnsfO0Jh+YzcHPANZnSZmA3q/r86d1iO4elvu/vWV4e6UXSzbVPFXdHMz+27jkbmQW4GxTgFWQb+H8OkY+VLFOJiZXkcR2vQXWWqsfQ9a2zZxCEw4pY+n2n6BEwke3eGtTEw89Vnuq+G7e+E+5TxyPa6pBNJNi50eMwfN2zhP1m9AUp4fYEfV1pBesb6u2KODmDx+k0OlajqCa64itK/XwJVaFvTjXnSPp28AqNdJwsPDrJhmEwiEPFzAOkmxrsj4s2O733jVVNB/Tjne0G/JsJtsDPGshyyCLJHgIN+XGmqxSkQcsst7VIx9nMw4xtS/EoQztQ/JV5dhDmvWLGVh40NZ5tEOeHPt/C58YB1W1A/AZ9xaJrlNKB+nijJRZj832mYAs1LBHAGfENXrcexXeRRTUxteUcCuEzjuIdEtF7dry14FvNvnVWDGjJWJGmPpJZjh7yaIjyZRezhCEjg/nGqYvgn2Ees+xoxMtKW1jJwW/YPXYNa1cDlE55ALWUO9aOFj/51YuxdsM3lfy5xPvChZaHJWxtbgh4h3j0vaspAIf1iPJqEl2jFJYgAC4bULUjShLK80f/Cc9rXB6hE6Kauk4HzUV8zrxcD8wdf88Sz8rSyOIHZRaODeJwoL+NgufxqIJeblRMmvRuEx4FwPE99KKIdB962paD1O8lUEHe1Yf0bFCxHAfuV5jt0wu4fCJeAzv6ZTZYua/9wY+qBfuvCFVNIpurzsfWW5lJAYlLVyvQ+Xv00CRHFnvjaQ8xosjnQuxEURtW+q3oQHkkdys0q21mOlRAXWSfgoJDNq3BKhcw3c+cnvARJ5scrqot2YB6vd1VLX+DsibEN3ys708XkwL6V4HnD6z6cPdrws03sZJloraVon14jfsLiJ1n9pOnMSuFXHWhLyQ3lnCT8QO8MtVyZrOyuSAGvofAsPef4FSdD7EH/Y5hD6q87gX5/2MXuP4XjFWgLrzpU0FhF4GEg14FmIdt642ehb3ZyDa1yKzxCdC2lEANEL6UwdwiDUShAfDY8NDOclrB5JCNJCvPNOF5QGHq5ab41pOBbCOCPfaNU+Xra1zf27LSOhT21B/jXYl0x3tXzP2fL/uy0+UEbpueUnnvuvoiEsfJRgstPmSS0wpAy5a3vNau8yKu7LL9N3u0hng3X4duojB4v9bp+sx/TYQS8Vqc5DcVKcs=
    RCLONE_CONFIG_JYUNDT_GMAIL_GDRIVE_TYPE: AgCkOeSJBWWbW47PvkeV1NN3WfOoU3xiOQjShDtLJuxZUEDrDl2uQiMusZJCOHPWHRyncE/c0UNK7V16R5vxRjZkZk8C5gru0DNtog02TBh0JjPOWTJM0qBFAcd2AlHOKGXuNCFXDn4sNiPGKvwns0CAjd/PPD7zuBBsdgBvkS+S4v7xcq4JFlNEOWLOCBKQBnxq8n6sq+7U0qksOmCg7kCt8qmy4dc3q44JZ0uUAhQ3unUzZEEg00foDVXoMT2FBsfC0HOh4VIwJpga6Cf0hXbAp8ARPZjtW39Zq0gzrx8EJ2oyX2oxlVXBCOZdfeKvDrw2U8Au414/IaogTYV0VVicULybgWKSipvOPgiJfmArxXbVYFCU8etS1tG/igeg6vnUu3U9VqDA09k80kXFRYRp8I/RnuP8UsuHk1C5rK5zK3ABQ/CDH9s4Ft3TTT6r1qKkKmn1m50flHQE2o7agIrBIqAY09l5TVAL1cYn+c6rYeY4PF8wSum9PHzjvOwxHNwWGxE8AOy+Rj5JrVByQEs6L8QKHj+nBX72spe1Ohl3gOt5ETvLeRJUB3JJIHS8myEXh2c7xJA6SXKBaQhkyLT1Jabz19JVyVnUC0qW+fySCANmWR2pARO/puO3oVLtDDZh8653G/58VpLZn6z5PZTFJVDso7Lww71ZKp1X1ZBzURcJO3w9e5Kjmrck4G7kA40JM6dWqQ==
  template:
    metadata:
      creationTimestamp: null
      name: rclone
      namespace: default
    type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone
  namespace: default
  labels:
    name: rclone
spec:
  capacity:
    storage: 1Pi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/backups/cloud
    server: callisto.wellesleynet.com
  mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone
  namespace: default
spec:
  selector:
    matchLabels:
      name: rclone
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone
  namespace: default
data:
  RCLONE_DRIVE_SKIP_DANGLING_SHORTCUTS: "true"
  RCLONE_DRIVE_CHUNK_SIZE: "256M"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone
  namespace: default
spec:
  schedule: "00 5 * * * "
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rclone-jyundt-gmail
            image: rclone/rclone:1.62.2
            args:
            - sync
            - "jyundt_gmail_gdrive:/"
            - "/mnt/rclone/jyundt_gmail_gdrive"
            volumeMounts:
            - name: rclone
              mountPath: /mnt/rclone
            envFrom:
              - configMapRef:
                  name: rclone
              - secretRef:
                  name: rclone
          - name: rclone-jyundt-digitalocean
            image: rclone/rclone:1.62.2
            args:
            - sync
            - "jyundt_digitalocean_gdrive:/"
            - "/mnt/rclone/jyundt_digitalocean_gdrive"
            volumeMounts:
            - name: rclone
              mountPath: /mnt/rclone
            envFrom:
              - configMapRef:
                  name: rclone
              - secretRef:
                  name: rclone
          - name: rclone-emily-gmail
            image: rclone/rclone:1.62.2
            args:
            - sync
            - "emily_gmail_gdrive:/"
            - "/mnt/rclone/emily_gmail_gdrive"
            volumeMounts:
            - name: rclone
              mountPath: /mnt/rclone
            envFrom:
              - configMapRef:
                  name: rclone
              - secretRef:
                  name: rclone
          volumes:
            - name: rclone
              persistentVolumeClaim:
                claimName: rclone
          restartPolicy: OnFailure
