---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shametime
  name: shametime
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shametime
  template:
    metadata:
      labels:
        app: shametime
    spec:
      containers:
      - image: registry.digitalocean.com/jyundt/shametime:202201151215
        imagePullPolicy: Always
        name: shametime
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-registry-creds
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: shametime
spec:
  selector:
    app: shametime
  ports:
  - name: shametime
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shametime
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: shametime.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: shametime
            port:
              number: 80
  - host: www.shametime.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: shametime
            port:
              number: 8080
  tls:
  - hosts:
    - shametime.com
    secretName: shametime-com-tls
  - hosts:
    - www.shametime.com
    secretName: www-shametime-com-tls

