---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shametime
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: shametime
  name: shametime
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shametime
  serviceName: shametime 
  template:
    metadata:
      labels:
        app: shametime
    spec:
      containers:
      - env:
        - name: TZ
          value: America/New_York
        image: nginx:stable-alpine
        imagePullPolicy: Always
        name: shametime
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shametime
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: shametime
        persistentVolumeClaim:
          claimName: shametime

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: shametime
spec:
  selector:
    app: shametime
  ports:
  - name: shametime
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shametime
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
  - host: shametime.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: shametime
            port:
              number: 80
  - host: www.shametime.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: shametime
            port:
              number: 8080
  tls:
  - hosts:
    - shametime.com
    secretName: shametime-com-tls
  - hosts:
    - www.shametime.com
    secretName: www-shametime-com-tls

