---
- name: "Create gmvault dir"
  file:
    path: "{{gmvault_conf_dir}}"
    state: directory
    mode: 0755
    group: "root"
    owner: "root"

- name: "Copy gmvault files"
  copy:
    src: "{{item.src}}"
    dest: "{{gmvault_conf_dir}}/{{item.src}}"
    mode: "{{item.mode}}"
    owner: "root"
    group: "root"
  with_items:
    -
      src: "gmvault_defaults.conf"
      mode: "0664"
    -
      src: "token.sec"
      mode: "0600"

- name: "Copy Dockerfile template"
  template:
    src: "Dockerfile.j2"
    dest: "{{gmvault_conf_dir}}/Dockerfile"
    mode: 0644
    owner: "root"
    group: "root"

# This is a bit clunky, but the passwords are google app specific passwords
# that gmvault then encrypts again. Because they are binary files, and
# because gmvault expects the password files to include the email address
# (which I consider "sensitive"), I had to mask this with a vault var (dict)
- name: "Copy google app passwords"
  copy:
    src: "{{item.file}}"
    dest: "{{gmvault_conf_dir}}/{{item.email}}.passwd"
    mode: "0600"
    owner: "root"
    group: "root"
  with_items: "{{gmvault_creds}}"

- name: "Build docker container"
  docker_image:
    path: "{{gmvault_conf_dir}}"
    name: "gmvault:{{gmvault_version}}"

# I'm cheating and using flock to make sure these nightly (quick) and
# monthly (full) backups don't clobber each other
- name: "Create cron jobs for monthly full sync backups"
  cron:
    name: "{{item.email}} gmvault monthly full backup"
    job: "{{cronwrapper_cmd}} --tag gmvault-monthly:{{item.email}} -- /usr/bin/docker run --rm -v {{gmvault_conf_dir}}:/root/.gmvault -v {{gmvault_db_dir}}:{{gmvault_db_dir}} gmvault-monthly:{{gmvault_version}} sync -p -d {{gmvault_db_dir}}/{{item.email}} {{item.email}}"
    user: "root"
    special_time: "monthly"
    cron_file: "gmvault-monthly"
  with_items: "{{gmvault_creds}}"

- name: "Create cron jobs for nightly quick sync backups"
  cron:
    name: "{{item.email}} gmvault nightly quick backup"
    job: "{{cronwrapper_cmd}} --tag gmvault-daily:{{item.email}} -- /usr/bin/docker run --rm -v {{gmvault_conf_dir}}:/root/.gmvault -v {{gmvault_db_dir}}:{{gmvault_db_dir}} gmvault:{{gmvault_version}} sync -p -d {{gmvault_db_dir}}/{{item.email}} {{item.email}} -t quick"
    user: "root"
    special_time: "daily"
    cron_file: "gmvault-daily"
  with_items: "{{gmvault_creds}}"
